// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package electric

import (
	"context"
	"net/http"

	"github.com/google/uuid"
	"github.com/simonjanss/rig/runtime/electric"
	"github.com/simonjanss/rig/runtime/rigerr"
	"github.com/simonjanss/rig/runtime/tenancy"
)

// RigNotificationRecipientShapeParams are the query parameters this shape
// accepts.
//
// They are the application's, not the protocol's: a subscriber uses them to
// ask for less, and the scoping function turns them into conditions. Nothing
// here can ask for more.
type RigNotificationRecipientShapeParams struct {
	// This shape declares none.
}

// parseRigNotificationRecipientShapeParams reads the declared parameters.
func parseRigNotificationRecipientShapeParams(r *http.Request) (RigNotificationRecipientShapeParams, error) {
	var p RigNotificationRecipientShapeParams

	return p, nil
}

// RigNotificationRecipientScope narrows the shape further.
//
// It receives a filter that already carries the tenant and lifecycle
// conditions, and can only add to it — every condition is joined with AND,
// so there is nothing a scope can write that widens what the subscriber sees.
// Add conditions through the Where methods rather than as text: they bind
// their values, and a shape filter built by string concatenation is an
// injection point with a streaming response attached.
//
// Returning an error refuses the subscription.
type RigNotificationRecipientScope func(ctx context.Context, r *http.Request, claims tenancy.Claims, p RigNotificationRecipientShapeParams, w *electric.Where) error

// handleRigNotificationRecipientShape serves GET
// /electric/rig_notification_recipient.
func handleRigNotificationRecipientShape(s Server, scope RigNotificationRecipientScope) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		claims, where, ok := prepare(s, w, r, false)
		if !ok {
			return
		}

		// Every row this shape can ever carry belongs to the caller's tenant. It is
		// the first condition, and nothing below can remove it.
		where.Eq("tenant_id", claims.TenantID.String())
		// This table is owner-scoped, so a subscriber sees its own rows and nothing
		// else. Here rather than in the scope function below, for the reason the
		// repository does not make anybody remember it: a narrowing the application
		// has to add by hand is a narrowing somebody eventually does not.
		// A caller with no account is refused rather than narrowed. An API key and a
		// system credential both have a nil identifier, and comparing against one
		// matches nothing *silently* — which is the wrong kind of correct, because a
		// subscriber handed an empty stream cannot tell it from having nothing to
		// receive.
		if claims.AccountID == uuid.Nil {
			fail(s, w, r, rigerr.Forbidden("this shape is scoped to one account, and this credential is not one"))
			return
		}
		where.Eq("account_id", claims.AccountID.String())
		// A retired row stops appearing in reads, so it stops appearing in a live
		// stream too.
		where.IsNull("deleted_at")

		params, err := parseRigNotificationRecipientShapeParams(r)
		if err != nil {
			fail(s, w, r, err)
			return
		}

		if scope != nil {
			if err := scope(r.Context(), r, claims, params, where); err != nil {
				fail(s, w, r, err)
				return
			}
		}

		s.Proxy.Serve(w, r, electric.Shape{
			Table:  "rig_notification_recipient",
			Where:  where.SQL(),
			Params: where.Params(),
			// The readable columns, named rather than left to default. A shape carries
			// every column it names to every subscriber, and a column that is not in the
			// API has no business in a live stream either.
			Columns: RigNotificationRecipientShapeColumns,
		})
	}
}

// RigNotificationRecipientShapeColumns are the columns this shape carries.
//
// They are the resource's readable fields — the same set a GET returns —
// so a column excluded from the API is excluded here without anybody having to
// remember.
var RigNotificationRecipientShapeColumns = []string{
	"id",
	"tenant_id",
	"notification_id",
	"account_id",
	"created_at",
	"updated_at",
	"deleted_at",
	"deleted_by_account_id",
	"kind",
	"group_key",
	"event_count",
	"read_at",
}
