// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the code that calls it.

/** What happened to one copy of an inbox line on its way to a channel. */
export const NotificationDeliveryState = {
    /**
     * Owed and not yet claimed, or claimed by a dispatcher that has not marked
     * it.
     */
    Pending: "Pending",
    /**
     * A channel accepted it, which is not the same as it arriving — rig does
     * not pretend to know the difference.
     */
    Sent: "Sent",
    /**
     * Past notifications.max_attempts, and no longer claimed. Without the cap a
     * permanently broken address would consume a lease forever.
     */
    Failed: "Failed",
    /**
     * A setting refused it, or the row it was a copy of was retired before it
     * went. Worth telling apart from Failed in a report: it is 'we decided
     * against this' rather than 'this did not work'.
     */
    Skipped: "Skipped",
} as const;

/**
 * One of the values of NotificationDeliveryState.
 *
 * The type and the object share a name on purpose: TypeScript keeps types and
 * values in separate namespaces, so `NotificationDeliveryState.Pending` and `:
 * NotificationDeliveryState` both read the way somebody would write them.
 */
export type NotificationDeliveryState = (typeof NotificationDeliveryState)[keyof typeof NotificationDeliveryState];

/**
 * Every value of NotificationDeliveryState, in declaration order. It is what a
 * picker is drawn from.
 */
export const allNotificationDeliveryState: readonly NotificationDeliveryState[] = [NotificationDeliveryState.Pending, NotificationDeliveryState.Sent, NotificationDeliveryState.Failed, NotificationDeliveryState.Skipped];
