// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the code that calls it.

import type { NotificationChannel } from "./notification_channel.gen.js";
import type { NotificationDigest } from "./notification_digest.gen.js";
import type { FieldError } from "@rig/client";

/**
 * NotificationSettingListQuery is the query string listNotificationSettings
 * takes.
 *
 * Every member is optional. The server applies a parameter's default when the
 * parameter is absent, so leaving one out is how to ask for the default rather
 * than for zero.
 */
export type NotificationSettingListQuery = {
    /** Maximum rows to return. */
    limit?: number;
    /** Rows to skip before the first returned row. */
    offset?: number;
    /**
     * How wide to read: own for the notificationsettings the caller created,
     * which is the default, or all for every one in the tenant. Asking for all
     * requires the rig_notification_setting.read.all permission and is refused
     * without it, rather than quietly answering with fewer rows.
     */
    scope?: string;
};

/**
 * NotificationSettingCreateInput is what creating a NotificationSetting takes.
 *
 * A field the server fills in — the identifier, the tenant, the audit columns
 * — is not here: those are not a caller's to send.
 */
export type NotificationSettingCreateInput = {
    /** Whose preference it is. */
    accountId: string;
    /**
     * Null is the default for the channel, which is the second step of the
     * resolution.
     */
    kind?: string | null;
    /** Which channel it answers for. */
    channel: NotificationChannel;
    /**
     * False writes no delivery row at all. Not the same as digest Off, which is
     * about preferring to look rather than be told.
     */
    isEnabled: boolean;
    /**
     * Immediate sends each on its own; anything else waits for the window and
     * goes out as one message.
     */
    digest: NotificationDigest;
    /**
     * When to start delivering, in the account time zone. Null means all day. A
     * window that wraps midnight is ordinary: 22:00 to 06:00 is how somebody
     * says "not overnight".
     */
    activeFrom?: string | null;
    /**
     * When to stop. Outside the window a delivery is held, not dropped: the
     * inbox line exists either way, and a discarded copy makes the badge and
     * the mailbox disagree.
     */
    activeUntil?: string | null;
    /**
     * ISO weekdays, 1 being Monday. Empty means every day. An array rather than
     * a bitmask because [1,2,3,4,5] is legible in a settings payload and 62 is
     * not.
     */
    activeDays: number[];
};

/**
 * NotificationSettingCreateFields is what a validation failure says, shaped
 * like the body it is about — one member per member, so each message can be
 * put beside the control it belongs to.
 *
 * A member is absent when there was nothing wrong with that field. It arrives
 * as the `fields` of the error the call threw.
 */
export type NotificationSettingCreateFields = {
    accountId?: FieldError;
    kind?: FieldError;
    channel?: FieldError;
    isEnabled?: FieldError;
    digest?: FieldError;
    activeFrom?: FieldError;
    activeUntil?: FieldError;
    activeDays?: FieldError;
    /**
     * What was wrong with the request as a whole rather than with any one
     * field.
     */
    entity?: FieldError;
};

/**
 * NotificationSettingGetQuery is the query string getNotificationSetting takes.
 *
 * Every member is optional. The server applies a parameter's default when the
 * parameter is absent, so leaving one out is how to ask for the default rather
 * than for zero.
 */
export type NotificationSettingGetQuery = {
    /**
     * How wide to read: own for the notificationsettings the caller created,
     * which is the default, or all for every one in the tenant. Asking for all
     * requires the rig_notification_setting.read.all permission and is refused
     * without it, rather than quietly answering with fewer rows.
     */
    scope?: string;
};

/**
 * NotificationSettingUpdateInput is what changing a NotificationSetting takes.
 *
 * A field left out is left alone. A nullable field set to `null` is cleared —
 * which is why only some members accept one: a column that cannot hold null has
 * no way to be given one.
 *
 * `undefined` reads as left out, because JSON.stringify drops the key either
 * way. It is `null` that is a request to clear.
 */
export type NotificationSettingUpdateInput = {
    /** Whose preference it is. */
    accountId?: string;
    /**
     * Null is the default for the channel, which is the second step of the
     * resolution.
     */
    kind?: string | null;
    /** Which channel it answers for. */
    channel?: NotificationChannel;
    /**
     * False writes no delivery row at all. Not the same as digest Off, which is
     * about preferring to look rather than be told.
     */
    isEnabled?: boolean;
    /**
     * Immediate sends each on its own; anything else waits for the window and
     * goes out as one message.
     */
    digest?: NotificationDigest;
    /**
     * When to start delivering, in the account time zone. Null means all day. A
     * window that wraps midnight is ordinary: 22:00 to 06:00 is how somebody
     * says "not overnight".
     */
    activeFrom?: string | null;
    /**
     * When to stop. Outside the window a delivery is held, not dropped: the
     * inbox line exists either way, and a discarded copy makes the badge and
     * the mailbox disagree.
     */
    activeUntil?: string | null;
    /**
     * ISO weekdays, 1 being Monday. Empty means every day. An array rather than
     * a bitmask because [1,2,3,4,5] is legible in a settings payload and 62 is
     * not.
     */
    activeDays?: number[];
};

/**
 * NotificationSettingUpdateFields is what a validation failure says, shaped
 * like the body it is about — one member per member, so each message can be
 * put beside the control it belongs to.
 *
 * A member is absent when there was nothing wrong with that field. It arrives
 * as the `fields` of the error the call threw.
 */
export type NotificationSettingUpdateFields = {
    accountId?: FieldError;
    kind?: FieldError;
    channel?: FieldError;
    isEnabled?: FieldError;
    digest?: FieldError;
    activeFrom?: FieldError;
    activeUntil?: FieldError;
    activeDays?: FieldError;
    /**
     * What was wrong with the request as a whole rather than with any one
     * field.
     */
    entity?: FieldError;
};

