// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the code that calls it.

/**
 * What somebody is doing with the thing they are on, as far as their own client
 * can tell.
 */
export const PresenceActivity = {
    /**
     * Looking at it. The default, and what a heartbeat says when nothing else
     * was claimed.
     */
    Viewing: "viewing",
    /**
     * Typing into it. What draws the ring on a control somebody else has open,
     * and the only reason this column exists rather than presence being a row
     * per person.
     */
    Editing: "editing",
} as const;

/**
 * One of the values of PresenceActivity.
 *
 * The type and the object share a name on purpose: TypeScript keeps types and
 * values in separate namespaces, so `PresenceActivity.Viewing` and `:
 * PresenceActivity` both read the way somebody would write them.
 */
export type PresenceActivity = (typeof PresenceActivity)[keyof typeof PresenceActivity];

/**
 * Every value of PresenceActivity, in declaration order. It is what a picker is
 * drawn from.
 */
export const allPresenceActivity: readonly PresenceActivity[] = [PresenceActivity.Viewing, PresenceActivity.Editing];
