// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the code that calls it.

import type { RigAccountKind } from "./rig_account_kind.gen.js";
import type { RigAccountRoleLevel } from "./rig_account_role_level.gen.js";
import type {
    TodoFilter,
    TodoFilterContains,
    TodoFilterEquals,
    TodoFilterLike,
    TodoFilterNull,
    TodoFilterRange,
} from "./todo_query.gen.js";

/** Conditions a RigAccount must satisfy to match a search. */
export type RigAccountFilter = {
    /** Fields that must equal the given value. */
    equals?: RigAccountFilterEquals | null;
    /** Fields that must not equal the given value. */
    notEquals?: RigAccountFilterEquals | null;
    /** Fields that must be greater than the given value. */
    greaterThan?: RigAccountFilterRange | null;
    /** Fields that must be less than the given value. */
    smallerThan?: RigAccountFilterRange | null;
    /** Fields that must be greater than or equal to the given value. */
    greaterOrEqual?: RigAccountFilterRange | null;
    /** Fields that must be less than or equal to the given value. */
    smallerOrEqual?: RigAccountFilterRange | null;
    /** Fields that must be one of the given values. */
    contains?: RigAccountFilterContains | null;
    /** Fields that must not be one of the given values. */
    notContains?: RigAccountFilterContains | null;
    /** Text fields that must match the given pattern. */
    like?: RigAccountFilterLike | null;
    /** Text fields that must not match the given pattern. */
    notLike?: RigAccountFilterLike | null;
    /** Fields that must be null. */
    null?: RigAccountFilterNull | null;
    /** Fields that must not be null. */
    notNull?: RigAccountFilterNull | null;
    /** Combine this filter's conditions with OR instead of AND. */
    orCondition: boolean;
    /**
     * Sub-filters combined with this one, so that AND and OR can be mixed to
     * any depth.
     */
    nestedFilters: RigAccountFilter[];
    /**
     * Relations with no row matching the given conditions. An empty one asks
     * for no related row at all.
     *
     * This is where a negation belongs when what you mean is "not": it negates
     * whether a matching related row exists, so a row with no related row at
     * all satisfies it. The negative operators above negate the comparison
     * instead and still require the related row to be there — "no related row
     * called X" is here, "a related row not called X" is NotEquals.
     */
    without?: RigAccountFilterWithout | null;
};

/** Set-membership conditions on RigAccount fields. */
export type RigAccountFilterContains = {
    /** Unique identifier for this row. */
    id: string[];
    /**
     * The person this account belongs to, or null for a service account, which
     * is nobody.
     */
    identityId: string[];
    /** When this row was created. Set automatically and never changes. */
    createdAt: string[];
    /** Account that created this row, taken from the request's claims. */
    createdByAccountId: string[];
    /** When this row was last updated. Set automatically on every update. */
    updatedAt: string[];
    /** Account that last updated this row, taken from the request's claims. */
    updatedByAccountId: string[];
    /** When this row was soft-deleted. Null while the row is live. */
    deletedAt: string[];
    /** Account that soft-deleted this row, taken from the request's claims. */
    deletedByAccountId: string[];
    /** Whether this is a person or a service account an integration acts as. */
    kind: RigAccountKind[];
    /**
     * The coarse level in this tenant: Owner, Admin, or Basic. Somebody can be
     * an Owner here and Basic elsewhere.
     */
    role: RigAccountRoleLevel[];
    /**
     * A copy of the identity's address, kept here so listing accounts is one
     * query. For a service account it is a label nobody signs in with.
     */
    emailAddress: string[];
    /** What to call the person in this tenant. */
    displayName: string[];
    /** IANA name, for example Europe/Stockholm. Null means UTC. */
    timeZone: string[];
    /**
     * Whether the account may be used. A disabled account is refused with 403,
     * not 401.
     */
    isActive: boolean[];
    /**
     * API key this row was created through, when it was an integration rather
     * than a person.
     */
    createdByApiKeyId: string[];
    /**
     * API key this row was last updated through, when it was an integration
     * rather than a person.
     */
    updatedByApiKeyId: string[];
    /**
     * API key this row was soft-deleted through, when it was an integration
     * rather than a person.
     */
    deletedByApiKeyId: string[];
    /**
     * Conditions on one of this row's AssigneeAccountTodos.
     *
     * Every condition has to hold of the same one, not of the set between them.
     *
     * Under the negative operators this asks whether one of them differs, which
     * is not the same as none of them matching: a row can have one that matches
     * and one that does not, satisfying the first and failing the second.
     * Without.AssigneeAccountTodos asks the second.
     */
    assigneeAccountTodos?: TodoFilterContains | null;
    /**
     * Conditions on this row's CreatedByAccount.
     *
     * A row with no CreatedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * CreatedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching CreatedByAccount, which a
     * row with none satisfies — use Without.CreatedByAccount.
     */
    createdByAccount?: RigAccountFilterContains | null;
    /**
     * Conditions on this row's DeletedByAccount.
     *
     * A row with no DeletedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * DeletedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching DeletedByAccount, which a
     * row with none satisfies — use Without.DeletedByAccount.
     */
    deletedByAccount?: RigAccountFilterContains | null;
    /**
     * Conditions on this row's UpdatedByAccount.
     *
     * A row with no UpdatedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * UpdatedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching UpdatedByAccount, which a
     * row with none satisfies — use Without.UpdatedByAccount.
     */
    updatedByAccount?: RigAccountFilterContains | null;
};

/** Exact-match conditions on RigAccount fields. */
export type RigAccountFilterEquals = {
    /** Unique identifier for this row. */
    id?: string | null;
    /**
     * The person this account belongs to, or null for a service account, which
     * is nobody.
     */
    identityId?: string | null;
    /** When this row was created. Set automatically and never changes. */
    createdAt?: string | null;
    /** Account that created this row, taken from the request's claims. */
    createdByAccountId?: string | null;
    /** When this row was last updated. Set automatically on every update. */
    updatedAt?: string | null;
    /** Account that last updated this row, taken from the request's claims. */
    updatedByAccountId?: string | null;
    /** When this row was soft-deleted. Null while the row is live. */
    deletedAt?: string | null;
    /** Account that soft-deleted this row, taken from the request's claims. */
    deletedByAccountId?: string | null;
    /** Whether this is a person or a service account an integration acts as. */
    kind?: RigAccountKind | null;
    /**
     * The coarse level in this tenant: Owner, Admin, or Basic. Somebody can be
     * an Owner here and Basic elsewhere.
     */
    role?: RigAccountRoleLevel | null;
    /**
     * A copy of the identity's address, kept here so listing accounts is one
     * query. For a service account it is a label nobody signs in with.
     */
    emailAddress?: string | null;
    /** What to call the person in this tenant. */
    displayName?: string | null;
    /** IANA name, for example Europe/Stockholm. Null means UTC. */
    timeZone?: string | null;
    /**
     * Whether the account may be used. A disabled account is refused with 403,
     * not 401.
     */
    isActive?: boolean | null;
    /**
     * API key this row was created through, when it was an integration rather
     * than a person.
     */
    createdByApiKeyId?: string | null;
    /**
     * API key this row was last updated through, when it was an integration
     * rather than a person.
     */
    updatedByApiKeyId?: string | null;
    /**
     * API key this row was soft-deleted through, when it was an integration
     * rather than a person.
     */
    deletedByApiKeyId?: string | null;
    /**
     * Conditions on one of this row's AssigneeAccountTodos.
     *
     * Every condition has to hold of the same one, not of the set between them.
     *
     * Under the negative operators this asks whether one of them differs, which
     * is not the same as none of them matching: a row can have one that matches
     * and one that does not, satisfying the first and failing the second.
     * Without.AssigneeAccountTodos asks the second.
     */
    assigneeAccountTodos?: TodoFilterEquals | null;
    /**
     * Conditions on this row's CreatedByAccount.
     *
     * A row with no CreatedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * CreatedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching CreatedByAccount, which a
     * row with none satisfies — use Without.CreatedByAccount.
     */
    createdByAccount?: RigAccountFilterEquals | null;
    /**
     * Conditions on this row's DeletedByAccount.
     *
     * A row with no DeletedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * DeletedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching DeletedByAccount, which a
     * row with none satisfies — use Without.DeletedByAccount.
     */
    deletedByAccount?: RigAccountFilterEquals | null;
    /**
     * Conditions on this row's UpdatedByAccount.
     *
     * A row with no UpdatedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * UpdatedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching UpdatedByAccount, which a
     * row with none satisfies — use Without.UpdatedByAccount.
     */
    updatedByAccount?: RigAccountFilterEquals | null;
};

/** Pattern conditions on RigAccount text fields. */
export type RigAccountFilterLike = {
    /**
     * A copy of the identity's address, kept here so listing accounts is one
     * query. For a service account it is a label nobody signs in with.
     */
    emailAddress?: string | null;
    /** What to call the person in this tenant. */
    displayName?: string | null;
    /** IANA name, for example Europe/Stockholm. Null means UTC. */
    timeZone?: string | null;
    /**
     * Conditions on one of this row's AssigneeAccountTodos.
     *
     * Every condition has to hold of the same one, not of the set between them.
     *
     * Under the negative operators this asks whether one of them differs, which
     * is not the same as none of them matching: a row can have one that matches
     * and one that does not, satisfying the first and failing the second.
     * Without.AssigneeAccountTodos asks the second.
     */
    assigneeAccountTodos?: TodoFilterLike | null;
    /**
     * Conditions on this row's CreatedByAccount.
     *
     * A row with no CreatedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * CreatedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching CreatedByAccount, which a
     * row with none satisfies — use Without.CreatedByAccount.
     */
    createdByAccount?: RigAccountFilterLike | null;
    /**
     * Conditions on this row's DeletedByAccount.
     *
     * A row with no DeletedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * DeletedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching DeletedByAccount, which a
     * row with none satisfies — use Without.DeletedByAccount.
     */
    deletedByAccount?: RigAccountFilterLike | null;
    /**
     * Conditions on this row's UpdatedByAccount.
     *
     * A row with no UpdatedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * UpdatedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching UpdatedByAccount, which a
     * row with none satisfies — use Without.UpdatedByAccount.
     */
    updatedByAccount?: RigAccountFilterLike | null;
};

/** Presence conditions on nullable RigAccount fields. */
export type RigAccountFilterNull = {
    /**
     * The person this account belongs to, or null for a service account, which
     * is nobody.
     */
    identityId?: boolean | null;
    /** Account that created this row, taken from the request's claims. */
    createdByAccountId?: boolean | null;
    /** When this row was last updated. Set automatically on every update. */
    updatedAt?: boolean | null;
    /** Account that last updated this row, taken from the request's claims. */
    updatedByAccountId?: boolean | null;
    /** When this row was soft-deleted. Null while the row is live. */
    deletedAt?: boolean | null;
    /** Account that soft-deleted this row, taken from the request's claims. */
    deletedByAccountId?: boolean | null;
    /** IANA name, for example Europe/Stockholm. Null means UTC. */
    timeZone?: boolean | null;
    /**
     * API key this row was created through, when it was an integration rather
     * than a person.
     */
    createdByApiKeyId?: boolean | null;
    /**
     * API key this row was last updated through, when it was an integration
     * rather than a person.
     */
    updatedByApiKeyId?: boolean | null;
    /**
     * API key this row was soft-deleted through, when it was an integration
     * rather than a person.
     */
    deletedByApiKeyId?: boolean | null;
    /**
     * Conditions on one of this row's AssigneeAccountTodos.
     *
     * Every condition has to hold of the same one, not of the set between them.
     *
     * Under the negative operators this asks whether one of them differs, which
     * is not the same as none of them matching: a row can have one that matches
     * and one that does not, satisfying the first and failing the second.
     * Without.AssigneeAccountTodos asks the second.
     */
    assigneeAccountTodos?: TodoFilterNull | null;
    /**
     * Conditions on this row's CreatedByAccount.
     *
     * A row with no CreatedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * CreatedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching CreatedByAccount, which a
     * row with none satisfies — use Without.CreatedByAccount.
     */
    createdByAccount?: RigAccountFilterNull | null;
    /**
     * Conditions on this row's DeletedByAccount.
     *
     * A row with no DeletedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * DeletedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching DeletedByAccount, which a
     * row with none satisfies — use Without.DeletedByAccount.
     */
    deletedByAccount?: RigAccountFilterNull | null;
    /**
     * Conditions on this row's UpdatedByAccount.
     *
     * A row with no UpdatedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * UpdatedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching UpdatedByAccount, which a
     * row with none satisfies — use Without.UpdatedByAccount.
     */
    updatedByAccount?: RigAccountFilterNull | null;
};

/** Ordering conditions on RigAccount fields that can be compared. */
export type RigAccountFilterRange = {
    /** When this row was created. Set automatically and never changes. */
    createdAt?: string | null;
    /** When this row was last updated. Set automatically on every update. */
    updatedAt?: string | null;
    /** When this row was soft-deleted. Null while the row is live. */
    deletedAt?: string | null;
    /**
     * Conditions on one of this row's AssigneeAccountTodos.
     *
     * Every condition has to hold of the same one, not of the set between them.
     *
     * Under the negative operators this asks whether one of them differs, which
     * is not the same as none of them matching: a row can have one that matches
     * and one that does not, satisfying the first and failing the second.
     * Without.AssigneeAccountTodos asks the second.
     */
    assigneeAccountTodos?: TodoFilterRange | null;
    /**
     * Conditions on this row's CreatedByAccount.
     *
     * A row with no CreatedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * CreatedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching CreatedByAccount, which a
     * row with none satisfies — use Without.CreatedByAccount.
     */
    createdByAccount?: RigAccountFilterRange | null;
    /**
     * Conditions on this row's DeletedByAccount.
     *
     * A row with no DeletedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * DeletedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching DeletedByAccount, which a
     * row with none satisfies — use Without.DeletedByAccount.
     */
    deletedByAccount?: RigAccountFilterRange | null;
    /**
     * Conditions on this row's UpdatedByAccount.
     *
     * A row with no UpdatedByAccount never matches, and that holds for the
     * negative operators too: under NotEquals this asks whether the
     * UpdatedByAccount is there and differs, so a row without one fails that as
     * well. To ask the other question — no matching UpdatedByAccount, which a
     * row with none satisfies — use Without.UpdatedByAccount.
     */
    updatedByAccount?: RigAccountFilterRange | null;
};

/** Relations a RigAccount must have no matching row for. */
export type RigAccountFilterWithout = {
    /**
     * Match rows with no AssigneeAccountTodos satisfying these conditions,
     * including rows with none at all.
     *
     * This negates the existence of a matching row rather than the comparison,
     * which is the whole difference from NotEquals.AssigneeAccountTodos: that
     * one is satisfied by one of them differing, and a row can have one that
     * differs and one that matches at the same time. An empty object asks for
     * rows with no AssigneeAccountTodos at all.
     */
    assigneeAccountTodos?: TodoFilter | null;
    /**
     * Match rows with no CreatedByAccount satisfying these conditions,
     * including rows that have none at all.
     *
     * This negates the existence of the related row rather than the comparison,
     * which is the whole difference from NotEquals.CreatedByAccount: that one
     * needs the CreatedByAccount to be there and to differ, so a row without
     * one fails it and satisfies this. An empty object asks for rows with no
     * CreatedByAccount at all.
     */
    createdByAccount?: RigAccountFilter | null;
    /**
     * Match rows with no DeletedByAccount satisfying these conditions,
     * including rows that have none at all.
     *
     * This negates the existence of the related row rather than the comparison,
     * which is the whole difference from NotEquals.DeletedByAccount: that one
     * needs the DeletedByAccount to be there and to differ, so a row without
     * one fails it and satisfies this. An empty object asks for rows with no
     * DeletedByAccount at all.
     */
    deletedByAccount?: RigAccountFilter | null;
    /**
     * Match rows with no UpdatedByAccount satisfying these conditions,
     * including rows that have none at all.
     *
     * This negates the existence of the related row rather than the comparison,
     * which is the whole difference from NotEquals.UpdatedByAccount: that one
     * needs the UpdatedByAccount to be there and to differ, so a row without
     * one fails it and satisfies this. An empty object asks for rows with no
     * UpdatedByAccount at all.
     */
    updatedByAccount?: RigAccountFilter | null;
};

