// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the code that calls it.

import type { Pagination } from "./objects.gen.js";
import type { TodoPriority } from "./todo_priority.gen.js";
import type { TodoStatus } from "./todo_status.gen.js";
import type { TodoVersionType } from "./todo_version_type.gen.js";

/**
 * One item on the board.
 *
 * Every field the server returns, and no field it does not: this is the
 * readable projection of the row rather than the row.
 */
export type Todo = {
    /** Unique identifier for this row. */
    id: string;
    /** Tenant this row belongs to. Every query is scoped by it. */
    tenantId: string;
    /** What needs doing, in a few words. */
    title: string;
    /** The longer story, or null while the title says it all. */
    description?: string | null;
    /** Which column of the board the item is in. */
    status: TodoStatus;
    /** How urgently the item wants attention. */
    priority: TodoPriority;
    /** Who has taken the item, or null while nobody has. */
    assigneeAccountId?: string | null;
    /** When this row was created. Set automatically and never changes. */
    createdAt: string;
    /** Account that created this row, taken from the request's claims. */
    createdByAccountId?: string | null;
    /** When this row was last updated. Set automatically on every update. */
    updatedAt?: string | null;
    /** Account that last updated this row, taken from the request's claims. */
    updatedByAccountId?: string | null;
    /** When this row was soft-deleted. Null while the row is live. */
    deletedAt?: string | null;
    /** Account that soft-deleted this row, taken from the request's claims. */
    deletedByAccountId?: string | null;
    /**
     * Whether this row is the live version or an immutable snapshot of a
     * previous one.
     */
    versionType: TodoVersionType;
    /** The row this snapshot was copied from. Null on live rows. */
    snapshotFromTodoId?: string | null;
    /**
     * The source row's last-updated time at the moment this snapshot was taken.
     * This identifies the version captured, not when the copy was made.
     */
    snapshotFromTodoAt?: string | null;
};

/** A page of Todos. */
export type TodoListResponse = {
    /** The rows in this page. */
    data: Todo[];
    /** Where this page sits in the full result set. */
    pagination: Pagination;
};

/**
 * TodoRow is a Todo as a live-sync stream sends it.
 *
 * The same row as Todo, under different keys. A stream carries what Postgres
 * printed, so the keys are column names — `created_at` where the API sends
 * `createdAt` — and the values have been through the corrections in the
 * streaming runtime, which is what makes a timestamp here the same string the
 * API would have sent.
 *
 * A member is nullable rather than optional: the sync service sends every
 * column of the projection on every row, with a null where the column is null,
 * so nothing here is ever absent.
 */
export type TodoRow = {
    /** Unique identifier for this row. */
    id: string;
    /** Tenant this row belongs to. Every query is scoped by it. */
    tenant_id: string;
    /** What needs doing, in a few words. */
    title: string;
    /** The longer story, or null while the title says it all. */
    description: string | null;
    /** Which column of the board the item is in. */
    status: TodoStatus;
    /** How urgently the item wants attention. */
    priority: TodoPriority;
    /** Who has taken the item, or null while nobody has. */
    assignee_account_id: string | null;
    /** When this row was created. Set automatically and never changes. */
    created_at: string;
    /** Account that created this row, taken from the request's claims. */
    created_by_account_id: string | null;
    /** When this row was last updated. Set automatically on every update. */
    updated_at: string | null;
    /** Account that last updated this row, taken from the request's claims. */
    updated_by_account_id: string | null;
    /** When this row was soft-deleted. Null while the row is live. */
    deleted_at: string | null;
    /** Account that soft-deleted this row, taken from the request's claims. */
    deleted_by_account_id: string | null;
    /**
     * Whether this row is the live version or an immutable snapshot of a
     * previous one.
     */
    version_type: TodoVersionType;
    /** The row this snapshot was copied from. Null on live rows. */
    snapshot_from_todo_id: string | null;
    /**
     * The source row's last-updated time at the moment this snapshot was taken.
     * This identifies the version captured, not when the copy was made.
     */
    snapshot_from_todo_at: string | null;
};

