// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"context"

	"github.com/google/uuid"
	"github.com/simonjanss/rig/examples/fantasyfootball/internal/model"
	"github.com/simonjanss/rig/examples/fantasyfootball/internal/store"
	"github.com/simonjanss/rig/runtime/dbhook"
	"github.com/simonjanss/rig/runtime/tenancy"
)

// PlayerService is the interface your service layer implements.
//
// Embedding DefaultPlayerService satisfies all of it, so a resource with no
// business logic needs nothing but a constructor. Override a method to add a
// rule and delegate to the embedded default for the rest.
type PlayerService interface {
	// List Players.
	List(ctx context.Context, r Request[struct{}, PlayerListQuery, struct{}]) (*PlayerListResponse, error)

	// Create a Player.
	Create(ctx context.Context, r Request[struct{}, struct{}, model.PlayerCreateInput]) (*model.Player, error)

	// Search Players with filters.
	Search(ctx context.Context, r Request[struct{}, PlayerSearchQuery, PlayerSearchBody]) (*PlayerListResponse, error)

	// List retired Players.
	//
	// A deletion stamps the row rather than removing it, so this is what was
	// deleted and can still be brought back. Only rows inside the 30-day restore
	// window appear: past it a row is gone as far as anyone is concerned, so it is
	// not in the trash either.
	ListDeleted(ctx context.Context, r Request[struct{}, PlayerListDeletedQuery, struct{}]) (*PlayerListResponse, error)

	// Delete a Player.
	//
	// The row is retired by stamping a deletion time; it stops appearing in reads
	// but can be restored within the retention window.
	Delete(ctx context.Context, r Request[PlayerDeletePath, struct{}, struct{}]) error

	// Fetch one Player by identifier.
	Get(ctx context.Context, r Request[PlayerGetPath, struct{}, struct{}]) (*model.Player, error)

	// Update a Player.
	//
	// Only the fields present in the body are changed. A field set to null is
	// cleared; a field left out is left alone.
	Update(ctx context.Context, r Request[PlayerUpdatePath, struct{}, model.PlayerUpdateInput]) (*model.Player, error)

	// Bring a retired Player back.
	//
	// The deletion stamp is cleared and the row appears in reads again. It works
	// for 30 days after the deletion; past that the row is no longer eligible and
	// this answers 409.
	//
	// Restoring a row that was never deleted is not an error. It is already in the
	// state the caller asked for, and answering otherwise would make a retry of a
	// request whose response went missing look like a failure.
	//
	// The request carries no fields. What to do when the world has moved on while
	// the row was retired — a unique value taken by something created since —
	// is the application's decision, and it is made in the restore hook: refuse,
	// or change the row so that it fits.
	//
	// Every rule then runs against whatever the hook settled on, not only the ones
	// for fields it touched. The row was not live, so nothing about it has been
	// checked against the world it is returning to.
	Restore(ctx context.Context, r Request[PlayerRestorePath, struct{}, struct{}]) (*model.Player, error)
}

// PlayerWriter writes a Player with the service's rules attached.
//
// Every write rig generates goes through it, and so should every write a
// custom endpoint makes: reaching for the repository directly means passing
// the hooks by hand, and forgetting once is a second way into the table where
// the rules do not run.
type PlayerWriter struct {
	repo  store.PlayerRepository
	hooks PlayerHooks
}

// NewPlayerWriter pairs a repository with the rules that apply to it.
func NewPlayerWriter(repo store.PlayerRepository, hooks PlayerHooks) PlayerWriter {
	return PlayerWriter{repo: repo, hooks: hooks}
}

// Create inserts a row, running the create rules and hooks.
func (w PlayerWriter) Create(ctx context.Context, in model.PlayerCreateInput) (*model.Player, error) {
	return w.repo.Create(ctx, dbhook.Create[model.PlayerCreateInput, model.Player]{Input: in, Hooks: w.hooks.Create})
}

// Update changes a row, running the update rules and hooks.
func (w PlayerWriter) Update(ctx context.Context, id uuid.UUID, in model.PlayerUpdateInput) (*model.Player, error) {
	return w.repo.Update(ctx, id, dbhook.Update[model.PlayerUpdateInput, model.Player]{Input: in, Hooks: w.hooks.Update})
}

// Delete removes a row, running the delete hooks.
func (w PlayerWriter) Delete(ctx context.Context, in model.PlayerDeleteInput) error {
	return w.repo.Delete(ctx, dbhook.Delete[model.PlayerDeleteInput, model.Player]{Input: in, Hooks: w.hooks.Delete})
}

// Restore brings a retired row back, running the restore hooks. The input
// starts empty: what a row has to change to be allowed back is the hook's
// decision, not the caller's.
func (w PlayerWriter) Restore(ctx context.Context, id uuid.UUID) (*model.Player, error) {
	return w.repo.Restore(ctx, id, dbhook.Restore[model.PlayerUpdateInput, model.Player]{Hooks: w.hooks.Restore})
}

// DefaultPlayerService implements every operation.
//
// The generated ones it answers itself, by calling the repository. A custom
// endpoint it hands to the contract, which is where the only implementation
// there could be lives.
type DefaultPlayerService struct {
	repo     store.PlayerRepository
	contract PlayerContract
	// write is the same writer a custom endpoint gets through Writer, so the
	// generated operations and the hand-written ones take one path.
	write PlayerWriter
}

// PlayerContract is what the service layer owes Player: everything about it
// the schema cannot describe.
//
// The members are optional in the sense that an empty one runs nothing. None
// of them is optional in the sense of being skippable: the constructor takes
// this value, so a resource with no rules has an empty literal somebody can
// read rather than an absence nobody can see.
type PlayerContract struct {
	// Hooks is everything that happens around a write: the rules it is checked
	// against, and the callbacks that run with it. One set per operation, because
	// the rules for creating a row and for changing one are different questions
	// asked about different fields.
	Hooks PlayerHooks
}

// PlayerHooks are the callbacks that run around each generated write.
//
// Before and After run inside the write's transaction, so returning an error
// from either undoes the write. AfterCommit runs once it has landed, which is
// where anything outside the database belongs.
type PlayerHooks struct {
	// Read shapes what a read answers with. It is the one set that is not about a
	// write, and the only one that runs outside the repository — a write reads
	// the row it is about to change, and narrowing that read would have the update
	// judge a row that is not the stored one.
	Read dbhook.ReadHooks[model.PlayerFilter, model.Player]

	Create dbhook.CreateHooks[model.PlayerCreateInput, model.Player]
	Update dbhook.UpdateHooks[model.PlayerUpdateInput, model.Player]
	Delete dbhook.DeleteHooks[model.PlayerDeleteInput, model.Player]
	// Restore takes the update input, because a restore may have to change the row
	// to be allowed back at all.
	Restore dbhook.RestoreHooks[model.PlayerUpdateInput, model.Player]
}

// PlayerRules is everything the service layer supplies about Player.
//
// Implement it on a type of your own and hand it to NewPlayerService. It is an
// interface rather than a struct so that the rules and the endpoints are one
// value: a resource whose configuration declares an endpoint cannot be wired
// up without an implementation of it, and the failure is at the call to the
// constructor rather than on the route.
type PlayerRules interface {
	// Hooks is everything that happens around a write, plus what a read answers
	// with. It is called once, during construction.
	Hooks() PlayerHooks

	// Bind receives the writer built from those hooks, so a custom endpoint can
	// write through the same path a generated operation does.
	//
	// It is in the interface rather than looked for, so a service that never
	// writes says so with an empty body instead of finding out at runtime that a
	// misspelled method left it without one. rig calls it once, before anything
	// can reach a hook.
	Bind(PlayerWriter)
}

// NewPlayerService is the front door.
//
// It asks the rules what they are, builds the writer from that, and hands the
// writer back. The service layer never has to hold a half-built value or name
// the type it is part of.
func NewPlayerService(repo store.PlayerRepository, rules PlayerRules) DefaultPlayerService {
	svc := NewDefaultPlayerService(repo, PlayerContract{Hooks: rules.Hooks()})
	rules.Bind(svc.Writer())
	return svc
}

// NewDefaultPlayerService builds the default implementation.
//
// The contract is a parameter rather than a field left to default, because a
// rule nobody attached is a rule that does not run, and nothing at the call
// site would have said so. An empty PlayerContract is still allowed — it is
// just a thing somebody wrote down.
func NewDefaultPlayerService(repo store.PlayerRepository, contract PlayerContract) DefaultPlayerService {
	return DefaultPlayerService{repo: repo, contract: contract, write: NewPlayerWriter(repo, contract.Hooks)}
}

// Writer is how a custom endpoint writes.
//
// It is the repository with this service's own rules already attached, so a
// hand-written endpoint takes the path a generated one takes. Reaching for the
// repository instead means passing the hooks by hand, and forgetting once is a
// second way into the table where the rules do not run.
//
// It is a method rather than something the service layer holds because there
// is then nothing to wire, and nothing to wire wrongly.
func (s DefaultPlayerService) Writer() PlayerWriter { return s.write }

// readFilter combines the caller's filter with whatever the read hook narrows
// to.
//
// Nested rather than merged, because the two are combined with AND: a caller
// whose own filter is an OR cannot widen its way out of the one the service
// added.
func (s DefaultPlayerService) readFilter(ctx context.Context, claims tenancy.Claims, asked model.PlayerFilter) (model.PlayerFilter, error) {
	if s.contract.Hooks.Read.Narrow == nil {
		return asked, nil
	}

	narrowed, err := s.contract.Hooks.Read.Narrow(ctx, caller(claims))
	if err != nil {
		return asked, err
	}
	if narrowed == nil {
		return asked, nil
	}

	return model.PlayerFilter{NestedFilters: []model.PlayerFilter{*narrowed, asked}}, nil
}

// readRows runs the read hook over what a read is about to answer with.
func (s DefaultPlayerService) readRows(ctx context.Context, claims tenancy.Claims, rows []*model.Player) error {
	if s.contract.Hooks.Read.Rows == nil {
		return nil
	}
	return s.contract.Hooks.Read.Rows(ctx, caller(claims), rows)
}

// List implements PlayerService.
func (s DefaultPlayerService) List(ctx context.Context, r Request[struct{}, PlayerListQuery, struct{}]) (*PlayerListResponse, error) {
	page := model.PlayerPage{Limit: r.Query.Limit, Offset: r.Query.Offset}
	asked := model.NewPlayerFilter()
	filter, err := s.readFilter(ctx, r.Claims, asked)
	if err != nil {
		return nil, err
	}

	rows, total, err := s.repo.List(ctx, filter, page)
	if err != nil {
		return nil, err
	}
	if err := s.readRows(ctx, r.Claims, rows); err != nil {
		return nil, err
	}

	return &PlayerListResponse{
		Data:       rows,
		Pagination: Pagination{Offset: page.Offset, Limit: page.Limit, Total: total},
	}, nil
}

// Create implements PlayerService.
func (s DefaultPlayerService) Create(ctx context.Context, r Request[struct{}, struct{}, model.PlayerCreateInput]) (*model.Player, error) {
	return s.write.Create(ctx, r.Body)
}

// Search implements PlayerService.
func (s DefaultPlayerService) Search(ctx context.Context, r Request[struct{}, PlayerSearchQuery, PlayerSearchBody]) (*PlayerListResponse, error) {
	page := model.PlayerPage{Limit: r.Query.Limit, Offset: r.Query.Offset}
	asked := r.Body.Filter
	filter, err := s.readFilter(ctx, r.Claims, asked)
	if err != nil {
		return nil, err
	}

	rows, total, err := s.repo.List(ctx, filter, page)
	if err != nil {
		return nil, err
	}
	if err := s.readRows(ctx, r.Claims, rows); err != nil {
		return nil, err
	}

	return &PlayerListResponse{
		Data:       rows,
		Pagination: Pagination{Offset: page.Offset, Limit: page.Limit, Total: total},
	}, nil
}

// ListDeleted implements PlayerService.
func (s DefaultPlayerService) ListDeleted(ctx context.Context, r Request[struct{}, PlayerListDeletedQuery, struct{}]) (*PlayerListResponse, error) {
	page := model.PlayerPage{Limit: r.Query.Limit, Offset: r.Query.Offset}
	filter, err := s.readFilter(ctx, r.Claims, model.NewPlayerFilter())
	if err != nil {
		return nil, err
	}

	rows, total, err := s.repo.ListDeleted(ctx, filter, page)
	if err != nil {
		return nil, err
	}
	if err := s.readRows(ctx, r.Claims, rows); err != nil {
		return nil, err
	}

	return &PlayerListResponse{
		Data:       rows,
		Pagination: Pagination{Offset: page.Offset, Limit: page.Limit, Total: total},
	}, nil
}

// Delete implements PlayerService.
func (s DefaultPlayerService) Delete(ctx context.Context, r Request[PlayerDeletePath, struct{}, struct{}]) error {
	return s.write.Delete(ctx, model.PlayerDeleteInput{ID: r.Path.ID})
}

// Get implements PlayerService.
func (s DefaultPlayerService) Get(ctx context.Context, r Request[PlayerGetPath, struct{}, struct{}]) (*model.Player, error) {
	row, err := s.repo.Get(ctx, r.Path.ID)
	if err != nil {
		return nil, err
	}

	// Not narrowed: Get fetches by primary key, and there is no filter to add a
	// condition to. A rule about whether this caller may have this row belongs in
	// Rows, which is handed it.
	if err := s.readRows(ctx, r.Claims, []*model.Player{row}); err != nil {
		return nil, err
	}
	return row, nil
}

// Update implements PlayerService.
func (s DefaultPlayerService) Update(ctx context.Context, r Request[PlayerUpdatePath, struct{}, model.PlayerUpdateInput]) (*model.Player, error) {
	return s.write.Update(ctx, r.Path.ID, r.Body)
}

// Restore implements PlayerService.
func (s DefaultPlayerService) Restore(ctx context.Context, r Request[PlayerRestorePath, struct{}, struct{}]) (*model.Player, error) {
	return s.write.Restore(ctx, r.Path.ID)
}
