// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"github.com/simonjanss/rig/observe"
)

// Tracing is this API's tracing configuration, as far as generated code can
// know it.
//
//	provider, err := observe.Setup(ctx, api.Tracing())
//	if err != nil { return nil, err }
//	app.CloseWithin("traces", 5*time.Second, provider.Shutdown)
//
// The name comes from rig.yaml, so nothing is typed twice. What is not here is
// where the spans go: a collector, or a file, is a property of the deployment
// rather than of this build, and the same binary runs where there is one and
// where there is not. Set [github.com/simonjanss/rig/observe.Config.Endpoint]
// on what this returns, or leave it to $OTEL_EXPORTER_OTLP_ENDPOINT.
//
// ServiceVersion is left empty on purpose. The build is the application's own
// fact — a tag, a commit, whatever the pipeline stamps in — and a
// generator that filled it with the API version would be answering a question
// nobody asked it.
func Tracing() observe.Config {
	return observe.Config{ServiceName: "fantasyfootball"}
}
