// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

import (
	"github.com/google/uuid"
	"github.com/simonjanss/rig/rigclient"
	"github.com/simonjanss/rig/runtime/patch"
	"github.com/simonjanss/rig/runtime/rigerr"
)

// TodoAttachmentListQuery is the query for TodoAttachment.List.
//
// A nil member is left out of the request, and the server applies its own
// default. rigclient.P takes the address of a value, for filling one in.
type TodoAttachmentListQuery struct {
	// Maximum rows to return. Left out, the server uses 50.
	Limit *int `json:"limit"`
	// Rows to skip before the first returned row. Left out, the server uses 0.
	Offset *int `json:"offset"`
}

// TodoAttachmentCreateInput is what creating a TodoAttachment takes.
//
// A field the server fills in — the identifier, the tenant, the audit
// columns — is not here: those are not a caller's to send.
type TodoAttachmentCreateInput struct {
	// The todo this is attached to.
	TodoID uuid.UUID `json:"todoId"`
	// The file itself. Required: an attachment with no file is nothing.
	AttachmentFileID uuid.UUID `json:"attachmentFileId"`
	// What the attachment is, in a few words.
	Caption *string `json:"caption,omitempty"`
	// Where this sits in the todo's list of attachments.
	Position int `json:"position"`
}

// TodoAttachmentCreateFields is what a validation failure says, shaped like
// the body it is about — one member per member, so each message can be put
// beside the control it belongs to.
//
// A member is nil when there was nothing wrong with that field. It arrives as
// the Fields of the error the call returns.
type TodoAttachmentCreateFields struct {
	TodoID           *rigerr.FieldError `json:"todoId,omitempty"`
	AttachmentFileID *rigerr.FieldError `json:"attachmentFileId,omitempty"`
	Caption          *rigerr.FieldError `json:"caption,omitempty"`
	Position         *rigerr.FieldError `json:"position,omitempty"`
	// Entity carries what was wrong with the request as a whole rather than with
	// any one field.
	Entity *rigerr.FieldError `json:"entity,omitempty"`
}

// TodoAttachmentCreateError is what a refused TodoAttachments.Create comes
// back as: the envelope the server sent — Code, Message, RequestID, Status
// — with the per-field detail decoded into a [TodoAttachmentCreateFields]
// rather than left as bytes.
//
// It is the error the method returns, so there is nothing to name and nothing
// to name wrongly:
//
//	var refused *TodoAttachmentCreateError
//	if errors.As(err, &refused) && refused.Fields.TodoID != nil {
//
// errors.As reaches the rigclient.Error underneath it too, so
// rigclient.IsInvalid and the rest answer about it unchanged.
type TodoAttachmentCreateError = rigclient.Failure[TodoAttachmentCreateFields]

// TodoAttachmentSearchBody is the request body for TodoAttachment.Search.
type TodoAttachmentSearchBody struct {
	// Conditions rows must satisfy.
	Filter TodoAttachmentFilter `json:"filter"`
}

// TodoAttachmentSearchFields is what a validation failure says, shaped like
// the body it is about — one member per member, so each message can be put
// beside the control it belongs to.
//
// A member is nil when there was nothing wrong with that field. It arrives as
// the Fields of the error the call returns.
type TodoAttachmentSearchFields struct {
	Filter *rigerr.FieldError `json:"filter,omitempty"`
	// Entity carries what was wrong with the request as a whole rather than with
	// any one field.
	Entity *rigerr.FieldError `json:"entity,omitempty"`
}

// TodoAttachmentSearchError is what a refused TodoAttachments.Search comes
// back as: the envelope the server sent — Code, Message, RequestID, Status
// — with the per-field detail decoded into a [TodoAttachmentSearchFields]
// rather than left as bytes.
//
// It is the error the method returns, so there is nothing to name and nothing
// to name wrongly:
//
//	var refused *TodoAttachmentSearchError
//	if errors.As(err, &refused) && refused.Fields.Filter != nil {
//
// errors.As reaches the rigclient.Error underneath it too, so
// rigclient.IsInvalid and the rest answer about it unchanged.
type TodoAttachmentSearchError = rigclient.Failure[TodoAttachmentSearchFields]

// TodoAttachmentSearchQuery is the query for TodoAttachment.Search.
//
// A nil member is left out of the request, and the server applies its own
// default. rigclient.P takes the address of a value, for filling one in.
type TodoAttachmentSearchQuery struct {
	// Maximum rows to return. Left out, the server uses 50.
	Limit *int `json:"limit"`
	// Rows to skip before the first returned row. Left out, the server uses 0.
	Offset *int `json:"offset"`
}

// TodoAttachmentListDeletedQuery is the query for TodoAttachment.ListDeleted.
//
// A nil member is left out of the request, and the server applies its own
// default. rigclient.P takes the address of a value, for filling one in.
type TodoAttachmentListDeletedQuery struct {
	// Maximum rows to return. Left out, the server uses 50.
	Limit *int `json:"limit"`
	// Rows to skip before the first returned row. Left out, the server uses 0.
	Offset *int `json:"offset"`
}

// TodoAttachmentUpdateInput is what changing a TodoAttachment takes.
//
// A field left out is left alone. A nullable field set to patch.Null is
// cleared — which is why there are two wrappers: a column that cannot hold
// null has no way to be given one, so clearing it is a compile error rather
// than a refusal at runtime. Immutable fields are not here at all.
type TodoAttachmentUpdateInput struct {
	// The todo this is attached to.
	TodoID patch.Optional[uuid.UUID] `json:"todoId,omitzero"`
	// The file itself. Required: an attachment with no file is nothing.
	AttachmentFileID patch.Optional[uuid.UUID] `json:"attachmentFileId,omitzero"`
	// What the attachment is, in a few words.
	Caption patch.Nullable[string] `json:"caption,omitzero"`
	// Where this sits in the todo's list of attachments.
	Position patch.Optional[int] `json:"position,omitzero"`
}

// TodoAttachmentUpdateFields is what a validation failure says, shaped like
// the body it is about — one member per member, so each message can be put
// beside the control it belongs to.
//
// A member is nil when there was nothing wrong with that field. It arrives as
// the Fields of the error the call returns.
type TodoAttachmentUpdateFields struct {
	TodoID           *rigerr.FieldError `json:"todoId,omitempty"`
	AttachmentFileID *rigerr.FieldError `json:"attachmentFileId,omitempty"`
	Caption          *rigerr.FieldError `json:"caption,omitempty"`
	Position         *rigerr.FieldError `json:"position,omitempty"`
	// Entity carries what was wrong with the request as a whole rather than with
	// any one field.
	Entity *rigerr.FieldError `json:"entity,omitempty"`
}

// TodoAttachmentUpdateError is what a refused TodoAttachments.Update comes
// back as: the envelope the server sent — Code, Message, RequestID, Status
// — with the per-field detail decoded into a [TodoAttachmentUpdateFields]
// rather than left as bytes.
//
// It is the error the method returns, so there is nothing to name and nothing
// to name wrongly:
//
//	var refused *TodoAttachmentUpdateError
//	if errors.As(err, &refused) && refused.Fields.TodoID != nil {
//
// errors.As reaches the rigclient.Error underneath it too, so
// rigclient.IsInvalid and the rest answer about it unchanged.
type TodoAttachmentUpdateError = rigclient.Failure[TodoAttachmentUpdateFields]
