// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

// How urgently a task wants attention.
type TodoPriority string

// The values of TodoPriority.
const (
	// Worth doing eventually.
	TodoPriorityLow TodoPriority = "low"
	// Worth doing soon. This is the default.
	TodoPriorityNormal TodoPriority = "normal"
	// Worth doing before anything else.
	TodoPriorityHigh TodoPriority = "high"
)

// AllTodoPriority is every value, in declaration order. It is what a picker is
// drawn from.
var AllTodoPriority = []TodoPriority{TodoPriorityLow, TodoPriorityNormal, TodoPriorityHigh}

// String implements fmt.Stringer.
func (v TodoPriority) String() string { return string(v) }
