// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

import (
	"github.com/google/uuid"
	"github.com/simonjanss/rig/runtime/patch"
	"github.com/simonjanss/rig/runtime/rigerr"
)

// TodoAttachmentListQuery is the query for TodoAttachment.List.
//
// A nil member is left out of the request, and the server applies its own
// default. rigclient.P takes the address of a value, for filling one in.
type TodoAttachmentListQuery struct {
	// Maximum rows to return. Left out, the server uses 50.
	Limit *int `json:"limit"`
	// Rows to skip before the first returned row. Left out, the server uses 0.
	Offset *int `json:"offset"`
}

// TodoAttachmentCreateInput is what creating a TodoAttachment takes.
//
// A field the server fills in — the identifier, the tenant, the audit
// columns — is not here: those are not a caller's to send.
type TodoAttachmentCreateInput struct {
	// The todo this is attached to.
	TodoID uuid.UUID `json:"todoId"`
	// The file itself. Required: an attachment with no file is nothing.
	AttachmentFileID uuid.UUID `json:"attachmentFileId"`
	// What the attachment is, in a few words.
	Caption *string `json:"caption,omitempty"`
	// Where this sits in the todo's list of attachments.
	Position int `json:"position"`
}

// TodoAttachmentCreateFields is what a validation failure on a
// TodoAttachmentCreateInput says, shaped like the input it is about — one
// member per member, so each message can be put beside the control it belongs
// to.
//
// It is read out of a failed call with
// rigclient.FieldsAs[TodoAttachmentCreateFields], and a member is nil when
// there was nothing wrong with that field.
type TodoAttachmentCreateFields struct {
	TodoID           *rigerr.FieldError `json:"todoId,omitempty"`
	AttachmentFileID *rigerr.FieldError `json:"attachmentFileId,omitempty"`
	Caption          *rigerr.FieldError `json:"caption,omitempty"`
	Position         *rigerr.FieldError `json:"position,omitempty"`
	// Entity carries what was wrong with the request as a whole rather than with
	// any one field.
	Entity *rigerr.FieldError `json:"entity,omitempty"`
}

// TodoAttachmentSearchBody is the request body for TodoAttachment.Search.
type TodoAttachmentSearchBody struct {
	// Conditions rows must satisfy.
	Filter TodoAttachmentFilter `json:"filter"`
}

// TodoAttachmentSearchQuery is the query for TodoAttachment.Search.
//
// A nil member is left out of the request, and the server applies its own
// default. rigclient.P takes the address of a value, for filling one in.
type TodoAttachmentSearchQuery struct {
	// Maximum rows to return. Left out, the server uses 50.
	Limit *int `json:"limit"`
	// Rows to skip before the first returned row. Left out, the server uses 0.
	Offset *int `json:"offset"`
}

// TodoAttachmentListDeletedQuery is the query for TodoAttachment.ListDeleted.
//
// A nil member is left out of the request, and the server applies its own
// default. rigclient.P takes the address of a value, for filling one in.
type TodoAttachmentListDeletedQuery struct {
	// Maximum rows to return. Left out, the server uses 50.
	Limit *int `json:"limit"`
	// Rows to skip before the first returned row. Left out, the server uses 0.
	Offset *int `json:"offset"`
}

// TodoAttachmentUpdateInput is what changing a TodoAttachment takes.
//
// A field left out is left alone. A nullable field set to patch.Null is
// cleared — which is why there are two wrappers: a column that cannot hold
// null has no way to be given one, so clearing it is a compile error rather
// than a refusal at runtime. Immutable fields are not here at all.
type TodoAttachmentUpdateInput struct {
	// The todo this is attached to.
	TodoID patch.Optional[uuid.UUID] `json:"todoId,omitzero"`
	// The file itself. Required: an attachment with no file is nothing.
	AttachmentFileID patch.Optional[uuid.UUID] `json:"attachmentFileId,omitzero"`
	// What the attachment is, in a few words.
	Caption patch.Nullable[string] `json:"caption,omitzero"`
	// Where this sits in the todo's list of attachments.
	Position patch.Optional[int] `json:"position,omitzero"`
}

// TodoAttachmentUpdateFields is what a validation failure on a
// TodoAttachmentUpdateInput says, shaped like the input it is about — one
// member per member, so each message can be put beside the control it belongs
// to.
//
// It is read out of a failed call with
// rigclient.FieldsAs[TodoAttachmentUpdateFields], and a member is nil when
// there was nothing wrong with that field.
type TodoAttachmentUpdateFields struct {
	TodoID           *rigerr.FieldError `json:"todoId,omitempty"`
	AttachmentFileID *rigerr.FieldError `json:"attachmentFileId,omitempty"`
	Caption          *rigerr.FieldError `json:"caption,omitempty"`
	Position         *rigerr.FieldError `json:"position,omitempty"`
	// Entity carries what was wrong with the request as a whole rather than with
	// any one field.
	Entity *rigerr.FieldError `json:"entity,omitempty"`
}
