// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// One copy of an inbox line on its way to a channel. Claimed by lease, sent
// outside any transaction, and marked afterwards.
//
// It is the one definition of a NotificationDelivery: the repository scans
// into it and the API returns it, so there is no conversion between two shapes
// of the same thing and no field that can go missing from one of them.
type NotificationDelivery struct {
	// Unique identifier for this row.
	ID uuid.UUID `json:"id"`
	// Tenant this row belongs to. Every query is scoped by it.
	TenantID uuid.UUID `json:"tenantId"`
	// The inbox line this is a copy of. The line is the truth and this is one way
	// it was repeated.
	RecipientID uuid.UUID `json:"recipientId"`
	// Who it is for, denormalized off the line so a claim can group by it without
	// a join.
	AccountID uuid.UUID `json:"accountId"`
	// When this row was created. Set automatically and never changes.
	CreatedAt time.Time `json:"createdAt"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Where it is going. One row per line per channel, which is what the unique
	// index below enforces.
	Channel NotificationChannel `json:"channel"`
	// Copied from the notification, so the settings resolution needs no join
	// either.
	Kind string `json:"kind"`
	// What the setting said when this row was written. Immediate rows are sent on
	// their own; the rest are batched per account and channel.
	Digest NotificationDigest `json:"digest"`
	// Skipped means a setting refused it, which is different from Failed and worth
	// telling apart in a report.
	State NotificationDeliveryState `json:"state"`
	// When this is due. A delivery held outside somebody hours moves to the next
	// opening; a digested one moves to its window close.
	DeliverAt time.Time `json:"deliverAt"`
	// When a channel accepted it, which is not the same as it arriving.
	SentAt *time.Time `json:"sentAt,omitempty"`
	// What the channel said last time. Kept on a retry as well as on a failure, so
	// a pattern is visible before the cap is reached.
	FailedReason *string `json:"failedReason,omitempty"`
	// How many times this has been claimed. Past notifications.max_attempts it is
	// Failed and stops being claimed.
	Attempts int `json:"attempts"`
	// When a dispatcher took it. Past notifications.claim_ttl another one may,
	// which is what makes a crashed process recoverable.
	ClaimedAt *time.Time `json:"claimedAt,omitempty"`
	// Which process holds the lease. A uuid generated once per process, with the
	// hostname beside it in the log line, so a stuck lease traces to a pod rather
	// than to a mystery.
	ClaimedBy *uuid.UUID `json:"claimedBy,omitempty"`
}

// TableNotificationDelivery is the table this entity is stored in.
const TableNotificationDelivery = "rig_notification_delivery"

// Column names for rig_notification_delivery, so nothing has to spell one out.
const (
	ColumnNotificationDeliveryID           = "id"
	ColumnNotificationDeliveryTenantID     = "tenant_id"
	ColumnNotificationDeliveryRecipientID  = "recipient_id"
	ColumnNotificationDeliveryAccountID    = "account_id"
	ColumnNotificationDeliveryCreatedAt    = "created_at"
	ColumnNotificationDeliveryUpdatedAt    = "updated_at"
	ColumnNotificationDeliveryChannel      = "channel"
	ColumnNotificationDeliveryKind         = "kind"
	ColumnNotificationDeliveryDigest       = "digest"
	ColumnNotificationDeliveryState        = "state"
	ColumnNotificationDeliveryDeliverAt    = "deliver_at"
	ColumnNotificationDeliverySentAt       = "sent_at"
	ColumnNotificationDeliveryFailedReason = "failed_reason"
	ColumnNotificationDeliveryAttempts     = "attempts"
	ColumnNotificationDeliveryClaimedAt    = "claimed_at"
	ColumnNotificationDeliveryClaimedBy    = "claimed_by"
)

// NotificationDeliveryColumns is every column, in the order the row is
// scanned.
var NotificationDeliveryColumns = []string{"id", "tenant_id", "recipient_id", "account_id", "created_at", "updated_at", "channel", "kind", "digest", "state", "deliver_at", "sent_at", "failed_reason", "attempts", "claimed_at", "claimed_by"}
