// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// Exact-match conditions on Todo fields.
type TodoFilterEquals struct {
	// Unique identifier for this row.
	ID *uuid.UUID `json:"id,omitempty"`
	// What needs doing, in a few words.
	Title *string `json:"title,omitempty"`
	// Anything worth remembering that does not fit in the title.
	Notes *string `json:"notes,omitempty"`
	// Whether the task has been completed.
	IsDone *bool `json:"isDone,omitempty"`
	// How urgently the task wants attention.
	Priority *TodoPriority `json:"priority,omitempty"`
	// When the task is due, or null if it never expires.
	DueAt *time.Time `json:"dueAt,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *uuid.UUID `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *uuid.UUID `json:"deletedByAccountId,omitempty"`
	// Whether this row is the live version or an immutable snapshot of a previous
	// one.
	VersionType *TodoVersionType `json:"versionType,omitempty"`
	// The row this snapshot was copied from. Null on live rows.
	SnapshotFromTodoID *uuid.UUID `json:"snapshotFromTodoId,omitempty"`
	// The source row's last-updated time at the moment this snapshot was taken.
	// This identifies the version captured, not when the copy was made.
	SnapshotFromTodoAt *time.Time `json:"snapshotFromTodoAt,omitempty"`
	// A picture for the todo, if it has one.
	CoverFileID *uuid.UUID `json:"coverFileId,omitempty"`
	// Conditions on one of this row's TodoAttachments.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.TodoAttachments asks the second.
	TodoAttachments *TodoAttachmentFilterEquals `json:"todoAttachments,omitempty"`
}

// Ordering conditions on Todo fields that can be compared.
type TodoFilterRange struct {
	// When the task is due, or null if it never expires.
	DueAt *time.Time `json:"dueAt,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// The source row's last-updated time at the moment this snapshot was taken.
	// This identifies the version captured, not when the copy was made.
	SnapshotFromTodoAt *time.Time `json:"snapshotFromTodoAt,omitempty"`
	// Conditions on one of this row's TodoAttachments.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.TodoAttachments asks the second.
	TodoAttachments *TodoAttachmentFilterRange `json:"todoAttachments,omitempty"`
}

// Set-membership conditions on Todo fields.
type TodoFilterContains struct {
	// Unique identifier for this row.
	ID []uuid.UUID `json:"id,omitempty"`
	// What needs doing, in a few words.
	Title []string `json:"title,omitempty"`
	// Anything worth remembering that does not fit in the title.
	Notes []string `json:"notes,omitempty"`
	// Whether the task has been completed.
	IsDone []bool `json:"isDone,omitempty"`
	// How urgently the task wants attention.
	Priority []TodoPriority `json:"priority,omitempty"`
	// When the task is due, or null if it never expires.
	DueAt []time.Time `json:"dueAt,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt []time.Time `json:"createdAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID []uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt []time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID []uuid.UUID `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt []time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID []uuid.UUID `json:"deletedByAccountId,omitempty"`
	// Whether this row is the live version or an immutable snapshot of a previous
	// one.
	VersionType []TodoVersionType `json:"versionType,omitempty"`
	// The row this snapshot was copied from. Null on live rows.
	SnapshotFromTodoID []uuid.UUID `json:"snapshotFromTodoId,omitempty"`
	// The source row's last-updated time at the moment this snapshot was taken.
	// This identifies the version captured, not when the copy was made.
	SnapshotFromTodoAt []time.Time `json:"snapshotFromTodoAt,omitempty"`
	// A picture for the todo, if it has one.
	CoverFileID []uuid.UUID `json:"coverFileId,omitempty"`
	// Conditions on one of this row's TodoAttachments.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.TodoAttachments asks the second.
	TodoAttachments *TodoAttachmentFilterContains `json:"todoAttachments,omitempty"`
}

// Pattern conditions on Todo text fields.
type TodoFilterLike struct {
	// What needs doing, in a few words.
	Title *string `json:"title,omitempty"`
	// Anything worth remembering that does not fit in the title.
	Notes *string `json:"notes,omitempty"`
	// Conditions on one of this row's TodoAttachments.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.TodoAttachments asks the second.
	TodoAttachments *TodoAttachmentFilterLike `json:"todoAttachments,omitempty"`
}

// Presence conditions on nullable Todo fields.
type TodoFilterNull struct {
	// Anything worth remembering that does not fit in the title.
	Notes *bool `json:"notes,omitempty"`
	// When the task is due, or null if it never expires.
	DueAt *bool `json:"dueAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *bool `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *bool `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *bool `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *bool `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *bool `json:"deletedByAccountId,omitempty"`
	// The row this snapshot was copied from. Null on live rows.
	SnapshotFromTodoID *bool `json:"snapshotFromTodoId,omitempty"`
	// The source row's last-updated time at the moment this snapshot was taken.
	// This identifies the version captured, not when the copy was made.
	SnapshotFromTodoAt *bool `json:"snapshotFromTodoAt,omitempty"`
	// A picture for the todo, if it has one.
	CoverFileID *bool `json:"coverFileId,omitempty"`
	// Conditions on one of this row's TodoAttachments.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.TodoAttachments asks the second.
	TodoAttachments *TodoAttachmentFilterNull `json:"todoAttachments,omitempty"`
}

// Relations a Todo must have no matching row for.
type TodoFilterWithout struct {
	// Match rows with no TodoAttachments satisfying these conditions, including
	// rows with none at all.
	//
	// This negates the existence of a matching row rather than the comparison,
	// which is the whole difference from NotEquals.TodoAttachments: that one is
	// satisfied by one of them differing, and a row can have one that differs and
	// one that matches at the same time. An empty object asks for rows with no
	// TodoAttachments at all.
	TodoAttachments *TodoAttachmentFilter `json:"todoAttachments,omitempty"`
}

// Conditions a Todo must satisfy to match a search.
type TodoFilter struct {
	// Fields that must equal the given value.
	Equals *TodoFilterEquals `json:"equals,omitempty"`
	// Fields that must not equal the given value.
	NotEquals *TodoFilterEquals `json:"notEquals,omitempty"`
	// Fields that must be greater than the given value.
	GreaterThan *TodoFilterRange `json:"greaterThan,omitempty"`
	// Fields that must be less than the given value.
	SmallerThan *TodoFilterRange `json:"smallerThan,omitempty"`
	// Fields that must be greater than or equal to the given value.
	GreaterOrEqual *TodoFilterRange `json:"greaterOrEqual,omitempty"`
	// Fields that must be less than or equal to the given value.
	SmallerOrEqual *TodoFilterRange `json:"smallerOrEqual,omitempty"`
	// Fields that must be one of the given values.
	Contains *TodoFilterContains `json:"contains,omitempty"`
	// Fields that must not be one of the given values.
	NotContains *TodoFilterContains `json:"notContains,omitempty"`
	// Text fields that must match the given pattern.
	Like *TodoFilterLike `json:"like,omitempty"`
	// Text fields that must not match the given pattern.
	NotLike *TodoFilterLike `json:"notLike,omitempty"`
	// Fields that must be null.
	Null *TodoFilterNull `json:"null,omitempty"`
	// Fields that must not be null.
	NotNull *TodoFilterNull `json:"notNull,omitempty"`
	// Combine this filter's conditions with OR instead of AND.
	OrCondition bool `json:"orCondition,omitempty"`
	// Sub-filters combined with this one, so that AND and OR can be mixed to any
	// depth.
	NestedFilters []TodoFilter `json:"nestedFilters,omitempty"`
	// Relations with no row matching the given conditions. An empty one asks for
	// no related row at all.
	//
	// This is where a negation belongs when what you mean is "not": it negates
	// whether a matching related row exists, so a row with no related row at all
	// satisfies it. The negative operators above negate the comparison instead and
	// still require the related row to be there — "no related row called X" is
	// here, "a related row not called X" is NotEquals.
	Without *TodoFilterWithout `json:"without,omitempty"`
}

// TodoPage says which slice of a result to return, and in what order.
//
// The zero value is the first page at the repository's default size, in the
// table's configured order, which is what a caller who has not thought about
// it wants.
type TodoPage struct {
	Limit  int
	Offset int

	// OrderBy replaces the table's default ordering.
	OrderBy []TodoOrder
}

// TodoOrder is one clause of an ordering.
//
// Relation names the relation the column belongs to, and is empty for this
// table's own columns. The repository turns it into a left join, so a row
// whose related row is missing still appears — at one end of the order
// rather than not at all.
type TodoOrder struct {
	Relation string
	Column   string
	Desc     bool
}

// The orderings a Todo supports.
var (
	TodoOrderIDAsc                  = TodoOrder{Column: "id"}
	TodoOrderIDDesc                 = TodoOrder{Column: "id", Desc: true}
	TodoOrderTenantIDAsc            = TodoOrder{Column: "tenant_id"}
	TodoOrderTenantIDDesc           = TodoOrder{Column: "tenant_id", Desc: true}
	TodoOrderTitleAsc               = TodoOrder{Column: "title"}
	TodoOrderTitleDesc              = TodoOrder{Column: "title", Desc: true}
	TodoOrderNotesAsc               = TodoOrder{Column: "notes"}
	TodoOrderNotesDesc              = TodoOrder{Column: "notes", Desc: true}
	TodoOrderIsDoneAsc              = TodoOrder{Column: "is_done"}
	TodoOrderIsDoneDesc             = TodoOrder{Column: "is_done", Desc: true}
	TodoOrderPriorityAsc            = TodoOrder{Column: "priority"}
	TodoOrderPriorityDesc           = TodoOrder{Column: "priority", Desc: true}
	TodoOrderDueAtAsc               = TodoOrder{Column: "due_at"}
	TodoOrderDueAtDesc              = TodoOrder{Column: "due_at", Desc: true}
	TodoOrderCreatedAtAsc           = TodoOrder{Column: "created_at"}
	TodoOrderCreatedAtDesc          = TodoOrder{Column: "created_at", Desc: true}
	TodoOrderCreatedByAccountIDAsc  = TodoOrder{Column: "created_by_account_id"}
	TodoOrderCreatedByAccountIDDesc = TodoOrder{Column: "created_by_account_id", Desc: true}
	TodoOrderUpdatedAtAsc           = TodoOrder{Column: "updated_at"}
	TodoOrderUpdatedAtDesc          = TodoOrder{Column: "updated_at", Desc: true}
	TodoOrderUpdatedByAccountIDAsc  = TodoOrder{Column: "updated_by_account_id"}
	TodoOrderUpdatedByAccountIDDesc = TodoOrder{Column: "updated_by_account_id", Desc: true}
	TodoOrderDeletedAtAsc           = TodoOrder{Column: "deleted_at"}
	TodoOrderDeletedAtDesc          = TodoOrder{Column: "deleted_at", Desc: true}
	TodoOrderDeletedByAccountIDAsc  = TodoOrder{Column: "deleted_by_account_id"}
	TodoOrderDeletedByAccountIDDesc = TodoOrder{Column: "deleted_by_account_id", Desc: true}
	TodoOrderVersionTypeAsc         = TodoOrder{Column: "version_type"}
	TodoOrderVersionTypeDesc        = TodoOrder{Column: "version_type", Desc: true}
	TodoOrderSnapshotFromTodoIDAsc  = TodoOrder{Column: "snapshot_from_todo_id"}
	TodoOrderSnapshotFromTodoIDDesc = TodoOrder{Column: "snapshot_from_todo_id", Desc: true}
	TodoOrderSnapshotFromTodoAtAsc  = TodoOrder{Column: "snapshot_from_todo_at"}
	TodoOrderSnapshotFromTodoAtDesc = TodoOrder{Column: "snapshot_from_todo_at", Desc: true}
	TodoOrderCoverFileIDAsc         = TodoOrder{Column: "cover_file_id"}
	TodoOrderCoverFileIDDesc        = TodoOrder{Column: "cover_file_id", Desc: true}
)

// NewTodoFilterEquals builds an empty TodoFilterEquals to fill in.
func NewTodoFilterEquals() *TodoFilterEquals { return &TodoFilterEquals{} }

// NewTodoFilterRange builds an empty TodoFilterRange to fill in.
func NewTodoFilterRange() *TodoFilterRange { return &TodoFilterRange{} }

// NewTodoFilterContains builds an empty TodoFilterContains to fill in.
func NewTodoFilterContains() *TodoFilterContains { return &TodoFilterContains{} }

// NewTodoFilterLike builds an empty TodoFilterLike to fill in.
func NewTodoFilterLike() *TodoFilterLike { return &TodoFilterLike{} }

// NewTodoFilterNull builds an empty TodoFilterNull to fill in.
func NewTodoFilterNull() *TodoFilterNull { return &TodoFilterNull{} }

// NewTodoFilterWithout builds an empty TodoFilterWithout to fill in.
func NewTodoFilterWithout() *TodoFilterWithout { return &TodoFilterWithout{} }

// NewTodoFilter builds an empty filter, which matches every row the caller is
// allowed to see.
func NewTodoFilter() TodoFilter { return TodoFilter{} }
