// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// Exact-match conditions on TodoAttachment fields.
type TodoAttachmentFilterEquals struct {
	// Unique identifier for this row.
	ID *uuid.UUID `json:"id,omitempty"`
	// The todo this is attached to.
	TodoID *uuid.UUID `json:"todoId,omitempty"`
	// The file itself. Required: an attachment with no file is nothing.
	AttachmentFileID *uuid.UUID `json:"attachmentFileId,omitempty"`
	// What the attachment is, in a few words.
	Caption *string `json:"caption,omitempty"`
	// Where this sits in the todo's list of attachments.
	Position *int `json:"position,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *uuid.UUID `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *uuid.UUID `json:"deletedByAccountId,omitempty"`
	// Conditions on this row's Todo.
	//
	// A row with no Todo never matches, and that holds for the negative operators
	// too: under NotEquals this asks whether the Todo is there and differs, so a
	// row without one fails that as well. To ask the other question — no
	// matching Todo, which a row with none satisfies — use Without.Todo.
	Todo *TodoFilterEquals `json:"todo,omitempty"`
}

// Ordering conditions on TodoAttachment fields that can be compared.
type TodoAttachmentFilterRange struct {
	// Where this sits in the todo's list of attachments.
	Position *int `json:"position,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// Conditions on this row's Todo.
	//
	// A row with no Todo never matches, and that holds for the negative operators
	// too: under NotEquals this asks whether the Todo is there and differs, so a
	// row without one fails that as well. To ask the other question — no
	// matching Todo, which a row with none satisfies — use Without.Todo.
	Todo *TodoFilterRange `json:"todo,omitempty"`
}

// Set-membership conditions on TodoAttachment fields.
type TodoAttachmentFilterContains struct {
	// Unique identifier for this row.
	ID []uuid.UUID `json:"id,omitempty"`
	// The todo this is attached to.
	TodoID []uuid.UUID `json:"todoId,omitempty"`
	// The file itself. Required: an attachment with no file is nothing.
	AttachmentFileID []uuid.UUID `json:"attachmentFileId,omitempty"`
	// What the attachment is, in a few words.
	Caption []string `json:"caption,omitempty"`
	// Where this sits in the todo's list of attachments.
	Position []int `json:"position,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt []time.Time `json:"createdAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID []uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt []time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID []uuid.UUID `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt []time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID []uuid.UUID `json:"deletedByAccountId,omitempty"`
	// Conditions on this row's Todo.
	//
	// A row with no Todo never matches, and that holds for the negative operators
	// too: under NotEquals this asks whether the Todo is there and differs, so a
	// row without one fails that as well. To ask the other question — no
	// matching Todo, which a row with none satisfies — use Without.Todo.
	Todo *TodoFilterContains `json:"todo,omitempty"`
}

// Pattern conditions on TodoAttachment text fields.
type TodoAttachmentFilterLike struct {
	// What the attachment is, in a few words.
	Caption *string `json:"caption,omitempty"`
	// Conditions on this row's Todo.
	//
	// A row with no Todo never matches, and that holds for the negative operators
	// too: under NotEquals this asks whether the Todo is there and differs, so a
	// row without one fails that as well. To ask the other question — no
	// matching Todo, which a row with none satisfies — use Without.Todo.
	Todo *TodoFilterLike `json:"todo,omitempty"`
}

// Presence conditions on nullable TodoAttachment fields.
type TodoAttachmentFilterNull struct {
	// What the attachment is, in a few words.
	Caption *bool `json:"caption,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *bool `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *bool `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *bool `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *bool `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *bool `json:"deletedByAccountId,omitempty"`
	// Conditions on this row's Todo.
	//
	// A row with no Todo never matches, and that holds for the negative operators
	// too: under NotEquals this asks whether the Todo is there and differs, so a
	// row without one fails that as well. To ask the other question — no
	// matching Todo, which a row with none satisfies — use Without.Todo.
	Todo *TodoFilterNull `json:"todo,omitempty"`
}

// Relations a TodoAttachment must have no matching row for.
type TodoAttachmentFilterWithout struct {
	// Match rows with no Todo satisfying these conditions, including rows that
	// have none at all.
	//
	// This negates the existence of the related row rather than the comparison,
	// which is the whole difference from NotEquals.Todo: that one needs the Todo
	// to be there and to differ, so a row without one fails it and satisfies this.
	// An empty object asks for rows with no Todo at all.
	Todo *TodoFilter `json:"todo,omitempty"`
}

// Conditions a TodoAttachment must satisfy to match a search.
type TodoAttachmentFilter struct {
	// Fields that must equal the given value.
	Equals *TodoAttachmentFilterEquals `json:"equals,omitempty"`
	// Fields that must not equal the given value.
	NotEquals *TodoAttachmentFilterEquals `json:"notEquals,omitempty"`
	// Fields that must be greater than the given value.
	GreaterThan *TodoAttachmentFilterRange `json:"greaterThan,omitempty"`
	// Fields that must be less than the given value.
	SmallerThan *TodoAttachmentFilterRange `json:"smallerThan,omitempty"`
	// Fields that must be greater than or equal to the given value.
	GreaterOrEqual *TodoAttachmentFilterRange `json:"greaterOrEqual,omitempty"`
	// Fields that must be less than or equal to the given value.
	SmallerOrEqual *TodoAttachmentFilterRange `json:"smallerOrEqual,omitempty"`
	// Fields that must be one of the given values.
	Contains *TodoAttachmentFilterContains `json:"contains,omitempty"`
	// Fields that must not be one of the given values.
	NotContains *TodoAttachmentFilterContains `json:"notContains,omitempty"`
	// Text fields that must match the given pattern.
	Like *TodoAttachmentFilterLike `json:"like,omitempty"`
	// Text fields that must not match the given pattern.
	NotLike *TodoAttachmentFilterLike `json:"notLike,omitempty"`
	// Fields that must be null.
	Null *TodoAttachmentFilterNull `json:"null,omitempty"`
	// Fields that must not be null.
	NotNull *TodoAttachmentFilterNull `json:"notNull,omitempty"`
	// Combine this filter's conditions with OR instead of AND.
	OrCondition bool `json:"orCondition,omitempty"`
	// Sub-filters combined with this one, so that AND and OR can be mixed to any
	// depth.
	NestedFilters []TodoAttachmentFilter `json:"nestedFilters,omitempty"`
	// Relations with no row matching the given conditions. An empty one asks for
	// no related row at all.
	//
	// This is where a negation belongs when what you mean is "not": it negates
	// whether a matching related row exists, so a row with no related row at all
	// satisfies it. The negative operators above negate the comparison instead and
	// still require the related row to be there — "no related row called X" is
	// here, "a related row not called X" is NotEquals.
	Without *TodoAttachmentFilterWithout `json:"without,omitempty"`
}

// TodoAttachmentPage says which slice of a result to return, and in what
// order.
//
// The zero value is the first page at the repository's default size, in the
// table's configured order, which is what a caller who has not thought about
// it wants.
type TodoAttachmentPage struct {
	Limit  int
	Offset int

	// OrderBy replaces the table's default ordering.
	OrderBy []TodoAttachmentOrder
}

// TodoAttachmentOrder is one clause of an ordering.
//
// Relation names the relation the column belongs to, and is empty for this
// table's own columns. The repository turns it into a left join, so a row
// whose related row is missing still appears — at one end of the order
// rather than not at all.
type TodoAttachmentOrder struct {
	Relation string
	Column   string
	Desc     bool
}

// The orderings a TodoAttachment supports.
var (
	TodoAttachmentOrderIDAsc                  = TodoAttachmentOrder{Column: "id"}
	TodoAttachmentOrderIDDesc                 = TodoAttachmentOrder{Column: "id", Desc: true}
	TodoAttachmentOrderTenantIDAsc            = TodoAttachmentOrder{Column: "tenant_id"}
	TodoAttachmentOrderTenantIDDesc           = TodoAttachmentOrder{Column: "tenant_id", Desc: true}
	TodoAttachmentOrderTodoIDAsc              = TodoAttachmentOrder{Column: "todo_id"}
	TodoAttachmentOrderTodoIDDesc             = TodoAttachmentOrder{Column: "todo_id", Desc: true}
	TodoAttachmentOrderAttachmentFileIDAsc    = TodoAttachmentOrder{Column: "attachment_file_id"}
	TodoAttachmentOrderAttachmentFileIDDesc   = TodoAttachmentOrder{Column: "attachment_file_id", Desc: true}
	TodoAttachmentOrderCaptionAsc             = TodoAttachmentOrder{Column: "caption"}
	TodoAttachmentOrderCaptionDesc            = TodoAttachmentOrder{Column: "caption", Desc: true}
	TodoAttachmentOrderPositionAsc            = TodoAttachmentOrder{Column: "position"}
	TodoAttachmentOrderPositionDesc           = TodoAttachmentOrder{Column: "position", Desc: true}
	TodoAttachmentOrderCreatedAtAsc           = TodoAttachmentOrder{Column: "created_at"}
	TodoAttachmentOrderCreatedAtDesc          = TodoAttachmentOrder{Column: "created_at", Desc: true}
	TodoAttachmentOrderCreatedByAccountIDAsc  = TodoAttachmentOrder{Column: "created_by_account_id"}
	TodoAttachmentOrderCreatedByAccountIDDesc = TodoAttachmentOrder{Column: "created_by_account_id", Desc: true}
	TodoAttachmentOrderUpdatedAtAsc           = TodoAttachmentOrder{Column: "updated_at"}
	TodoAttachmentOrderUpdatedAtDesc          = TodoAttachmentOrder{Column: "updated_at", Desc: true}
	TodoAttachmentOrderUpdatedByAccountIDAsc  = TodoAttachmentOrder{Column: "updated_by_account_id"}
	TodoAttachmentOrderUpdatedByAccountIDDesc = TodoAttachmentOrder{Column: "updated_by_account_id", Desc: true}
	TodoAttachmentOrderDeletedAtAsc           = TodoAttachmentOrder{Column: "deleted_at"}
	TodoAttachmentOrderDeletedAtDesc          = TodoAttachmentOrder{Column: "deleted_at", Desc: true}
	TodoAttachmentOrderDeletedByAccountIDAsc  = TodoAttachmentOrder{Column: "deleted_by_account_id"}
	TodoAttachmentOrderDeletedByAccountIDDesc = TodoAttachmentOrder{Column: "deleted_by_account_id", Desc: true}
)

// TodoAttachmentOrderTodo orders a TodoAttachment by a column of its Todo.
//
// Take the term from Todo's own orderings:
//
//	TodoAttachmentOrderTodo(TodoOrderIDDesc)
//
// The repository reaches it with a left join, so a TodoAttachment with no Todo
// sorts to one end rather than vanishing. Only Todo's own columns can be used;
// an ordering that itself reaches across a relation is refused, because one
// join is where this stops.
func TodoAttachmentOrderTodo(o TodoOrder) TodoAttachmentOrder {
	return TodoAttachmentOrder{Relation: "Todo", Column: o.Column, Desc: o.Desc}
}

// NewTodoAttachmentFilterEquals builds an empty TodoAttachmentFilterEquals to
// fill in.
func NewTodoAttachmentFilterEquals() *TodoAttachmentFilterEquals {
	return &TodoAttachmentFilterEquals{}
}

// NewTodoAttachmentFilterRange builds an empty TodoAttachmentFilterRange to
// fill in.
func NewTodoAttachmentFilterRange() *TodoAttachmentFilterRange { return &TodoAttachmentFilterRange{} }

// NewTodoAttachmentFilterContains builds an empty TodoAttachmentFilterContains
// to fill in.
func NewTodoAttachmentFilterContains() *TodoAttachmentFilterContains {
	return &TodoAttachmentFilterContains{}
}

// NewTodoAttachmentFilterLike builds an empty TodoAttachmentFilterLike to fill
// in.
func NewTodoAttachmentFilterLike() *TodoAttachmentFilterLike { return &TodoAttachmentFilterLike{} }

// NewTodoAttachmentFilterNull builds an empty TodoAttachmentFilterNull to fill
// in.
func NewTodoAttachmentFilterNull() *TodoAttachmentFilterNull { return &TodoAttachmentFilterNull{} }

// NewTodoAttachmentFilterWithout builds an empty TodoAttachmentFilterWithout
// to fill in.
func NewTodoAttachmentFilterWithout() *TodoAttachmentFilterWithout {
	return &TodoAttachmentFilterWithout{}
}

// NewTodoAttachmentFilter builds an empty filter, which matches every row the
// caller is allowed to see.
func NewTodoAttachmentFilter() TodoAttachmentFilter { return TodoAttachmentFilter{} }
