// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"github.com/simonjanss/rig/observe"
)

// Monitoring is this API's monitoring page, as far as generated code can know
// it.
//
// The page listens on 127.0.0.1:9084, on a listener of its own inside this
// same binary. It is not a route on the mux Register returns, and it cannot be
// made into one: which interface the page is bound to is the only boundary in
// front of it that a client cannot talk its way around, and sharing the API's
// listener would be giving that up. Serving it is two fields on the server
// this application already runs:
//
//	page, err := tracing.Page(api.Monitoring())
//	if err != nil { return nil, err }
//	if why := page.Unarmed(); why != "" {
//		app.Logger.Info("monitoring page not listening", "reason", why)
//	}
//
//	// ... serve.Config{Monitor: page.Handler(), MonitorAddr: page.Addr()}
//
// For the log half, open a sink, tee its handler into the logger this
// application already has, and set it on what this returns:
//
//	logs, err := observe.OpenLogs(observe.LogConfig{})
//	// ... serve.Config{Logger: slog.New(observe.Tee(base, logs.Handler()))}
//	cfg := api.Monitoring()
//	cfg.Logs = logs
//	page, err := tracing.Page(cfg)
//
// It is not a field a generator can fill in, because it is the sink itself
// rather than a path: the page reading the file the handler is writing is what
// makes a request and the lines it wrote one view, and two places naming that
// path would be one too many. Without it the page serves its request half and
// says why the other is empty.
//
// It hangs off the provider rather than standing alone because the page reads
// the span file that provider is writing: two places naming a path is two
// places to get it wrong, and the failure would be a page that is permanently
// empty for no visible reason.
//
// What is not here is where the spans go — that is the deployment's, the
// same as it is for [Tracing] — and, unless this project wrote one into its
// rig.yaml, the password, which is read from $RIG_MONITOR_PASSWORD at run
// time. With nothing in it the page does not listen at all: the port is closed
// rather than guarded, and Unarmed is what says so.
//
// The address is here and overridable — $RIG_MONITOR_ADDR wins over it —
// for the reason the span destination is the deployment's: moving a port
// should not need a regenerate. `monitoring.allow` is here because which
// networks may reach the page is a decision about this application rather than
// about the machine it happens to be on. It is the layer above the address
// rather than a substitute for it: the port decides who can open a connection,
// and the list decides which of them is answered, 404 before the password is
// compared.
func Monitoring() observe.PageConfig {
	return observe.PageConfig{
		ServiceName: "linearlite",
		Addr:        "127.0.0.1:9084",
		BasePath:    "/_rig/monitor",
		MaxTraces:   200,
		MaxLogs:     500,
		PasswordEnv: "RIG_MONITOR_PASSWORD",
	}
}
