// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"github.com/simonjanss/rig/runtime/tenancy"
)

// Permissions is every permission this API's endpoints require.
//
// Hand it to the authentication foundation at startup and it reconciles the
// permission table against it: a key this API checks and the database does not
// have is one no role can hold, which denies every caller — so the missing
// ones are written. A row the database has and this API does not check is
// reported and never deleted: it grants nothing, and removing it would take
// live grants with it.
//
// The names and descriptions come from the tables' own comments, so the
// sentence somebody reads while handing out a permission is the one that was
// already written about the table.
func Permissions() []tenancy.Permission {
	return []tenancy.Permission{
		{Key: "rig_account.read", Name: "Read rigaccounts", Description: "Read rigaccounts — One person inside one tenant. The person is the identity; this is who they are here."},
		{Key: "todo.delete", Name: "Delete todos", Description: "Delete todos — One item on the board."},
		{Key: "todo.read", Name: "Read todos", Description: "Read todos — One item on the board."},
		{Key: "todo.write", Name: "Write todos", Description: "Create and change todos — One item on the board."},
		{Key: "todo_attachment.attachment_file.read", Name: "Read the attachment of todoattachments", Description: "Download the attachment of todoattachments — A file attached to a todo."},
		{Key: "todo_attachment.attachment_file.write", Name: "Replace the attachment of todoattachments", Description: "Attach, replace and remove the attachment of todoattachments — A file attached to a todo. Held in addition to todo_attachment.write rather than implied by it: a role that may edit the row is not automatically a role that may change its attachment."},
		{Key: "todo_attachment.delete", Name: "Delete todoattachments", Description: "Delete todoattachments — A file attached to a todo."},
		{Key: "todo_attachment.read", Name: "Read todoattachments", Description: "Read todoattachments — A file attached to a todo."},
		{Key: "todo_attachment.write", Name: "Write todoattachments", Description: "Create and change todoattachments — A file attached to a todo."},
	}
}

// PermissionKeys is [Permissions] as the keys alone.
//
// It is what a role grant wants: the set an owner should hold is every
// permission this API checks, and deriving it beats a list somebody maintains
// — a hand-written one goes stale the moment a table is added, and the owner
// of a brand new tenant silently cannot touch it.
func PermissionKeys() []string {
	out := make([]string, 0, 9)
	for _, p := range Permissions() {
		out = append(out, p.Key)
	}
	return out
}
