// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"github.com/google/uuid"
	"github.com/simonjanss/rig/examples/linearlite/internal/model"
	"github.com/simonjanss/rig/runtime/tenancy"
)

// A page of RigNotificationSettings.
type RigNotificationSettingListResponse struct {
	// The rows in this page.
	//
	// Pointers, because that is what the repository returns and copying every row
	// to change that would be work nobody asked for.
	Data []*model.RigNotificationSetting `json:"data"`
	// Where this page sits in the full result set.
	Pagination Pagination `json:"pagination"`
}

// Query parameters for RigNotificationSetting.List.
type RigNotificationSettingListQuery struct {
	// Maximum rows to return.
	Limit int `json:"limit"`
	// Rows to skip before the first returned row.
	Offset int `json:"offset"`
	// How wide to read: own for the rignotificationsettings the caller created,
	// which is the default, or all for every one in the tenant. Asking for all
	// requires the rig_notification_setting.read.all permission and is refused
	// without it, rather than quietly answering with fewer rows.
	Scope tenancy.Scope `json:"scope"`
}

// Path parameters for RigNotificationSetting.Delete.
type RigNotificationSettingDeletePath struct {
	// Identifier of the RigNotificationSetting.
	ID uuid.UUID `json:"id"`
}

// Path parameters for RigNotificationSetting.Update.
type RigNotificationSettingUpdatePath struct {
	// Identifier of the RigNotificationSetting.
	ID uuid.UUID `json:"id"`
}
