// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/simonjanss/rig/examples/linearlite/internal/model"
	"github.com/simonjanss/rig/files"
	"github.com/simonjanss/rig/files/filehttp"
	"github.com/simonjanss/rig/runtime/idempotency"
	"github.com/simonjanss/rig/runtime/reqlog"
	"github.com/simonjanss/rig/runtime/tenancy"
)

// registerTodoAttachment mounts TodoAttachment's routes.
func registerTodoAttachment(mux *http.ServeMux, s Server, svc TodoAttachmentService) {
	mux.HandleFunc("GET /api/v1/todo-attachments", handleListTodoAttachments(s, svc))
	mux.HandleFunc("POST /api/v1/todo-attachments", handleCreateTodoAttachment(s, svc))
	mux.HandleFunc("QUERY /api/v1/todo-attachments", handleSearchTodoAttachments(s, svc))
	mux.HandleFunc("POST /api/v1/todo-attachments/_search", handleSearchTodoAttachments(s, svc))
	mux.HandleFunc("GET /api/v1/todo-attachments/_deleted", handleListDeletedTodoAttachments(s, svc))
	mux.HandleFunc("DELETE /api/v1/todo-attachments/{id}", handleDeleteTodoAttachment(s, svc))
	mux.HandleFunc("GET /api/v1/todo-attachments/{id}", handleGetTodoAttachment(s, svc))
	mux.HandleFunc("PATCH /api/v1/todo-attachments/{id}", handleUpdateTodoAttachment(s, svc))
	mux.HandleFunc("POST /api/v1/todo-attachments/{id}/_restore", handleRestoreTodoAttachment(s, svc))
	mux.HandleFunc("POST /api/v1/todo-attachments/{id}/attachment-file", handleUploadTodoAttachmentAttachmentFile(s, svc))
	mux.HandleFunc("GET /api/v1/todo-attachments/{id}/attachment-file/{fileId}/{filename}", handleDownloadTodoAttachmentAttachmentFile(s, svc))
}

// handleListTodoAttachments serves GET /api/v1/todo-attachments.
//
// List TodoAttachments.
func handleListTodoAttachments(s Server, svc TodoAttachmentService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		if err := tenancy.Require(claims, "todo_attachment.read"); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		var query TodoAttachmentListQuery
		limitParam, err := queryInt(r, "limit", 50)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		query.Limit = limitParam
		offsetParam, err := queryInt(r, "offset", 0)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		query.Offset = offsetParam

		req := NewRequest(claims, struct{}{}, query, struct{}{}, rc)

		out, err := svc.List(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeJSON(w, http.StatusOK, out)
	}
}

// handleCreateTodoAttachment serves POST /api/v1/todo-attachments.
//
// Create a TodoAttachment.
func handleCreateTodoAttachment(s Server, svc TodoAttachmentService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		if err := tenancy.Require(claims, "todo_attachment.write"); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		var body model.TodoAttachmentCreateInput
		var pending []*files.Pending
		if filehttp.IsMultipart(r) {
			filehttp.Deadline(w, filehttp.DefaultDeadline)
			form, err := filehttp.ReadForm(r)
			if err != nil {
				fail(s, w, r, rc, err)
				return
			}

			for {
				part, err := form.Next()
				if errors.Is(err, io.EOF) {
					break
				}
				if err != nil {
					fail(s, w, r, rc, err)
					return
				}

				switch part.Name {
				case filehttp.JSONPart:
					// The same body the JSON form carries, through the same decoder, so an unknown
					// key is refused here exactly as it is there and a 422 comes back with the
					// same field errors.
					if err := decodeReader(part.Body, &body); err != nil {
						fail(s, w, r, rc, err)
						return
					}
				case "attachmentFile":
					p, err := svc.Files().Prepare(ctx, part.Name, files.AttachRequest{
						TenantID: claims.TenantID,
						Upload:   part.Upload(),
					})
					if err != nil {
						fail(s, w, r, rc, err)
						return
					}
					pending = append(pending, p)
				default:
					// Refused rather than skipped, for the reason an unknown JSON key is refused:
					// a client that misspelled a part name has uploaded a file into nowhere, and a
					// 201 would tell it that worked.
					fail(s, w, r, rc, filehttp.ErrUnknownPart(part.Name))
					return
				}
			}

			if !hasPart(pending, "attachmentFile") {
				fail(s, w, r, rc, filehttp.ErrMissingPart("attachmentFile"))
				return
			}
		} else if err := decodeBody(r, &body); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		req := NewRequest(claims, struct{}{}, struct{}{}, body, rc)

		result, err := idempotency.Run(ctx, s.DB, idempotency.Request{
			TenantID: claims.TenantID,
			Key:      r.Header.Get("Idempotency-Key"),
			// The route pattern rather than the path, so the same key against the same
			// endpoint is one record however many rows it names. What the path said is in
			// the fingerprint.
			Endpoint:    rc.Route,
			Fingerprint: idempotency.Fingerprint([]any{struct{}{}, struct{}{}, body}),
			RequestID:   rc.RequestID,
		}, func(ctx context.Context) (int, any, error) {
			out, err := svc.Create(ctx, req, pending)
			return http.StatusCreated, out, err
		})
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeResult(w, result)
	}
}

// handleSearchTodoAttachments serves QUERY /api/v1/todo-attachments.
//
// Search TodoAttachments with filters.
func handleSearchTodoAttachments(s Server, svc TodoAttachmentService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		if err := tenancy.Require(claims, "todo_attachment.read"); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		var query TodoAttachmentSearchQuery
		limitParam, err := queryInt(r, "limit", 50)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		query.Limit = limitParam
		offsetParam, err := queryInt(r, "offset", 0)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		query.Offset = offsetParam

		var body TodoAttachmentSearchBody
		if err := decodeBody(r, &body); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		req := NewRequest(claims, struct{}{}, query, body, rc)

		out, err := svc.Search(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeJSON(w, http.StatusOK, out)
	}
}

// handleListDeletedTodoAttachments serves GET
// /api/v1/todo-attachments/_deleted.
//
// List retired TodoAttachments.
//
// A deletion stamps the row rather than removing it, so this is what was
// deleted and can still be brought back. Only rows inside the 30-day restore
// window appear: past it a row is gone as far as anyone is concerned, so it is
// not in the trash either.
func handleListDeletedTodoAttachments(s Server, svc TodoAttachmentService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		if err := tenancy.Require(claims, "todo_attachment.read"); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		var query TodoAttachmentListDeletedQuery
		limitParam, err := queryInt(r, "limit", 50)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		query.Limit = limitParam
		offsetParam, err := queryInt(r, "offset", 0)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		query.Offset = offsetParam

		req := NewRequest(claims, struct{}{}, query, struct{}{}, rc)

		out, err := svc.ListDeleted(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeJSON(w, http.StatusOK, out)
	}
}

// handleDeleteTodoAttachment serves DELETE /api/v1/todo-attachments/{id}.
//
// Delete a TodoAttachment.
//
// The row is retired by stamping a deletion time; it stops appearing in reads
// but can be restored within the retention window.
func handleDeleteTodoAttachment(s Server, svc TodoAttachmentService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		if err := tenancy.Require(claims, "todo_attachment.delete"); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		var path TodoAttachmentDeletePath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		req := NewRequest(claims, path, struct{}{}, struct{}{}, rc)

		if err := svc.Delete(ctx, req); err != nil {
			fail(s, w, r, rc, err)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleGetTodoAttachment serves GET /api/v1/todo-attachments/{id}.
//
// Fetch one TodoAttachment by identifier.
func handleGetTodoAttachment(s Server, svc TodoAttachmentService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		if err := tenancy.Require(claims, "todo_attachment.read"); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		var path TodoAttachmentGetPath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		req := NewRequest(claims, path, struct{}{}, struct{}{}, rc)

		out, err := svc.Get(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeJSON(w, http.StatusOK, out)
	}
}

// handleUpdateTodoAttachment serves PATCH /api/v1/todo-attachments/{id}.
//
// Update a TodoAttachment.
//
// Only the fields present in the body are changed. A field set to null is
// cleared; a field left out is left alone.
func handleUpdateTodoAttachment(s Server, svc TodoAttachmentService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		if err := tenancy.Require(claims, "todo_attachment.write"); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		var path TodoAttachmentUpdatePath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		var body model.TodoAttachmentUpdateInput
		if err := decodeBody(r, &body); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		req := NewRequest(claims, path, struct{}{}, body, rc)

		result, err := idempotency.Run(ctx, s.DB, idempotency.Request{
			TenantID: claims.TenantID,
			Key:      r.Header.Get("Idempotency-Key"),
			// The route pattern rather than the path, so the same key against the same
			// endpoint is one record however many rows it names. What the path said is in
			// the fingerprint.
			Endpoint:    rc.Route,
			Fingerprint: idempotency.Fingerprint([]any{path, struct{}{}, body}),
			RequestID:   rc.RequestID,
		}, func(ctx context.Context) (int, any, error) {
			out, err := svc.Update(ctx, req)
			return http.StatusOK, out, err
		})
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeResult(w, result)
	}
}

// handleRestoreTodoAttachment serves POST
// /api/v1/todo-attachments/{id}/_restore.
//
// Bring a retired TodoAttachment back.
//
// The deletion stamp is cleared and the row appears in reads again. It works
// for 30 days after the deletion; past that the row is no longer eligible and
// this answers 409.
//
// Restoring a row that was never deleted is not an error. It is already in the
// state the caller asked for, and answering otherwise would make a retry of a
// request whose response went missing look like a failure.
//
// The request carries no fields. What to do when the world has moved on while
// the row was retired — a unique value taken by something created since —
// is the application's decision, and it is made in the restore hook: refuse,
// or change the row so that it fits.
//
// Every rule then runs against whatever the hook settled on, not only the ones
// for fields it touched. The row was not live, so nothing about it has been
// checked against the world it is returning to.
func handleRestoreTodoAttachment(s Server, svc TodoAttachmentService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		if err := tenancy.Require(claims, "todo_attachment.write"); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		var path TodoAttachmentRestorePath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		req := NewRequest(claims, path, struct{}{}, struct{}{}, rc)

		result, err := idempotency.Run(ctx, s.DB, idempotency.Request{
			TenantID: claims.TenantID,
			Key:      r.Header.Get("Idempotency-Key"),
			// The route pattern rather than the path, so the same key against the same
			// endpoint is one record however many rows it names. What the path said is in
			// the fingerprint.
			Endpoint:    rc.Route,
			Fingerprint: idempotency.Fingerprint([]any{path, struct{}{}, struct{}{}}),
			RequestID:   rc.RequestID,
		}, func(ctx context.Context) (int, any, error) {
			out, err := svc.Restore(ctx, req)
			return http.StatusOK, out, err
		})
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeResult(w, result)
	}
}

// handleUploadTodoAttachmentAttachmentFile serves POST
// /api/v1/todo-attachments/{id}/attachment-file.
//
// Attach a file to a TodoAttachment as its attachment.
//
// The form carries one part, named attachmentFile. Nothing else in it is
// accepted.
//
// The type is sniffed from the bytes rather than taken from what the request
// claimed, and the sniffed type is what is stored and what a download
// announces. A file replacing an existing one does not delete it: a row that
// keeps its previous versions still points at the old file from every one of
// them.
func handleUploadTodoAttachmentAttachmentFile(s Server, svc TodoAttachmentService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		if err := tenancy.Require(claims, "todo_attachment.attachment_file.write"); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		var path TodoAttachmentUploadAttachmentFilePath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		filehttp.Deadline(w, filehttp.DefaultDeadline)
		body, err := filehttp.OnePart(r, "attachmentFile")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}

		req := NewRequest(claims, path, struct{}{}, body, rc)
		out, err := svc.UploadAttachmentFile(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeJSON(w, http.StatusCreated, out)
	}
}

// handleDownloadTodoAttachmentAttachmentFile serves GET
// /api/v1/todo-attachments/{id}/attachment-file/{fileId}/{filename}.
//
// Fetch a TodoAttachment's attachment.
//
// Answers range and conditional requests, so a resumed download does not start
// over and a media element can seek.
func handleDownloadTodoAttachmentAttachmentFile(s Server, svc TodoAttachmentService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		if err := tenancy.Require(claims, "todo_attachment.attachment_file.read"); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		var path TodoAttachmentDownloadAttachmentFilePath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam
		fileIDParam, err := pathUUID(r, "fileId")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.FileID = fileIDParam
		filenameParam, err := pathString(r, "filename")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.Filename = filenameParam

		filehttp.Deadline(w, filehttp.DefaultDeadline)
		req := NewRequest(claims, path, struct{}{}, struct{}{}, rc)

		content, err := svc.DownloadAttachmentFile(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		defer content.Body.Close()

		// ServeContent from here, so a range request and a conditional request are
		// answered rather than ignored: a resumed download does not start over and a
		// media element can seek.
		filehttp.Serve(w, r, content, svc.Files().InlineTypes())
	}
}
