// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

import (
	"time"

	"github.com/google/uuid"
)

// Conditions a Note must satisfy to match a search.
type NoteFilter struct {
	// Fields that must equal the given value.
	Equals *NoteFilterEquals `json:"equals,omitempty"`
	// Fields that must not equal the given value.
	NotEquals *NoteFilterEquals `json:"notEquals,omitempty"`
	// Fields that must be greater than the given value.
	GreaterThan *NoteFilterRange `json:"greaterThan,omitempty"`
	// Fields that must be less than the given value.
	SmallerThan *NoteFilterRange `json:"smallerThan,omitempty"`
	// Fields that must be greater than or equal to the given value.
	GreaterOrEqual *NoteFilterRange `json:"greaterOrEqual,omitempty"`
	// Fields that must be less than or equal to the given value.
	SmallerOrEqual *NoteFilterRange `json:"smallerOrEqual,omitempty"`
	// Fields that must be one of the given values.
	Contains *NoteFilterContains `json:"contains,omitempty"`
	// Fields that must not be one of the given values.
	NotContains *NoteFilterContains `json:"notContains,omitempty"`
	// Text fields that must match the given pattern.
	Like *NoteFilterLike `json:"like,omitempty"`
	// Text fields that must not match the given pattern.
	NotLike *NoteFilterLike `json:"notLike,omitempty"`
	// Fields that must be null.
	Null *NoteFilterNull `json:"null,omitempty"`
	// Fields that must not be null.
	NotNull *NoteFilterNull `json:"notNull,omitempty"`
	// Combine this filter's conditions with OR instead of AND.
	OrCondition bool `json:"orCondition"`
	// Sub-filters combined with this one, so that AND and OR can be mixed to any
	// depth.
	NestedFilters []NoteFilter `json:"nestedFilters,omitempty"`
}

// Set-membership conditions on Note fields.
type NoteFilterContains struct {
	// Unique identifier for this row.
	ID []uuid.UUID `json:"id,omitempty"`
	// What the note is about, in a few words.
	Title []string `json:"title,omitempty"`
	// The note itself, or null while it is just a title.
	Body []string `json:"body,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt []time.Time `json:"createdAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID []uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt []time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID []uuid.UUID `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt []time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID []uuid.UUID `json:"deletedByAccountId,omitempty"`
	// API key this row was created through, when it was an integration rather than
	// a person.
	CreatedByAPIKeyID []uuid.UUID `json:"createdByApiKeyId,omitempty"`
	// API key this row was last updated through, when it was an integration rather
	// than a person.
	UpdatedByAPIKeyID []uuid.UUID `json:"updatedByApiKeyId,omitempty"`
	// API key this row was soft-deleted through, when it was an integration rather
	// than a person.
	DeletedByAPIKeyID []uuid.UUID `json:"deletedByApiKeyId,omitempty"`
	// When the note goes live, or null while it is a draft. Notifications about it
	// are due then.
	PublishAt []time.Time `json:"publishAt,omitempty"`
}

// Exact-match conditions on Note fields.
type NoteFilterEquals struct {
	// Unique identifier for this row.
	ID *uuid.UUID `json:"id,omitempty"`
	// What the note is about, in a few words.
	Title *string `json:"title,omitempty"`
	// The note itself, or null while it is just a title.
	Body *string `json:"body,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *uuid.UUID `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *uuid.UUID `json:"deletedByAccountId,omitempty"`
	// API key this row was created through, when it was an integration rather than
	// a person.
	CreatedByAPIKeyID *uuid.UUID `json:"createdByApiKeyId,omitempty"`
	// API key this row was last updated through, when it was an integration rather
	// than a person.
	UpdatedByAPIKeyID *uuid.UUID `json:"updatedByApiKeyId,omitempty"`
	// API key this row was soft-deleted through, when it was an integration rather
	// than a person.
	DeletedByAPIKeyID *uuid.UUID `json:"deletedByApiKeyId,omitempty"`
	// When the note goes live, or null while it is a draft. Notifications about it
	// are due then.
	PublishAt *time.Time `json:"publishAt,omitempty"`
}

// Pattern conditions on Note text fields.
type NoteFilterLike struct {
	// What the note is about, in a few words.
	Title *string `json:"title,omitempty"`
	// The note itself, or null while it is just a title.
	Body *string `json:"body,omitempty"`
}

// Presence conditions on nullable Note fields.
type NoteFilterNull struct {
	// The note itself, or null while it is just a title.
	Body *bool `json:"body,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *bool `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *bool `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *bool `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *bool `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *bool `json:"deletedByAccountId,omitempty"`
	// API key this row was created through, when it was an integration rather than
	// a person.
	CreatedByAPIKeyID *bool `json:"createdByApiKeyId,omitempty"`
	// API key this row was last updated through, when it was an integration rather
	// than a person.
	UpdatedByAPIKeyID *bool `json:"updatedByApiKeyId,omitempty"`
	// API key this row was soft-deleted through, when it was an integration rather
	// than a person.
	DeletedByAPIKeyID *bool `json:"deletedByApiKeyId,omitempty"`
	// When the note goes live, or null while it is a draft. Notifications about it
	// are due then.
	PublishAt *bool `json:"publishAt,omitempty"`
}

// Ordering conditions on Note fields that can be compared.
type NoteFilterRange struct {
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// When the note goes live, or null while it is a draft. Notifications about it
	// are due then.
	PublishAt *time.Time `json:"publishAt,omitempty"`
}

// NewNoteFilter builds an empty filter, which matches every row the caller is
// allowed to see.
func NewNoteFilter() NoteFilter { return NoteFilter{} }
