// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// Exact-match conditions on Bookmark fields.
type BookmarkFilterEquals struct {
	// Unique identifier for this row.
	ID *uuid.UUID `json:"id,omitempty"`
	// What to call it in a list.
	Title *string `json:"title,omitempty"`
	// Where it points.
	URL *string `json:"url,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *uuid.UUID `json:"updatedByAccountId,omitempty"`
}

// Ordering conditions on Bookmark fields that can be compared.
type BookmarkFilterRange struct {
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Set-membership conditions on Bookmark fields.
type BookmarkFilterContains struct {
	// Unique identifier for this row.
	ID []uuid.UUID `json:"id,omitempty"`
	// What to call it in a list.
	Title []string `json:"title,omitempty"`
	// Where it points.
	URL []string `json:"url,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt []time.Time `json:"createdAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID []uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt []time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID []uuid.UUID `json:"updatedByAccountId,omitempty"`
}

// Pattern conditions on Bookmark text fields.
type BookmarkFilterLike struct {
	// What to call it in a list.
	Title *string `json:"title,omitempty"`
	// Where it points.
	URL *string `json:"url,omitempty"`
}

// Presence conditions on nullable Bookmark fields.
type BookmarkFilterNull struct {
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *bool `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *bool `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *bool `json:"updatedByAccountId,omitempty"`
}

// Conditions a Bookmark must satisfy to match a search.
type BookmarkFilter struct {
	// Fields that must equal the given value.
	Equals *BookmarkFilterEquals `json:"equals,omitempty"`
	// Fields that must not equal the given value.
	NotEquals *BookmarkFilterEquals `json:"notEquals,omitempty"`
	// Fields that must be greater than the given value.
	GreaterThan *BookmarkFilterRange `json:"greaterThan,omitempty"`
	// Fields that must be less than the given value.
	SmallerThan *BookmarkFilterRange `json:"smallerThan,omitempty"`
	// Fields that must be greater than or equal to the given value.
	GreaterOrEqual *BookmarkFilterRange `json:"greaterOrEqual,omitempty"`
	// Fields that must be less than or equal to the given value.
	SmallerOrEqual *BookmarkFilterRange `json:"smallerOrEqual,omitempty"`
	// Fields that must be one of the given values.
	Contains *BookmarkFilterContains `json:"contains,omitempty"`
	// Fields that must not be one of the given values.
	NotContains *BookmarkFilterContains `json:"notContains,omitempty"`
	// Text fields that must match the given pattern.
	Like *BookmarkFilterLike `json:"like,omitempty"`
	// Text fields that must not match the given pattern.
	NotLike *BookmarkFilterLike `json:"notLike,omitempty"`
	// Fields that must be null.
	Null *BookmarkFilterNull `json:"null,omitempty"`
	// Fields that must not be null.
	NotNull *BookmarkFilterNull `json:"notNull,omitempty"`
	// Combine this filter's conditions with OR instead of AND.
	OrCondition bool `json:"orCondition,omitempty"`
	// Sub-filters combined with this one, so that AND and OR can be mixed to any
	// depth.
	NestedFilters []BookmarkFilter `json:"nestedFilters,omitempty"`
}

// BookmarkPage says which slice of a result to return, and in what order.
//
// The zero value is the first page at the repository's default size, in the
// table's configured order, which is what a caller who has not thought about
// it wants.
type BookmarkPage struct {
	Limit  int
	Offset int

	// OrderBy replaces the table's default ordering.
	OrderBy []BookmarkOrder
}

// BookmarkOrder is one clause of an ordering.
//
// Relation names the relation the column belongs to, and is empty for this
// table's own columns. The repository turns it into a left join, so a row
// whose related row is missing still appears — at one end of the order
// rather than not at all.
type BookmarkOrder struct {
	Relation string
	Column   string
	Desc     bool
}

// The orderings a Bookmark supports.
var (
	BookmarkOrderIDAsc                  = BookmarkOrder{Column: "id"}
	BookmarkOrderIDDesc                 = BookmarkOrder{Column: "id", Desc: true}
	BookmarkOrderTenantIDAsc            = BookmarkOrder{Column: "tenant_id"}
	BookmarkOrderTenantIDDesc           = BookmarkOrder{Column: "tenant_id", Desc: true}
	BookmarkOrderTitleAsc               = BookmarkOrder{Column: "title"}
	BookmarkOrderTitleDesc              = BookmarkOrder{Column: "title", Desc: true}
	BookmarkOrderURLAsc                 = BookmarkOrder{Column: "url"}
	BookmarkOrderURLDesc                = BookmarkOrder{Column: "url", Desc: true}
	BookmarkOrderCreatedAtAsc           = BookmarkOrder{Column: "created_at"}
	BookmarkOrderCreatedAtDesc          = BookmarkOrder{Column: "created_at", Desc: true}
	BookmarkOrderCreatedByAccountIDAsc  = BookmarkOrder{Column: "created_by_account_id"}
	BookmarkOrderCreatedByAccountIDDesc = BookmarkOrder{Column: "created_by_account_id", Desc: true}
	BookmarkOrderUpdatedAtAsc           = BookmarkOrder{Column: "updated_at"}
	BookmarkOrderUpdatedAtDesc          = BookmarkOrder{Column: "updated_at", Desc: true}
	BookmarkOrderUpdatedByAccountIDAsc  = BookmarkOrder{Column: "updated_by_account_id"}
	BookmarkOrderUpdatedByAccountIDDesc = BookmarkOrder{Column: "updated_by_account_id", Desc: true}
)

// NewBookmarkFilterEquals builds an empty BookmarkFilterEquals to fill in.
func NewBookmarkFilterEquals() *BookmarkFilterEquals { return &BookmarkFilterEquals{} }

// NewBookmarkFilterRange builds an empty BookmarkFilterRange to fill in.
func NewBookmarkFilterRange() *BookmarkFilterRange { return &BookmarkFilterRange{} }

// NewBookmarkFilterContains builds an empty BookmarkFilterContains to fill in.
func NewBookmarkFilterContains() *BookmarkFilterContains { return &BookmarkFilterContains{} }

// NewBookmarkFilterLike builds an empty BookmarkFilterLike to fill in.
func NewBookmarkFilterLike() *BookmarkFilterLike { return &BookmarkFilterLike{} }

// NewBookmarkFilterNull builds an empty BookmarkFilterNull to fill in.
func NewBookmarkFilterNull() *BookmarkFilterNull { return &BookmarkFilterNull{} }

// NewBookmarkFilter builds an empty filter, which matches every row the caller
// is allowed to see.
func NewBookmarkFilter() BookmarkFilter { return BookmarkFilter{} }
