// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// A link somebody saved.
//
// It is the one definition of a Bookmark: the repository scans into it and the
// API returns it, so there is no conversion between two shapes of the same
// thing and no field that can go missing from one of them.
type Bookmark struct {
	// Unique identifier for this row.
	ID uuid.UUID `json:"id"`
	// Tenant this row belongs to. Every query is scoped by it.
	TenantID uuid.UUID `json:"tenantId"`
	// What to call it in a list.
	Title string `json:"title"`
	// Where it points.
	URL string `json:"url"`
	// When this row was created. Set automatically and never changes.
	CreatedAt time.Time `json:"createdAt"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *uuid.UUID `json:"updatedByAccountId,omitempty"`
}

// TableBookmark is the table this entity is stored in.
const TableBookmark = "bookmark"

// Column names for bookmark, so nothing has to spell one out.
const (
	ColumnBookmarkID                 = "id"
	ColumnBookmarkTenantID           = "tenant_id"
	ColumnBookmarkTitle              = "title"
	ColumnBookmarkURL                = "url"
	ColumnBookmarkCreatedAt          = "created_at"
	ColumnBookmarkCreatedByAccountID = "created_by_account_id"
	ColumnBookmarkUpdatedAt          = "updated_at"
	ColumnBookmarkUpdatedByAccountID = "updated_by_account_id"
)

// BookmarkColumns is every column, in the order the row is scanned.
var BookmarkColumns = []string{"id", "tenant_id", "title", "url", "created_at", "created_by_account_id", "updated_at", "updated_by_account_id"}
