// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the code that calls it.

/** How urgently a task wants attention. */
export const TodoPriority = {
    /** Worth doing eventually. */
    Low: "low",
    /** Worth doing soon. This is the default. */
    Normal: "normal",
    /** Worth doing before anything else. */
    High: "high",
} as const;

/**
 * One of the values of TodoPriority.
 *
 * The type and the object share a name on purpose: TypeScript keeps types and
 * values in separate namespaces, so `TodoPriority.Low` and `: TodoPriority`
 * both read the way somebody would write them.
 */
export type TodoPriority = (typeof TodoPriority)[keyof typeof TodoPriority];

/**
 * Every value of TodoPriority, in declaration order. It is what a picker is
 * drawn from.
 */
export const allTodoPriority: readonly TodoPriority[] = [TodoPriority.Low, TodoPriority.Normal, TodoPriority.High];
