// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the code that calls it.

import type { TodoPriority } from "./todo_priority.gen.js";
import type { TodoFilter } from "./todo_query.gen.js";
import type { FieldError, Upload } from "@rig/client";

/**
 * TodoCreateFiles is the files a create carries with it.
 *
 * A not-null file column is unreachable without this: the row would have to
 * exist before an upload had anywhere to go, and it cannot exist without one.
 * So a required column is a plain member here and a nullable one is optional,
 * and leaving out a file the schema insists on does not compile rather than
 * coming back a 422.
 */
export type TodoCreateFiles = {
    coverFile?: Upload;
};

/**
 * TodoListQuery is the query string listTodos takes.
 *
 * Every member is optional. The server applies a parameter's default when the
 * parameter is absent, so leaving one out is how to ask for the default rather
 * than for zero.
 */
export type TodoListQuery = {
    /** Maximum rows to return. */
    limit?: number;
    /** Rows to skip before the first returned row. */
    offset?: number;
};

/**
 * TodoCreateInput is what creating a Todo takes.
 *
 * A field the server fills in — the identifier, the tenant, the audit columns
 * — is not here: those are not a caller's to send.
 */
export type TodoCreateInput = {
    /** What needs doing, in a few words. */
    title: string;
    /** Anything worth remembering that does not fit in the title. */
    notes?: string | null;
    /** Whether the task has been completed. */
    isDone: boolean;
    /** How urgently the task wants attention. */
    priority: TodoPriority;
    /** When the task is due, or null if it never expires. */
    dueAt?: string | null;
    /** A picture for the todo, if it has one. */
    coverFileId?: string | null;
};

/**
 * TodoCreateFields is what a validation failure says, shaped like the body it
 * is about — one member per member, so each message can be put beside the
 * control it belongs to.
 *
 * A member is absent when there was nothing wrong with that field. It arrives
 * as the `fields` of the error the call threw.
 */
export type TodoCreateFields = {
    title?: FieldError;
    notes?: FieldError;
    isDone?: FieldError;
    priority?: FieldError;
    dueAt?: FieldError;
    coverFileId?: FieldError;
    /**
     * What was wrong with the request as a whole rather than with any one
     * field.
     */
    entity?: FieldError;
};

/** The body searchTodos sends. */
export type TodoSearchBody = {
    /** Conditions rows must satisfy. */
    filter: TodoFilter;
};

/**
 * TodoSearchQuery is the query string searchTodos takes.
 *
 * Every member is optional. The server applies a parameter's default when the
 * parameter is absent, so leaving one out is how to ask for the default rather
 * than for zero.
 */
export type TodoSearchQuery = {
    /** Maximum rows to return. */
    limit?: number;
    /** Rows to skip before the first returned row. */
    offset?: number;
};

/**
 * TodoListDeletedQuery is the query string listDeletedTodos takes.
 *
 * Every member is optional. The server applies a parameter's default when the
 * parameter is absent, so leaving one out is how to ask for the default rather
 * than for zero.
 */
export type TodoListDeletedQuery = {
    /** Maximum rows to return. */
    limit?: number;
    /** Rows to skip before the first returned row. */
    offset?: number;
};

/**
 * TodoUpdateInput is what changing a Todo takes.
 *
 * A field left out is left alone. A nullable field set to `null` is cleared —
 * which is why only some members accept one: a column that cannot hold null has
 * no way to be given one.
 *
 * `undefined` reads as left out, because JSON.stringify drops the key either
 * way. It is `null` that is a request to clear.
 */
export type TodoUpdateInput = {
    /** What needs doing, in a few words. */
    title?: string;
    /** Anything worth remembering that does not fit in the title. */
    notes?: string | null;
    /** Whether the task has been completed. */
    isDone?: boolean;
    /** How urgently the task wants attention. */
    priority?: TodoPriority;
    /** When the task is due, or null if it never expires. */
    dueAt?: string | null;
    /** A picture for the todo, if it has one. */
    coverFileId?: string | null;
};

/**
 * TodoUpdateFields is what a validation failure says, shaped like the body it
 * is about — one member per member, so each message can be put beside the
 * control it belongs to.
 *
 * A member is absent when there was nothing wrong with that field. It arrives
 * as the `fields` of the error the call threw.
 */
export type TodoUpdateFields = {
    title?: FieldError;
    notes?: FieldError;
    isDone?: FieldError;
    priority?: FieldError;
    dueAt?: FieldError;
    coverFileId?: FieldError;
    /**
     * What was wrong with the request as a whole rather than with any one
     * field.
     */
    entity?: FieldError;
};

/** The body completeTodo sends. */
export type TodoCompleteBody = {
    /** What was done, appended to the task's notes. */
    note?: string | null;
};

/**
 * TodoCompleteFields is what a validation failure says, shaped like the body it
 * is about — one member per member, so each message can be put beside the
 * control it belongs to.
 *
 * A member is absent when there was nothing wrong with that field. It arrives
 * as the `fields` of the error the call threw.
 */
export type TodoCompleteFields = {
    note?: FieldError;
    /**
     * What was wrong with the request as a whole rather than with any one
     * field.
     */
    entity?: FieldError;
};

/** The body revertTodo sends. */
export type TodoRevertBody = {
    /** The version to put back, from the Todo's history. */
    versionId: string;
};

