// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/simonjanss/rig/files"
	"github.com/simonjanss/rig/files/blob"
	"github.com/simonjanss/rig/runtime/serve"
)

// NewFiles builds this project's file handling from its `files:` block.
//
// The pool is the same one the repositories use, and that is not a detail: the
// transaction that finalizes a file and writes the row pointing at it has to
// be one transaction, and it cannot be if the two live in different pools.
func NewFiles(db files.DB) *files.Service {
	return files.New(files.Config{
		Store:          blob.NewMemory(),
		DB:             db,
		MaxBytes:       5242880,
		InlineTypes:    []string{"image/jpeg", "image/png", "image/gif", "image/webp"},
		AbandonedAfter: 86400 * time.Second,
		RestoreWindow:  2592000 * time.Second,
	})
}

// FileSweeper is the housekeeping task: abandoned uploads, and trash past the
// restore window.
//
// A task rather than a goroutine, so it is a subcommand in a cron job rather
// than something racing itself in every replica. Register it in
// serve.Config.Tasks and run `<binary> sweep-files`.
func FileSweeper(svc *files.Service) serve.Task {
	return func(ctx context.Context, _ *pgxpool.Pool) error {
		_, err := svc.Sweep(ctx)
		return err
	}
}
