// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"strconv"
	"time"

	"github.com/google/uuid"
	"github.com/simonjanss/rig/runtime/rigerr"
	"github.com/simonjanss/rig/runtime/tenancy"
	"github.com/simonjanss/rig/runtime/throttle"
)

// Authenticator identifies a caller and serves its own routes.
//
// It is declared here rather than imported, and that is the whole trick:
// [github.com/simonjanss/rig/auth.Auth] satisfies it without either side
// knowing the other exists. A field typed as the auth package's own would make
// every project depend on it — argon2, OAuth and all — including the ones
// with no authentication at all.
//
// Anything else with these two methods works just as well: a wrapper that adds
// a header check, a stub in a test, an entirely different implementation.
type Authenticator interface {
	// Claims identifies the caller behind a request.
	Claims(*http.Request) (tenancy.Claims, error)
	// Mount registers the authentication routes — signing in, refreshing, keys
	// — on the same mux the resource routes are on.
	Mount(*http.ServeMux)
}

// Server is the behavior every handler shares.
type Server struct {
	// Auth wires the whole authentication foundation in one field.
	//
	// Setting it does two things that otherwise have to be remembered separately:
	// GetClaims comes from it, and its routes are mounted on the mux Register
	// returns. Wiring the claims from one thing and mounting another is a mistake
	// this makes unavailable.
	//
	// Nil for a project with no authentication, which then has to supply GetClaims
	// itself.
	Auth Authenticator

	// GetClaims establishes who is calling. A handler does not run without it, so
	// a route cannot accidentally be left unauthenticated.
	//
	// Auth supplies it. Set this instead for a project that authenticates its own
	// way, or has no auth routes to mount.
	GetClaims func(*http.Request) (tenancy.Claims, error)

	// RequestID labels a request for the logs. Nil generates nothing, and the
	// field is simply absent from error bodies.
	RequestID func(*http.Request) string

	// OnError turns a service error into a response. Nil uses DefaultErrorMapper,
	// which is the right behavior for almost everyone.
	OnError func(w http.ResponseWriter, r *http.Request, rc RequestContext, err error)

	// PreHooks run before anything else, in order. A hook that writes a response
	// stops the request.
	PreHooks []func(w http.ResponseWriter, r *http.Request) bool

	// Context lets a hook attach values a service will read.
	Context func(ctx context.Context, r *http.Request) context.Context
}

// Handlers is every resource's service, plus the shared behavior.
//
// One field per resource is deliberate: adding a table and forgetting to wire
// it up will not compile, rather than producing a route that answers 404 until
// somebody notices.
type Handlers struct {
	Server Server

	Todo TodoService
}

// Register mounts every route and returns the mux.
//
// The patterns come from the compiled document, so the router, the OpenAPI
// document, and the generated client all describe the same paths.
//
// It makes the mux rather than taking one, because a caller has nothing to
// decide about it: the patterns are absolute and already carry the base path.
// What comes back is a *http.ServeMux and not an opaque handler, so anything
// else this server answers — static files, a second API, another generator's
// routes — is still a Handle call on it.
func Register(h Handlers) *http.ServeMux {
	if h.Server.Auth != nil {
		if h.Server.GetClaims != nil {
			// Two answers to "who is calling" is not a preference to resolve quietly.
			// Whichever one lost would go on looking wired, and the difference only shows
			// up as a caller who is somebody else.
			panic("api.Register: set Server.Auth or Server.GetClaims, not both")
		}
		h.Server.GetClaims = h.Server.Auth.Claims
	}

	if h.Server.GetClaims == nil {
		// Refusing here rather than defaulting to anonymous is the point: a server
		// with no way to identify a caller cannot enforce tenancy, and every generated
		// query depends on it.
		panic("api.Register: set Server.Auth, or Server.GetClaims if this project authenticates its own way")
	}

	mux := http.NewServeMux()

	if h.Todo != nil {
		registerTodo(mux, h.Server, h.Todo)
	}

	// After the resources, so a pattern collision between the two is a panic
	// naming the auth route rather than the resource one — and the resource
	// routes are the ones this project owns.
	if h.Server.Auth != nil {
		h.Server.Auth.Mount(mux)
	}

	return mux
}

// maxBodyBytes bounds a request body. Without a limit, one client can exhaust
// the server's memory by streaming forever.
const maxBodyBytes = 1 << 20

// prepare runs the shared front half of every handler: the hooks, the claims,
// and the request metadata.
func prepare(s Server, w http.ResponseWriter, r *http.Request) (context.Context, tenancy.Claims, RequestContext, bool) {
	return resolve(s, w, r, true)
}

// resolve is the body of both, differing only in whether a caller who cannot
// be identified is refused.
func resolve(s Server, w http.ResponseWriter, r *http.Request, required bool) (context.Context, tenancy.Claims, RequestContext, bool) {
	rc := RequestContext{
		Method:     r.Method,
		Path:       r.URL.Path,
		Route:      r.Pattern,
		RemoteAddr: r.RemoteAddr,
		UserAgent:  r.UserAgent(),
	}
	if s.RequestID != nil {
		rc.RequestID = s.RequestID(r)
	}

	for _, hook := range s.PreHooks {
		if !hook(w, r) {
			return nil, tenancy.Claims{}, rc, false
		}
	}

	claims, err := s.GetClaims(r)
	if err != nil {
		if required {
			fail(s, w, r, rc, err)
			return nil, tenancy.Claims{}, rc, false
		}
		// Public, so the caller is nobody rather than nobody yet. The claims go on the
		// context all the same: what needs a tenant refuses there, where the reason is
		// about the thing being asked for.
		claims = tenancy.Claims{}
	}

	ctx := tenancy.NewContext(r.Context(), claims)
	if s.Context != nil {
		ctx = s.Context(ctx, r)
	}
	return ctx, claims, rc, true
}

// fail writes an error response.
func fail(s Server, w http.ResponseWriter, r *http.Request, rc RequestContext, err error) {
	if s.OnError != nil {
		s.OnError(w, r, rc, err)
		return
	}
	DefaultErrorMapper(w, r, rc, err)
}

// DefaultErrorMapper turns an error into a response.
//
// An internal failure's detail never reaches the client: it is exactly the
// kind of thing that leaks a table name or a connection string. The request
// identifier goes out instead, so the detail can be found in the logs.
func DefaultErrorMapper(w http.ResponseWriter, _ *http.Request, rc RequestContext, err error) {
	code := rigerr.CodeOf(err)

	message := err.Error()
	var typed *rigerr.Error
	if errors.As(err, &typed) {
		message = typed.Message
	}
	if code == rigerr.CodeInternal {
		message = "something went wrong"
	}

	// A 429 with no Retry-After leaves a client with nothing to do but guess, and
	// clients that guess retry immediately.
	if refusal, ok := throttle.RefusalOf(err); ok {
		refusal.Decision().SetHeaders(w.Header())
	}

	// A validation failure carries its own shape — one member per field of the
	// input — and answering with that instead of only a sentence is the
	// difference between a client highlighting the field and a client parsing
	// prose to find out which one.
	fields, _ := rigerr.FieldsOf(err)

	writeJSON(w, code.HTTPStatus(), Error{
		Code:      code,
		Message:   message,
		RequestID: rc.RequestID,
		Fields:    fields,
	})
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	if body == nil {
		return
	}
	_ = json.NewEncoder(w).Encode(body)
}

// decodeBody reads a JSON request body.
//
// Unknown fields are rejected. A client that misspells a field name is asking
// for something it will not get, and telling it so beats silently ignoring
// half the request.
func decodeBody(r *http.Request, into any) error {
	body := io.LimitReader(r.Body, maxBodyBytes)
	dec := json.NewDecoder(body)
	dec.DisallowUnknownFields()

	if err := dec.Decode(into); err != nil {
		if err == io.EOF {
			return rigerr.BadRequest("the request body is empty")
		}
		return rigerr.BadRequest("cannot read the request body: %v", err)
	}
	return nil
}

func pathUUID(r *http.Request, name string) (uuid.UUID, error) {
	raw := r.PathValue(name)
	id, err := uuid.Parse(raw)
	if err != nil {
		return uuid.Nil, rigerr.BadRequest("%s is not a valid identifier", name)
	}
	return id, nil
}

func pathInt(r *http.Request, name string) (int, error) {
	v, err := strconv.Atoi(r.PathValue(name))
	if err != nil {
		return 0, rigerr.BadRequest("%s must be a whole number", name)
	}
	return v, nil
}

func pathString(r *http.Request, name string) (string, error) {
	raw := r.PathValue(name)
	if raw == "" {
		return "", rigerr.BadRequest("%s is required", name)
	}
	return raw, nil
}

// queryInt reads an integer query parameter, falling back when absent.
func queryInt(r *http.Request, name string, fallback int) (int, error) {
	raw := r.URL.Query().Get(name)
	if raw == "" {
		return fallback, nil
	}
	v, err := strconv.Atoi(raw)
	if err != nil {
		return 0, rigerr.BadRequest("%s must be a whole number", name)
	}
	return v, nil
}

func queryString(r *http.Request, name, fallback string) string {
	if raw := r.URL.Query().Get(name); raw != "" {
		return raw
	}
	return fallback
}

func queryBool(r *http.Request, name string, fallback bool) (bool, error) {
	raw := r.URL.Query().Get(name)
	if raw == "" {
		return fallback, nil
	}
	v, err := strconv.ParseBool(raw)
	if err != nil {
		return false, rigerr.BadRequest("%s must be true or false", name)
	}
	return v, nil
}

func queryUUID(r *http.Request, name string) (uuid.UUID, error) {
	raw := r.URL.Query().Get(name)
	if raw == "" {
		return uuid.Nil, nil
	}
	v, err := uuid.Parse(raw)
	if err != nil {
		return uuid.Nil, rigerr.BadRequest("%s is not a valid identifier", name)
	}
	return v, nil
}

func queryTime(r *http.Request, name string) (time.Time, error) {
	raw := r.URL.Query().Get(name)
	if raw == "" {
		return time.Time{}, nil
	}
	v, err := time.Parse(time.RFC3339, raw)
	if err != nil {
		return time.Time{}, rigerr.BadRequest("%s must be an RFC 3339 timestamp", name)
	}
	return v, nil
}
