// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/simonjanss/rig/examples/todo/internal/model"
	"github.com/simonjanss/rig/files"
	"github.com/simonjanss/rig/files/filehttp"
	"github.com/simonjanss/rig/runtime/idempotency"
	"github.com/simonjanss/rig/runtime/reqlog"
)

// registerTodo mounts Todo's routes.
func registerTodo(mux *http.ServeMux, s Server, svc TodoService) {
	mux.HandleFunc("GET /api/v1/todos", handleListTodos(s, svc))
	mux.HandleFunc("POST /api/v1/todos", handleCreateTodo(s, svc))
	mux.HandleFunc("QUERY /api/v1/todos", handleSearchTodos(s, svc))
	mux.HandleFunc("POST /api/v1/todos/_search", handleSearchTodos(s, svc))
	mux.HandleFunc("GET /api/v1/todos/_deleted", handleListDeletedTodos(s, svc))
	mux.HandleFunc("DELETE /api/v1/todos/{id}", handleDeleteTodo(s, svc))
	mux.HandleFunc("GET /api/v1/todos/{id}", handleGetTodo(s, svc))
	mux.HandleFunc("PATCH /api/v1/todos/{id}", handleUpdateTodo(s, svc))
	mux.HandleFunc("POST /api/v1/todos/{id}/_complete", handleCompleteTodo(s, svc))
	mux.HandleFunc("POST /api/v1/todos/{id}/_restore", handleRestoreTodo(s, svc))
	mux.HandleFunc("POST /api/v1/todos/{id}/_revert", handleRevertTodo(s, svc))
	mux.HandleFunc("GET /api/v1/todos/{id}/_versions", handleVersionsOfTodo(s, svc))
	mux.HandleFunc("DELETE /api/v1/todos/{id}/cover-file", handleDeleteTodoCoverFile(s, svc))
	mux.HandleFunc("POST /api/v1/todos/{id}/cover-file", handleUploadTodoCoverFile(s, svc))
	mux.HandleFunc("GET /api/v1/todos/{id}/cover-file/{fileId}/{filename}", handleDownloadTodoCoverFile(s, svc))
}

// handleListTodos serves GET /api/v1/todos.
//
// List Todos.
func handleListTodos(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var query TodoListQuery
		limitParam, err := queryInt(r, "limit", 50)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		query.Limit = limitParam
		offsetParam, err := queryInt(r, "offset", 0)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		query.Offset = offsetParam

		req := NewRequest(claims, struct{}{}, query, struct{}{}, rc)

		out, err := svc.List(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeJSON(w, http.StatusOK, out)
	}
}

// handleCreateTodo serves POST /api/v1/todos.
//
// Create a Todo.
func handleCreateTodo(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var body model.TodoCreateInput
		var pending []*files.Pending
		if filehttp.IsMultipart(r) {
			filehttp.Deadline(w, filehttp.DefaultDeadline)
			form, err := filehttp.ReadForm(r)
			if err != nil {
				fail(s, w, r, rc, err)
				return
			}

			for {
				part, err := form.Next()
				if errors.Is(err, io.EOF) {
					break
				}
				if err != nil {
					fail(s, w, r, rc, err)
					return
				}

				switch part.Name {
				case filehttp.JSONPart:
					// The same body the JSON form carries, through the same decoder, so an unknown
					// key is refused here exactly as it is there and a 422 comes back with the
					// same field errors.
					if err := decodeReader(part.Body, &body); err != nil {
						fail(s, w, r, rc, err)
						return
					}
				case "coverFile":
					p, err := svc.Files().Prepare(ctx, part.Name, files.AttachRequest{
						TenantID: claims.TenantID,
						Upload:   part.Upload(),
					})
					if err != nil {
						fail(s, w, r, rc, err)
						return
					}
					pending = append(pending, p)
				default:
					// Refused rather than skipped, for the reason an unknown JSON key is refused:
					// a client that misspelled a part name has uploaded a file into nowhere, and a
					// 201 would tell it that worked.
					fail(s, w, r, rc, filehttp.ErrUnknownPart(part.Name))
					return
				}
			}

		} else if err := decodeBody(r, &body); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		req := NewRequest(claims, struct{}{}, struct{}{}, body, rc)

		result, err := idempotency.Run(ctx, s.DB, idempotency.Request{
			TenantID: claims.TenantID,
			Key:      r.Header.Get("Idempotency-Key"),
			// The route pattern rather than the path, so the same key against the same
			// endpoint is one record however many rows it names. What the path said is in
			// the fingerprint.
			Endpoint:    rc.Route,
			Fingerprint: idempotency.Fingerprint([]any{struct{}{}, struct{}{}, body}),
			RequestID:   rc.RequestID,
		}, func(ctx context.Context) (int, any, error) {
			out, err := svc.Create(ctx, req, pending)
			return http.StatusCreated, out, err
		})
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeResult(w, result)
	}
}

// handleSearchTodos serves QUERY /api/v1/todos.
//
// Search Todos with filters.
func handleSearchTodos(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var query TodoSearchQuery
		limitParam, err := queryInt(r, "limit", 50)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		query.Limit = limitParam
		offsetParam, err := queryInt(r, "offset", 0)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		query.Offset = offsetParam

		var body TodoSearchBody
		if err := decodeBody(r, &body); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		req := NewRequest(claims, struct{}{}, query, body, rc)

		out, err := svc.Search(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeJSON(w, http.StatusOK, out)
	}
}

// handleListDeletedTodos serves GET /api/v1/todos/_deleted.
//
// List retired Todos.
//
// A deletion stamps the row rather than removing it, so this is what was
// deleted and can still be brought back. Only rows inside the 30-day restore
// window appear: past it a row is gone as far as anyone is concerned, so it is
// not in the trash either.
func handleListDeletedTodos(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var query TodoListDeletedQuery
		limitParam, err := queryInt(r, "limit", 50)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		query.Limit = limitParam
		offsetParam, err := queryInt(r, "offset", 0)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		query.Offset = offsetParam

		req := NewRequest(claims, struct{}{}, query, struct{}{}, rc)

		out, err := svc.ListDeleted(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeJSON(w, http.StatusOK, out)
	}
}

// handleDeleteTodo serves DELETE /api/v1/todos/{id}.
//
// Delete a Todo.
//
// The row is retired by stamping a deletion time; it stops appearing in reads
// but can be restored within the retention window.
func handleDeleteTodo(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var path TodoDeletePath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		req := NewRequest(claims, path, struct{}{}, struct{}{}, rc)

		if err := svc.Delete(ctx, req); err != nil {
			fail(s, w, r, rc, err)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleGetTodo serves GET /api/v1/todos/{id}.
//
// Fetch one Todo by identifier.
func handleGetTodo(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var path TodoGetPath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		req := NewRequest(claims, path, struct{}{}, struct{}{}, rc)

		out, err := svc.Get(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeJSON(w, http.StatusOK, out)
	}
}

// handleUpdateTodo serves PATCH /api/v1/todos/{id}.
//
// Update a Todo.
//
// Only the fields present in the body are changed. A field set to null is
// cleared; a field left out is left alone.
func handleUpdateTodo(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var path TodoUpdatePath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		var body model.TodoUpdateInput
		if err := decodeBody(r, &body); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		req := NewRequest(claims, path, struct{}{}, body, rc)

		result, err := idempotency.Run(ctx, s.DB, idempotency.Request{
			TenantID: claims.TenantID,
			Key:      r.Header.Get("Idempotency-Key"),
			// The route pattern rather than the path, so the same key against the same
			// endpoint is one record however many rows it names. What the path said is in
			// the fingerprint.
			Endpoint:    rc.Route,
			Fingerprint: idempotency.Fingerprint([]any{path, struct{}{}, body}),
			RequestID:   rc.RequestID,
		}, func(ctx context.Context) (int, any, error) {
			out, err := svc.Update(ctx, req)
			return http.StatusOK, out, err
		})
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeResult(w, result)
	}
}

// handleCompleteTodo serves POST /api/v1/todos/{id}/_complete.
//
// Mark the task as done.
//
// Completing a task that is already done is a conflict rather than a no-op:
// two people ticking the same box should not both be told they were the one
// who finished it.
func handleCompleteTodo(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var path TodoCompletePath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		var body TodoCompleteBody
		if err := decodeBody(r, &body); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		req := NewRequest(claims, path, struct{}{}, body, rc)

		result, err := idempotency.Run(ctx, s.DB, idempotency.Request{
			TenantID: claims.TenantID,
			Key:      r.Header.Get("Idempotency-Key"),
			// The route pattern rather than the path, so the same key against the same
			// endpoint is one record however many rows it names. What the path said is in
			// the fingerprint.
			Endpoint:    rc.Route,
			Fingerprint: idempotency.Fingerprint([]any{path, struct{}{}, body}),
			RequestID:   rc.RequestID,
		}, func(ctx context.Context) (int, any, error) {
			out, err := svc.Complete(ctx, req)
			return http.StatusOK, out, err
		})
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeResult(w, result)
	}
}

// handleRestoreTodo serves POST /api/v1/todos/{id}/_restore.
//
// Bring a retired Todo back.
//
// The deletion stamp is cleared and the row appears in reads again. It works
// for 30 days after the deletion; past that the row is no longer eligible and
// this answers 409.
//
// Restoring a row that was never deleted is not an error. It is already in the
// state the caller asked for, and answering otherwise would make a retry of a
// request whose response went missing look like a failure.
//
// The request carries no fields. What to do when the world has moved on while
// the row was retired — a unique value taken by something created since —
// is the application's decision, and it is made in the restore hook: refuse,
// or change the row so that it fits.
//
// Every rule then runs against whatever the hook settled on, not only the ones
// for fields it touched. The row was not live, so nothing about it has been
// checked against the world it is returning to.
func handleRestoreTodo(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var path TodoRestorePath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		req := NewRequest(claims, path, struct{}{}, struct{}{}, rc)

		result, err := idempotency.Run(ctx, s.DB, idempotency.Request{
			TenantID: claims.TenantID,
			Key:      r.Header.Get("Idempotency-Key"),
			// The route pattern rather than the path, so the same key against the same
			// endpoint is one record however many rows it names. What the path said is in
			// the fingerprint.
			Endpoint:    rc.Route,
			Fingerprint: idempotency.Fingerprint([]any{path, struct{}{}, struct{}{}}),
			RequestID:   rc.RequestID,
		}, func(ctx context.Context) (int, any, error) {
			out, err := svc.Restore(ctx, req)
			return http.StatusOK, out, err
		})
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeResult(w, result)
	}
}

// handleRevertTodo serves POST /api/v1/todos/{id}/_revert.
//
// Put a Todo back to one of its previous versions.
//
// The version is replayed through the ordinary update path rather than written
// over the row, so the state being replaced is itself snapshotted first and
// every rule an update runs still runs. Reverting is undoable, and a value
// that would be refused now is still refused.
func handleRevertTodo(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var path TodoRevertPath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		var body TodoRevertBody
		if err := decodeBody(r, &body); err != nil {
			fail(s, w, r, rc, err)
			return
		}

		req := NewRequest(claims, path, struct{}{}, body, rc)

		result, err := idempotency.Run(ctx, s.DB, idempotency.Request{
			TenantID: claims.TenantID,
			Key:      r.Header.Get("Idempotency-Key"),
			// The route pattern rather than the path, so the same key against the same
			// endpoint is one record however many rows it names. What the path said is in
			// the fingerprint.
			Endpoint:    rc.Route,
			Fingerprint: idempotency.Fingerprint([]any{path, struct{}{}, body}),
			RequestID:   rc.RequestID,
		}, func(ctx context.Context) (int, any, error) {
			out, err := svc.Revert(ctx, req)
			return http.StatusOK, out, err
		})
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeResult(w, result)
	}
}

// handleVersionsOfTodo serves GET /api/v1/todos/{id}/_versions.
//
// List a Todo's previous versions.
//
// Every update copies the row as it was before writing the change, so this is
// the row's history: newest first, and never the live row itself.
//
// These do not appear in ordinary reads. A version answers Get by its own
// identifier, but it is filtered out of List and Search, so history does not
// turn up in a listing.
func handleVersionsOfTodo(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var path TodoVersionsPath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		req := NewRequest(claims, path, struct{}{}, struct{}{}, rc)

		out, err := svc.Versions(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeJSON(w, http.StatusOK, out)
	}
}

// handleDeleteTodoCoverFile serves DELETE /api/v1/todos/{id}/cover-file.
//
// Remove a Todo's cover.
//
// The column is cleared and the file is retired. Its bytes outlive the delete
// for as long as the file restore window, because a restore inside that window
// has to hand back a row pointing at something.
func handleDeleteTodoCoverFile(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var path TodoDeleteCoverFilePath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		req := NewRequest(claims, path, struct{}{}, struct{}{}, rc)

		if err := svc.DeleteCoverFile(ctx, req); err != nil {
			fail(s, w, r, rc, err)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleUploadTodoCoverFile serves POST /api/v1/todos/{id}/cover-file.
//
// Attach a file to a Todo as its cover.
//
// The form carries one part, named coverFile. Nothing else in it is accepted.
//
// The type is sniffed from the bytes rather than taken from what the request
// claimed, and the sniffed type is what is stored and what a download
// announces. A file replacing an existing one does not delete it: a row that
// keeps its previous versions still points at the old file from every one of
// them.
func handleUploadTodoCoverFile(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var path TodoUploadCoverFilePath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam

		filehttp.Deadline(w, filehttp.DefaultDeadline)
		body, err := filehttp.OnePart(r, "coverFile")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}

		req := NewRequest(claims, path, struct{}{}, body, rc)
		out, err := svc.UploadCoverFile(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		writeJSON(w, http.StatusCreated, out)
	}
}

// handleDownloadTodoCoverFile serves GET
// /api/v1/todos/{id}/cover-file/{fileId}/{filename}.
//
// Fetch a Todo's cover.
//
// Answers range and conditional requests, so a resumed download does not start
// over and a media element can seek.
func handleDownloadTodoCoverFile(s Server, svc TodoService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := reqlog.Wrap(w)
		w = rec

		ctx, claims, rc, ok := prepare(s, w, r)
		defer logRequest(s, r, rec, rc)
		if !ok {
			return
		}

		var path TodoDownloadCoverFilePath
		idParam, err := pathUUID(r, "id")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.ID = idParam
		fileIDParam, err := pathUUID(r, "fileId")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.FileID = fileIDParam
		filenameParam, err := pathString(r, "filename")
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		path.Filename = filenameParam

		filehttp.Deadline(w, filehttp.DefaultDeadline)
		req := NewRequest(claims, path, struct{}{}, struct{}{}, rc)

		content, err := svc.DownloadCoverFile(ctx, req)
		if err != nil {
			fail(s, w, r, rc, err)
			return
		}
		defer content.Body.Close()

		// ServeContent from here, so a range request and a conditional request are
		// answered rather than ignored: a resumed download does not start over and a
		// media element can seek.
		filehttp.Serve(w, r, content, svc.Files().InlineTypes())
	}
}
