// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"context"

	"github.com/google/uuid"
	"github.com/simonjanss/rig/examples/todo/internal/model"
	"github.com/simonjanss/rig/examples/todo/internal/store"
	"github.com/simonjanss/rig/runtime/dbhook"
	"github.com/simonjanss/rig/runtime/rigerr"
	"github.com/simonjanss/rig/runtime/tenancy"
)

// TodoService is the interface your service layer implements.
//
// Embedding DefaultTodoService satisfies all of it, so a resource with no
// business logic needs nothing but a constructor. Override a method to add a
// rule and delegate to the embedded default for the rest.
type TodoService interface {
	// List Todos.
	List(ctx context.Context, r Request[struct{}, TodoListQuery, struct{}]) (*TodoListResponse, error)

	// Create a Todo.
	Create(ctx context.Context, r Request[struct{}, struct{}, model.TodoCreateInput]) (*model.Todo, error)

	// Search Todos with filters.
	Search(ctx context.Context, r Request[struct{}, TodoSearchQuery, TodoSearchBody]) (*TodoListResponse, error)

	// List retired Todos.
	//
	// A deletion stamps the row rather than removing it, so this is what was
	// deleted and can still be brought back. Only rows inside the 30-day restore
	// window appear: past it a row is gone as far as anyone is concerned, so it is
	// not in the trash either.
	ListDeleted(ctx context.Context, r Request[struct{}, TodoListDeletedQuery, struct{}]) (*TodoListResponse, error)

	// Delete a Todo.
	//
	// The row is retired by stamping a deletion time; it stops appearing in reads
	// but can be restored within the retention window.
	Delete(ctx context.Context, r Request[TodoDeletePath, struct{}, struct{}]) error

	// Fetch one Todo by identifier.
	Get(ctx context.Context, r Request[TodoGetPath, struct{}, struct{}]) (*model.Todo, error)

	// Update a Todo.
	//
	// Only the fields present in the body are changed. A field set to null is
	// cleared; a field left out is left alone.
	Update(ctx context.Context, r Request[TodoUpdatePath, struct{}, model.TodoUpdateInput]) (*model.Todo, error)

	// Mark the task as done.
	//
	// Completing a task that is already done is a conflict rather than a no-op:
	// two people ticking the same box should not both be told they were the one
	// who finished it.
	Complete(ctx context.Context, r Request[TodoCompletePath, struct{}, TodoCompleteBody]) (*model.Todo, error)

	// Bring a retired Todo back.
	//
	// The deletion stamp is cleared and the row appears in reads again. It works
	// for 30 days after the deletion; past that the row is no longer eligible and
	// this answers 409.
	//
	// Restoring a row that was never deleted is not an error. It is already in the
	// state the caller asked for, and answering otherwise would make a retry of a
	// request whose response went missing look like a failure.
	//
	// The request carries no fields. What to do when the world has moved on while
	// the row was retired — a unique value taken by something created since —
	// is the application's decision, and it is made in the restore hook: refuse,
	// or change the row so that it fits.
	//
	// Every rule then runs against whatever the hook settled on, not only the ones
	// for fields it touched. The row was not live, so nothing about it has been
	// checked against the world it is returning to.
	Restore(ctx context.Context, r Request[TodoRestorePath, struct{}, struct{}]) (*model.Todo, error)

	// Put a Todo back to one of its previous versions.
	//
	// The version is replayed through the ordinary update path rather than written
	// over the row, so the state being replaced is itself snapshotted first and
	// every rule an update runs still runs. Reverting is undoable, and a value
	// that would be refused now is still refused.
	Revert(ctx context.Context, r Request[TodoRevertPath, struct{}, TodoRevertBody]) (*model.Todo, error)

	// List a Todo's previous versions.
	//
	// Every update copies the row as it was before writing the change, so this is
	// the row's history: newest first, and never the live row itself.
	//
	// These do not appear in ordinary reads. A version answers Get by its own
	// identifier, but it is filtered out of List and Search, so history does not
	// turn up in a listing.
	Versions(ctx context.Context, r Request[TodoVersionsPath, struct{}, struct{}]) (*TodoListResponse, error)
}

// TodoWriter writes a Todo with the service's rules attached.
//
// Every write rig generates goes through it, and so should every write a
// custom endpoint makes: reaching for the repository directly means passing
// the hooks by hand, and forgetting once is a second way into the table where
// the rules do not run.
type TodoWriter struct {
	repo  store.TodoRepository
	hooks TodoHooks
}

// NewTodoWriter pairs a repository with the rules that apply to it.
func NewTodoWriter(repo store.TodoRepository, hooks TodoHooks) TodoWriter {
	return TodoWriter{repo: repo, hooks: hooks}
}

// Create inserts a row, running the create rules and hooks.
func (w TodoWriter) Create(ctx context.Context, in model.TodoCreateInput) (*model.Todo, error) {
	return w.repo.Create(ctx, dbhook.Create[model.TodoCreateInput, model.Todo]{Input: in, Hooks: w.hooks.Create})
}

// Update changes a row, running the update rules and hooks.
func (w TodoWriter) Update(ctx context.Context, id uuid.UUID, in model.TodoUpdateInput) (*model.Todo, error) {
	return w.repo.Update(ctx, id, dbhook.Update[model.TodoUpdateInput, model.Todo]{Input: in, Hooks: w.hooks.Update})
}

// Delete removes a row, running the delete hooks.
func (w TodoWriter) Delete(ctx context.Context, in model.TodoDeleteInput) error {
	return w.repo.Delete(ctx, dbhook.Delete[model.TodoDeleteInput, model.Todo]{Input: in, Hooks: w.hooks.Delete})
}

// Restore brings a retired row back, running the restore hooks. The input
// starts empty: what a row has to change to be allowed back is the hook's
// decision, not the caller's.
func (w TodoWriter) Restore(ctx context.Context, id uuid.UUID) (*model.Todo, error) {
	return w.repo.Restore(ctx, id, dbhook.Restore[model.TodoUpdateInput, model.Todo]{Hooks: w.hooks.Restore})
}

// Revert replays a previous version, running the update rules and hooks —
// because that is what it is.
func (w TodoWriter) Revert(ctx context.Context, id, versionID uuid.UUID) (*model.Todo, error) {
	return w.repo.Revert(ctx, id, versionID, w.hooks.Update)
}

// DefaultTodoService implements every operation.
//
// The generated ones it answers itself, by calling the repository. A custom
// endpoint it hands to the contract, which is where the only implementation
// there could be lives.
type DefaultTodoService struct {
	repo     store.TodoRepository
	contract TodoContract
	// write is the same writer a custom endpoint gets through Writer, so the
	// generated operations and the hand-written ones take one path.
	write TodoWriter
}

// TodoContract is what the service layer owes Todo: everything about it the
// schema cannot describe.
//
// The members are optional in the sense that an empty one runs nothing. None
// of them is optional in the sense of being skippable: the constructor takes
// this value, so a resource with no rules has an empty literal somebody can
// read rather than an absence nobody can see.
type TodoContract struct {
	// Hooks is everything that happens around a write: the rules it is checked
	// against, and the callbacks that run with it. One set per operation, because
	// the rules for creating a row and for changing one are different questions
	// asked about different fields.
	Hooks TodoHooks

	// Endpoints holds the operations the configuration declared and rig cannot
	// write. It is required, because a resource that declares one has no working
	// answer without it.
	Endpoints TodoEndpoints
}

// TodoEndpoints are the endpoints the table configuration declares.
//
// There is nothing sensible for rig to do by default with any of them — an
// endpoint nobody could describe from the schema is exactly the one that has
// to be written — so the whole set is the service layer's, and it arrives
// through the contract.
type TodoEndpoints interface {
	// Mark the task as done.
	//
	// Completing a task that is already done is a conflict rather than a no-op:
	// two people ticking the same box should not both be told they were the one
	// who finished it.
	Complete(ctx context.Context, r Request[TodoCompletePath, struct{}, TodoCompleteBody]) (*model.Todo, error)
}

// TodoHooks are the callbacks that run around each generated write.
//
// Before and After run inside the write's transaction, so returning an error
// from either undoes the write. AfterCommit runs once it has landed, which is
// where anything outside the database belongs.
type TodoHooks struct {
	// Read shapes what a read answers with. It is the one set that is not about a
	// write, and the only one that runs outside the repository — a write reads
	// the row it is about to change, and narrowing that read would have the update
	// judge a row that is not the stored one.
	Read dbhook.ReadHooks[model.TodoFilter, model.Todo]

	Create dbhook.CreateHooks[model.TodoCreateInput, model.Todo]
	Update dbhook.UpdateHooks[model.TodoUpdateInput, model.Todo]
	Delete dbhook.DeleteHooks[model.TodoDeleteInput, model.Todo]
	// Restore takes the update input, because a restore may have to change the row
	// to be allowed back at all.
	Restore dbhook.RestoreHooks[model.TodoUpdateInput, model.Todo]
}

// TodoRules is everything the service layer supplies about Todo.
//
// Implement it on a type of your own and hand it to NewTodoService. It is an
// interface rather than a struct so that the rules and the endpoints are one
// value: a resource whose configuration declares an endpoint cannot be wired
// up without an implementation of it, and the failure is at the call to the
// constructor rather than on the route.
type TodoRules interface {
	// The endpoints the table configuration declares, which rig has no way to
	// write.
	TodoEndpoints

	// Hooks is everything that happens around a write, plus what a read answers
	// with. It is called once, during construction.
	Hooks() TodoHooks

	// Bind receives the writer built from those hooks, so a custom endpoint can
	// write through the same path a generated operation does.
	//
	// It is in the interface rather than looked for, so a service that never
	// writes says so with an empty body instead of finding out at runtime that a
	// misspelled method left it without one. rig calls it once, before anything
	// can reach a hook.
	Bind(TodoWriter)
}

// NewTodoService is the front door.
//
// It asks the rules what they are, builds the writer from that, and hands the
// writer back. The service layer never has to hold a half-built value or name
// the type it is part of.
func NewTodoService(repo store.TodoRepository, rules TodoRules) DefaultTodoService {
	svc := NewDefaultTodoService(repo, TodoContract{Hooks: rules.Hooks(), Endpoints: rules})
	rules.Bind(svc.Writer())
	return svc
}

// NewDefaultTodoService builds the default implementation.
//
// The contract is a parameter rather than a field left to default, because a
// rule nobody attached is a rule that does not run, and nothing at the call
// site would have said so. An empty TodoContract is still allowed — it is
// just a thing somebody wrote down.
func NewDefaultTodoService(repo store.TodoRepository, contract TodoContract) DefaultTodoService {
	// A nil set is not a service with no custom endpoints; it is one whose custom
	// endpoints all answer 500. Failing at startup beats finding that out from a
	// caller.
	if contract.Endpoints == nil {
		panic("api.NewDefaultTodoService: Contract.Endpoints is required: todo declares custom endpoints")
	}

	return DefaultTodoService{repo: repo, contract: contract, write: NewTodoWriter(repo, contract.Hooks)}
}

// Writer is how a custom endpoint writes.
//
// It is the repository with this service's own rules already attached, so a
// hand-written endpoint takes the path a generated one takes. Reaching for the
// repository instead means passing the hooks by hand, and forgetting once is a
// second way into the table where the rules do not run.
//
// It is a method rather than something the service layer holds because there
// is then nothing to wire, and nothing to wire wrongly.
func (s DefaultTodoService) Writer() TodoWriter { return s.write }

// readFilter combines the caller's filter with whatever the read hook narrows
// to.
//
// Nested rather than merged, because the two are combined with AND: a caller
// whose own filter is an OR cannot widen its way out of the one the service
// added.
func (s DefaultTodoService) readFilter(ctx context.Context, claims tenancy.Claims, asked model.TodoFilter) (model.TodoFilter, error) {
	if s.contract.Hooks.Read.Narrow == nil {
		return asked, nil
	}

	narrowed, err := s.contract.Hooks.Read.Narrow(ctx, caller(claims))
	if err != nil {
		return asked, err
	}
	if narrowed == nil {
		return asked, nil
	}

	return model.TodoFilter{NestedFilters: []model.TodoFilter{*narrowed, asked}}, nil
}

// readRows runs the read hook over what a read is about to answer with.
func (s DefaultTodoService) readRows(ctx context.Context, claims tenancy.Claims, rows []*model.Todo) error {
	if s.contract.Hooks.Read.Rows == nil {
		return nil
	}
	return s.contract.Hooks.Read.Rows(ctx, caller(claims), rows)
}

// List implements TodoService.
func (s DefaultTodoService) List(ctx context.Context, r Request[struct{}, TodoListQuery, struct{}]) (*TodoListResponse, error) {
	page := model.TodoPage{Limit: r.Query.Limit, Offset: r.Query.Offset}
	asked := model.NewTodoFilter()
	filter, err := s.readFilter(ctx, r.Claims, asked)
	if err != nil {
		return nil, err
	}

	rows, total, err := s.repo.List(ctx, filter, page)
	if err != nil {
		return nil, err
	}
	if err := s.readRows(ctx, r.Claims, rows); err != nil {
		return nil, err
	}

	return &TodoListResponse{
		Data:       rows,
		Pagination: Pagination{Offset: page.Offset, Limit: page.Limit, Total: total},
	}, nil
}

// Create implements TodoService.
func (s DefaultTodoService) Create(ctx context.Context, r Request[struct{}, struct{}, model.TodoCreateInput]) (*model.Todo, error) {
	return s.write.Create(ctx, r.Body)
}

// Search implements TodoService.
func (s DefaultTodoService) Search(ctx context.Context, r Request[struct{}, TodoSearchQuery, TodoSearchBody]) (*TodoListResponse, error) {
	page := model.TodoPage{Limit: r.Query.Limit, Offset: r.Query.Offset}
	asked := r.Body.Filter
	filter, err := s.readFilter(ctx, r.Claims, asked)
	if err != nil {
		return nil, err
	}

	rows, total, err := s.repo.List(ctx, filter, page)
	if err != nil {
		return nil, err
	}
	if err := s.readRows(ctx, r.Claims, rows); err != nil {
		return nil, err
	}

	return &TodoListResponse{
		Data:       rows,
		Pagination: Pagination{Offset: page.Offset, Limit: page.Limit, Total: total},
	}, nil
}

// ListDeleted implements TodoService.
func (s DefaultTodoService) ListDeleted(ctx context.Context, r Request[struct{}, TodoListDeletedQuery, struct{}]) (*TodoListResponse, error) {
	page := model.TodoPage{Limit: r.Query.Limit, Offset: r.Query.Offset}
	filter, err := s.readFilter(ctx, r.Claims, model.NewTodoFilter())
	if err != nil {
		return nil, err
	}

	rows, total, err := s.repo.ListDeleted(ctx, filter, page)
	if err != nil {
		return nil, err
	}
	if err := s.readRows(ctx, r.Claims, rows); err != nil {
		return nil, err
	}

	return &TodoListResponse{
		Data:       rows,
		Pagination: Pagination{Offset: page.Offset, Limit: page.Limit, Total: total},
	}, nil
}

// Delete implements TodoService.
func (s DefaultTodoService) Delete(ctx context.Context, r Request[TodoDeletePath, struct{}, struct{}]) error {
	return s.write.Delete(ctx, model.TodoDeleteInput{ID: r.Path.ID})
}

// Get implements TodoService.
func (s DefaultTodoService) Get(ctx context.Context, r Request[TodoGetPath, struct{}, struct{}]) (*model.Todo, error) {
	row, err := s.repo.Get(ctx, r.Path.ID)
	if err != nil {
		return nil, err
	}

	// Not narrowed: Get fetches by primary key, and there is no filter to add a
	// condition to. A rule about whether this caller may have this row belongs in
	// Rows, which is handed it.
	if err := s.readRows(ctx, r.Claims, []*model.Todo{row}); err != nil {
		return nil, err
	}
	return row, nil
}

// Update implements TodoService.
func (s DefaultTodoService) Update(ctx context.Context, r Request[TodoUpdatePath, struct{}, model.TodoUpdateInput]) (*model.Todo, error) {
	return s.write.Update(ctx, r.Path.ID, r.Body)
}

// Complete implements TodoService.
func (s DefaultTodoService) Complete(ctx context.Context, r Request[TodoCompletePath, struct{}, TodoCompleteBody]) (*model.Todo, error) {
	if s.contract.Endpoints == nil {
		return nil, rigerr.Internal(nil, "Todo.Complete has no implementation")
	}
	return s.contract.Endpoints.Complete(ctx, r)
}

// Restore implements TodoService.
func (s DefaultTodoService) Restore(ctx context.Context, r Request[TodoRestorePath, struct{}, struct{}]) (*model.Todo, error) {
	return s.write.Restore(ctx, r.Path.ID)
}

// Revert implements TodoService.
func (s DefaultTodoService) Revert(ctx context.Context, r Request[TodoRevertPath, struct{}, TodoRevertBody]) (*model.Todo, error) {
	return s.write.Revert(ctx, r.Path.ID, r.Body.VersionID)
}

// Versions implements TodoService.
func (s DefaultTodoService) Versions(ctx context.Context, r Request[TodoVersionsPath, struct{}, struct{}]) (*TodoListResponse, error) {
	if _, err := s.repo.Get(ctx, r.Path.ID); err != nil {
		return nil, err
	}

	versions, err := s.repo.ListSnapshots(ctx, r.Path.ID)
	if err != nil {
		return nil, err
	}
	if err := s.readRows(ctx, r.Claims, versions); err != nil {
		return nil, err
	}

	// A history is not paged: the whole of it comes back, and the pagination block
	// says exactly that rather than describing a page nobody asked for.
	return &TodoListResponse{
		Data:       versions,
		Pagination: Pagination{Limit: len(versions), Total: int64(len(versions))},
	}, nil
}
