// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"github.com/simonjanss/rig/authmodel"
)

// What an account is.
//
// An alias for [github.com/simonjanss/rig/authmodel.AccountKind]: rig's schema
// declared the type, so rig declares the Go for it.
type AccountKind = authmodel.AccountKind

// The values of AccountKind.
const (
	AccountKindPerson  = authmodel.AccountKindPerson
	AccountKindService = authmodel.AccountKindService
)

// AllAccountKind is every value, in declaration order.
var AllAccountKind = authmodel.AllAccountKind

// ParseAccountKind reads a value, accepting any casing and surrounding space.
// A name rather than a method, so unlike Valid and String it does not come
// with the type.
var ParseAccountKind = authmodel.ParseAccountKind
