// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// Exact-match conditions on Account fields.
type AccountFilterEquals struct {
	// Unique identifier for this row.
	ID *uuid.UUID `json:"id,omitempty"`
	// The person this account belongs to, or null for a service account, which is
	// nobody.
	IdentityID *uuid.UUID `json:"identityId,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *uuid.UUID `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *uuid.UUID `json:"deletedByAccountId,omitempty"`
	// Whether this is a person or a service account an integration acts as.
	Kind *RigAccountKind `json:"kind,omitempty"`
	// The coarse level in this tenant: Owner, Admin, or Basic. Somebody can be an
	// Owner here and Basic elsewhere.
	Role *RigAccountRoleLevel `json:"role,omitempty"`
	// A copy of the identity's address, kept here so listing accounts is one
	// query. For a service account it is a label nobody signs in with.
	EmailAddress *string `json:"emailAddress,omitempty"`
	// What to call the person in this tenant.
	DisplayName *string `json:"displayName,omitempty"`
	// IANA name, for example Europe/Stockholm. Null means UTC.
	TimeZone *string `json:"timeZone,omitempty"`
	// Whether the account may be used. A disabled account is refused with 403, not
	// 401.
	IsActive *bool `json:"isActive,omitempty"`
	// API key this row was created through, when it was an integration rather than
	// a person.
	CreatedByAPIKeyID *uuid.UUID `json:"createdByApiKeyId,omitempty"`
	// API key this row was last updated through, when it was an integration rather
	// than a person.
	UpdatedByAPIKeyID *uuid.UUID `json:"updatedByApiKeyId,omitempty"`
	// API key this row was soft-deleted through, when it was an integration rather
	// than a person.
	DeletedByAPIKeyID *uuid.UUID `json:"deletedByApiKeyId,omitempty"`
	// Conditions on one of this row's AssigneeAccountTodos.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.AssigneeAccountTodos asks the second.
	AssigneeAccountTodos *TodoFilterEquals `json:"assigneeAccountTodos,omitempty"`
}

// Ordering conditions on Account fields that can be compared.
type AccountFilterRange struct {
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// Conditions on one of this row's AssigneeAccountTodos.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.AssigneeAccountTodos asks the second.
	AssigneeAccountTodos *TodoFilterRange `json:"assigneeAccountTodos,omitempty"`
}

// Set-membership conditions on Account fields.
type AccountFilterContains struct {
	// Unique identifier for this row.
	ID []uuid.UUID `json:"id,omitempty"`
	// The person this account belongs to, or null for a service account, which is
	// nobody.
	IdentityID []uuid.UUID `json:"identityId,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt []time.Time `json:"createdAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID []uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt []time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID []uuid.UUID `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt []time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID []uuid.UUID `json:"deletedByAccountId,omitempty"`
	// Whether this is a person or a service account an integration acts as.
	Kind []RigAccountKind `json:"kind,omitempty"`
	// The coarse level in this tenant: Owner, Admin, or Basic. Somebody can be an
	// Owner here and Basic elsewhere.
	Role []RigAccountRoleLevel `json:"role,omitempty"`
	// A copy of the identity's address, kept here so listing accounts is one
	// query. For a service account it is a label nobody signs in with.
	EmailAddress []string `json:"emailAddress,omitempty"`
	// What to call the person in this tenant.
	DisplayName []string `json:"displayName,omitempty"`
	// IANA name, for example Europe/Stockholm. Null means UTC.
	TimeZone []string `json:"timeZone,omitempty"`
	// Whether the account may be used. A disabled account is refused with 403, not
	// 401.
	IsActive []bool `json:"isActive,omitempty"`
	// API key this row was created through, when it was an integration rather than
	// a person.
	CreatedByAPIKeyID []uuid.UUID `json:"createdByApiKeyId,omitempty"`
	// API key this row was last updated through, when it was an integration rather
	// than a person.
	UpdatedByAPIKeyID []uuid.UUID `json:"updatedByApiKeyId,omitempty"`
	// API key this row was soft-deleted through, when it was an integration rather
	// than a person.
	DeletedByAPIKeyID []uuid.UUID `json:"deletedByApiKeyId,omitempty"`
	// Conditions on one of this row's AssigneeAccountTodos.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.AssigneeAccountTodos asks the second.
	AssigneeAccountTodos *TodoFilterContains `json:"assigneeAccountTodos,omitempty"`
}

// Pattern conditions on Account text fields.
type AccountFilterLike struct {
	// A copy of the identity's address, kept here so listing accounts is one
	// query. For a service account it is a label nobody signs in with.
	EmailAddress *string `json:"emailAddress,omitempty"`
	// What to call the person in this tenant.
	DisplayName *string `json:"displayName,omitempty"`
	// IANA name, for example Europe/Stockholm. Null means UTC.
	TimeZone *string `json:"timeZone,omitempty"`
	// Conditions on one of this row's AssigneeAccountTodos.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.AssigneeAccountTodos asks the second.
	AssigneeAccountTodos *TodoFilterLike `json:"assigneeAccountTodos,omitempty"`
}

// Presence conditions on nullable Account fields.
type AccountFilterNull struct {
	// The person this account belongs to, or null for a service account, which is
	// nobody.
	IdentityID *bool `json:"identityId,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *bool `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *bool `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *bool `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *bool `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *bool `json:"deletedByAccountId,omitempty"`
	// IANA name, for example Europe/Stockholm. Null means UTC.
	TimeZone *bool `json:"timeZone,omitempty"`
	// API key this row was created through, when it was an integration rather than
	// a person.
	CreatedByAPIKeyID *bool `json:"createdByApiKeyId,omitempty"`
	// API key this row was last updated through, when it was an integration rather
	// than a person.
	UpdatedByAPIKeyID *bool `json:"updatedByApiKeyId,omitempty"`
	// API key this row was soft-deleted through, when it was an integration rather
	// than a person.
	DeletedByAPIKeyID *bool `json:"deletedByApiKeyId,omitempty"`
	// Conditions on one of this row's AssigneeAccountTodos.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.AssigneeAccountTodos asks the second.
	AssigneeAccountTodos *TodoFilterNull `json:"assigneeAccountTodos,omitempty"`
}

// Relations a Account must have no matching row for.
type AccountFilterWithout struct {
	// Match rows with no AssigneeAccountTodos satisfying these conditions,
	// including rows with none at all.
	//
	// This negates the existence of a matching row rather than the comparison,
	// which is the whole difference from NotEquals.AssigneeAccountTodos: that one
	// is satisfied by one of them differing, and a row can have one that differs
	// and one that matches at the same time. An empty object asks for rows with no
	// AssigneeAccountTodos at all.
	AssigneeAccountTodos *TodoFilter `json:"assigneeAccountTodos,omitempty"`
}

// Conditions a Account must satisfy to match a search.
type AccountFilter struct {
	// Fields that must equal the given value.
	Equals *AccountFilterEquals `json:"equals,omitempty"`
	// Fields that must not equal the given value.
	NotEquals *AccountFilterEquals `json:"notEquals,omitempty"`
	// Fields that must be greater than the given value.
	GreaterThan *AccountFilterRange `json:"greaterThan,omitempty"`
	// Fields that must be less than the given value.
	SmallerThan *AccountFilterRange `json:"smallerThan,omitempty"`
	// Fields that must be greater than or equal to the given value.
	GreaterOrEqual *AccountFilterRange `json:"greaterOrEqual,omitempty"`
	// Fields that must be less than or equal to the given value.
	SmallerOrEqual *AccountFilterRange `json:"smallerOrEqual,omitempty"`
	// Fields that must be one of the given values.
	Contains *AccountFilterContains `json:"contains,omitempty"`
	// Fields that must not be one of the given values.
	NotContains *AccountFilterContains `json:"notContains,omitempty"`
	// Text fields that must match the given pattern.
	Like *AccountFilterLike `json:"like,omitempty"`
	// Text fields that must not match the given pattern.
	NotLike *AccountFilterLike `json:"notLike,omitempty"`
	// Fields that must be null.
	Null *AccountFilterNull `json:"null,omitempty"`
	// Fields that must not be null.
	NotNull *AccountFilterNull `json:"notNull,omitempty"`
	// Combine this filter's conditions with OR instead of AND.
	OrCondition bool `json:"orCondition,omitempty"`
	// Sub-filters combined with this one, so that AND and OR can be mixed to any
	// depth.
	NestedFilters []AccountFilter `json:"nestedFilters,omitempty"`
	// Relations with no row matching the given conditions. An empty one asks for
	// no related row at all.
	//
	// This is where a negation belongs when what you mean is "not": it negates
	// whether a matching related row exists, so a row with no related row at all
	// satisfies it. The negative operators above negate the comparison instead and
	// still require the related row to be there — "no related row called X" is
	// here, "a related row not called X" is NotEquals.
	Without *AccountFilterWithout `json:"without,omitempty"`
}

// AccountPage says which slice of a result to return, and in what order.
//
// The zero value is the first page at the repository's default size, in the
// table's configured order, which is what a caller who has not thought about
// it wants.
type AccountPage struct {
	Limit  int
	Offset int

	// OrderBy replaces the table's default ordering.
	OrderBy []AccountOrder
}

// AccountOrder is one clause of an ordering.
//
// Relation names the relation the column belongs to, and is empty for this
// table's own columns. The repository turns it into a left join, so a row
// whose related row is missing still appears — at one end of the order
// rather than not at all.
type AccountOrder struct {
	Relation string
	Column   string
	Desc     bool
}

// The orderings a Account supports.
var (
	AccountOrderIDAsc                  = AccountOrder{Column: "id"}
	AccountOrderIDDesc                 = AccountOrder{Column: "id", Desc: true}
	AccountOrderTenantIDAsc            = AccountOrder{Column: "tenant_id"}
	AccountOrderTenantIDDesc           = AccountOrder{Column: "tenant_id", Desc: true}
	AccountOrderIdentityIDAsc          = AccountOrder{Column: "identity_id"}
	AccountOrderIdentityIDDesc         = AccountOrder{Column: "identity_id", Desc: true}
	AccountOrderCreatedAtAsc           = AccountOrder{Column: "created_at"}
	AccountOrderCreatedAtDesc          = AccountOrder{Column: "created_at", Desc: true}
	AccountOrderCreatedByAccountIDAsc  = AccountOrder{Column: "created_by_account_id"}
	AccountOrderCreatedByAccountIDDesc = AccountOrder{Column: "created_by_account_id", Desc: true}
	AccountOrderUpdatedAtAsc           = AccountOrder{Column: "updated_at"}
	AccountOrderUpdatedAtDesc          = AccountOrder{Column: "updated_at", Desc: true}
	AccountOrderUpdatedByAccountIDAsc  = AccountOrder{Column: "updated_by_account_id"}
	AccountOrderUpdatedByAccountIDDesc = AccountOrder{Column: "updated_by_account_id", Desc: true}
	AccountOrderDeletedAtAsc           = AccountOrder{Column: "deleted_at"}
	AccountOrderDeletedAtDesc          = AccountOrder{Column: "deleted_at", Desc: true}
	AccountOrderDeletedByAccountIDAsc  = AccountOrder{Column: "deleted_by_account_id"}
	AccountOrderDeletedByAccountIDDesc = AccountOrder{Column: "deleted_by_account_id", Desc: true}
	AccountOrderKindAsc                = AccountOrder{Column: "kind"}
	AccountOrderKindDesc               = AccountOrder{Column: "kind", Desc: true}
	AccountOrderRoleAsc                = AccountOrder{Column: "role"}
	AccountOrderRoleDesc               = AccountOrder{Column: "role", Desc: true}
	AccountOrderEmailAddressAsc        = AccountOrder{Column: "email_address"}
	AccountOrderEmailAddressDesc       = AccountOrder{Column: "email_address", Desc: true}
	AccountOrderDisplayNameAsc         = AccountOrder{Column: "display_name"}
	AccountOrderDisplayNameDesc        = AccountOrder{Column: "display_name", Desc: true}
	AccountOrderTimeZoneAsc            = AccountOrder{Column: "time_zone"}
	AccountOrderTimeZoneDesc           = AccountOrder{Column: "time_zone", Desc: true}
	AccountOrderIsActiveAsc            = AccountOrder{Column: "is_active"}
	AccountOrderIsActiveDesc           = AccountOrder{Column: "is_active", Desc: true}
	AccountOrderCreatedByAPIKeyIDAsc   = AccountOrder{Column: "created_by_api_key_id"}
	AccountOrderCreatedByAPIKeyIDDesc  = AccountOrder{Column: "created_by_api_key_id", Desc: true}
	AccountOrderUpdatedByAPIKeyIDAsc   = AccountOrder{Column: "updated_by_api_key_id"}
	AccountOrderUpdatedByAPIKeyIDDesc  = AccountOrder{Column: "updated_by_api_key_id", Desc: true}
	AccountOrderDeletedByAPIKeyIDAsc   = AccountOrder{Column: "deleted_by_api_key_id"}
	AccountOrderDeletedByAPIKeyIDDesc  = AccountOrder{Column: "deleted_by_api_key_id", Desc: true}
)

// NewAccountFilterEquals builds an empty AccountFilterEquals to fill in.
func NewAccountFilterEquals() *AccountFilterEquals { return &AccountFilterEquals{} }

// NewAccountFilterRange builds an empty AccountFilterRange to fill in.
func NewAccountFilterRange() *AccountFilterRange { return &AccountFilterRange{} }

// NewAccountFilterContains builds an empty AccountFilterContains to fill in.
func NewAccountFilterContains() *AccountFilterContains { return &AccountFilterContains{} }

// NewAccountFilterLike builds an empty AccountFilterLike to fill in.
func NewAccountFilterLike() *AccountFilterLike { return &AccountFilterLike{} }

// NewAccountFilterNull builds an empty AccountFilterNull to fill in.
func NewAccountFilterNull() *AccountFilterNull { return &AccountFilterNull{} }

// NewAccountFilterWithout builds an empty AccountFilterWithout to fill in.
func NewAccountFilterWithout() *AccountFilterWithout { return &AccountFilterWithout{} }

// NewAccountFilter builds an empty filter, which matches every row the caller
// is allowed to see.
func NewAccountFilter() AccountFilter { return AccountFilter{} }
