// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// Exact-match conditions on RigPresence fields.
type RigPresenceFilterEquals struct {
	// The row's identifier. Nothing references it: a client addresses its own
	// presence by session key, so this identifier never leaves the server except
	// on the stream.
	ID *uuid.UUID `json:"id,omitempty"`
	// Who is present. Read from the credential and never from a request body,
	// which is what makes "you may only write your own presence" a sentence a
	// client cannot phrase rather than a rule somebody enforces.
	AccountID *uuid.UUID `json:"accountId,omitempty"`
	// Which tab this is. The browser names itself, and the name points at nothing:
	// one sign-in can have several tabs, and each is present separately rather
	// than overwriting the others.
	SessionKey *string `json:"sessionKey,omitempty"`
	// When this tab first appeared. It deliberately does not move on a heartbeat,
	// so "joined four minutes ago" stays answerable.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// The last heartbeat. Not updated_at: this is not when the row was last
	// edited, it is the whole meaning of the row — whoever is reading decides
	// whether somebody is here by comparing it against the configured TTL.
	SeenAt *time.Time `json:"seenAt,omitempty"`
	// Which part of the application this presence is in, named by the application:
	// a board, a document, a tenant. It is what a subscriber narrows the stream
	// by, so it decides how much presence traffic one screen pays for.
	Scope *string `json:"scope,omitempty"`
	// The table the row being looked at is in, checked against this API's own
	// tables. Null means present in the scope without being on a particular row.
	TargetTable *string `json:"targetTable,omitempty"`
	// Which row. There is deliberately no foreign key, and this is the one place
	// rig accepts a polymorphic reference: nothing joins to a presence row,
	// nothing embeds one, and no client filters a list of them — so the
	// integrity a key would buy has no reader. A presence pointing at a row
	// somebody just deleted is not a bug, it is a row that will be gone before
	// anybody looks.
	TargetID *uuid.UUID `json:"targetId,omitempty"`
	// Which field, when the application tracks focus that finely. This is what
	// turns "Simon is on this issue" into "Simon is editing the title".
	TargetField *string `json:"targetField,omitempty"`
	// Whether they are looking or typing. Separate from target_field because a
	// client may know somebody is editing before it knows which control has focus.
	Activity *RigPresenceActivity `json:"activity,omitempty"`
}

// Ordering conditions on RigPresence fields that can be compared.
type RigPresenceFilterRange struct {
	// When this tab first appeared. It deliberately does not move on a heartbeat,
	// so "joined four minutes ago" stays answerable.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// The last heartbeat. Not updated_at: this is not when the row was last
	// edited, it is the whole meaning of the row — whoever is reading decides
	// whether somebody is here by comparing it against the configured TTL.
	SeenAt *time.Time `json:"seenAt,omitempty"`
}

// Set-membership conditions on RigPresence fields.
type RigPresenceFilterContains struct {
	// The row's identifier. Nothing references it: a client addresses its own
	// presence by session key, so this identifier never leaves the server except
	// on the stream.
	ID []uuid.UUID `json:"id,omitempty"`
	// Who is present. Read from the credential and never from a request body,
	// which is what makes "you may only write your own presence" a sentence a
	// client cannot phrase rather than a rule somebody enforces.
	AccountID []uuid.UUID `json:"accountId,omitempty"`
	// Which tab this is. The browser names itself, and the name points at nothing:
	// one sign-in can have several tabs, and each is present separately rather
	// than overwriting the others.
	SessionKey []string `json:"sessionKey,omitempty"`
	// When this tab first appeared. It deliberately does not move on a heartbeat,
	// so "joined four minutes ago" stays answerable.
	CreatedAt []time.Time `json:"createdAt,omitempty"`
	// The last heartbeat. Not updated_at: this is not when the row was last
	// edited, it is the whole meaning of the row — whoever is reading decides
	// whether somebody is here by comparing it against the configured TTL.
	SeenAt []time.Time `json:"seenAt,omitempty"`
	// Which part of the application this presence is in, named by the application:
	// a board, a document, a tenant. It is what a subscriber narrows the stream
	// by, so it decides how much presence traffic one screen pays for.
	Scope []string `json:"scope,omitempty"`
	// The table the row being looked at is in, checked against this API's own
	// tables. Null means present in the scope without being on a particular row.
	TargetTable []string `json:"targetTable,omitempty"`
	// Which row. There is deliberately no foreign key, and this is the one place
	// rig accepts a polymorphic reference: nothing joins to a presence row,
	// nothing embeds one, and no client filters a list of them — so the
	// integrity a key would buy has no reader. A presence pointing at a row
	// somebody just deleted is not a bug, it is a row that will be gone before
	// anybody looks.
	TargetID []uuid.UUID `json:"targetId,omitempty"`
	// Which field, when the application tracks focus that finely. This is what
	// turns "Simon is on this issue" into "Simon is editing the title".
	TargetField []string `json:"targetField,omitempty"`
	// Whether they are looking or typing. Separate from target_field because a
	// client may know somebody is editing before it knows which control has focus.
	Activity []RigPresenceActivity `json:"activity,omitempty"`
}

// Pattern conditions on RigPresence text fields.
type RigPresenceFilterLike struct {
	// Which tab this is. The browser names itself, and the name points at nothing:
	// one sign-in can have several tabs, and each is present separately rather
	// than overwriting the others.
	SessionKey *string `json:"sessionKey,omitempty"`
	// Which part of the application this presence is in, named by the application:
	// a board, a document, a tenant. It is what a subscriber narrows the stream
	// by, so it decides how much presence traffic one screen pays for.
	Scope *string `json:"scope,omitempty"`
	// The table the row being looked at is in, checked against this API's own
	// tables. Null means present in the scope without being on a particular row.
	TargetTable *string `json:"targetTable,omitempty"`
	// Which field, when the application tracks focus that finely. This is what
	// turns "Simon is on this issue" into "Simon is editing the title".
	TargetField *string `json:"targetField,omitempty"`
}

// Presence conditions on nullable RigPresence fields.
type RigPresenceFilterNull struct {
	// The table the row being looked at is in, checked against this API's own
	// tables. Null means present in the scope without being on a particular row.
	TargetTable *bool `json:"targetTable,omitempty"`
	// Which row. There is deliberately no foreign key, and this is the one place
	// rig accepts a polymorphic reference: nothing joins to a presence row,
	// nothing embeds one, and no client filters a list of them — so the
	// integrity a key would buy has no reader. A presence pointing at a row
	// somebody just deleted is not a bug, it is a row that will be gone before
	// anybody looks.
	TargetID *bool `json:"targetId,omitempty"`
	// Which field, when the application tracks focus that finely. This is what
	// turns "Simon is on this issue" into "Simon is editing the title".
	TargetField *bool `json:"targetField,omitempty"`
}

// Conditions a RigPresence must satisfy to match a search.
type RigPresenceFilter struct {
	// Fields that must equal the given value.
	Equals *RigPresenceFilterEquals `json:"equals,omitempty"`
	// Fields that must not equal the given value.
	NotEquals *RigPresenceFilterEquals `json:"notEquals,omitempty"`
	// Fields that must be greater than the given value.
	GreaterThan *RigPresenceFilterRange `json:"greaterThan,omitempty"`
	// Fields that must be less than the given value.
	SmallerThan *RigPresenceFilterRange `json:"smallerThan,omitempty"`
	// Fields that must be greater than or equal to the given value.
	GreaterOrEqual *RigPresenceFilterRange `json:"greaterOrEqual,omitempty"`
	// Fields that must be less than or equal to the given value.
	SmallerOrEqual *RigPresenceFilterRange `json:"smallerOrEqual,omitempty"`
	// Fields that must be one of the given values.
	Contains *RigPresenceFilterContains `json:"contains,omitempty"`
	// Fields that must not be one of the given values.
	NotContains *RigPresenceFilterContains `json:"notContains,omitempty"`
	// Text fields that must match the given pattern.
	Like *RigPresenceFilterLike `json:"like,omitempty"`
	// Text fields that must not match the given pattern.
	NotLike *RigPresenceFilterLike `json:"notLike,omitempty"`
	// Fields that must be null.
	Null *RigPresenceFilterNull `json:"null,omitempty"`
	// Fields that must not be null.
	NotNull *RigPresenceFilterNull `json:"notNull,omitempty"`
	// Combine this filter's conditions with OR instead of AND.
	OrCondition bool `json:"orCondition,omitempty"`
	// Sub-filters combined with this one, so that AND and OR can be mixed to any
	// depth.
	NestedFilters []RigPresenceFilter `json:"nestedFilters,omitempty"`
}

// RigPresencePage says which slice of a result to return, and in what order.
//
// The zero value is the first page at the repository's default size, in the
// table's configured order, which is what a caller who has not thought about
// it wants.
type RigPresencePage struct {
	Limit  int
	Offset int

	// OrderBy replaces the table's default ordering.
	OrderBy []RigPresenceOrder
}

// RigPresenceOrder is one clause of an ordering.
//
// Relation names the relation the column belongs to, and is empty for this
// table's own columns. The repository turns it into a left join, so a row
// whose related row is missing still appears — at one end of the order
// rather than not at all.
type RigPresenceOrder struct {
	Relation string
	Column   string
	Desc     bool
}

// The orderings a RigPresence supports.
var (
	RigPresenceOrderIDAsc           = RigPresenceOrder{Column: "id"}
	RigPresenceOrderIDDesc          = RigPresenceOrder{Column: "id", Desc: true}
	RigPresenceOrderTenantIDAsc     = RigPresenceOrder{Column: "tenant_id"}
	RigPresenceOrderTenantIDDesc    = RigPresenceOrder{Column: "tenant_id", Desc: true}
	RigPresenceOrderAccountIDAsc    = RigPresenceOrder{Column: "account_id"}
	RigPresenceOrderAccountIDDesc   = RigPresenceOrder{Column: "account_id", Desc: true}
	RigPresenceOrderSessionKeyAsc   = RigPresenceOrder{Column: "session_key"}
	RigPresenceOrderSessionKeyDesc  = RigPresenceOrder{Column: "session_key", Desc: true}
	RigPresenceOrderCreatedAtAsc    = RigPresenceOrder{Column: "created_at"}
	RigPresenceOrderCreatedAtDesc   = RigPresenceOrder{Column: "created_at", Desc: true}
	RigPresenceOrderSeenAtAsc       = RigPresenceOrder{Column: "seen_at"}
	RigPresenceOrderSeenAtDesc      = RigPresenceOrder{Column: "seen_at", Desc: true}
	RigPresenceOrderScopeAsc        = RigPresenceOrder{Column: "scope"}
	RigPresenceOrderScopeDesc       = RigPresenceOrder{Column: "scope", Desc: true}
	RigPresenceOrderTargetTableAsc  = RigPresenceOrder{Column: "target_table"}
	RigPresenceOrderTargetTableDesc = RigPresenceOrder{Column: "target_table", Desc: true}
	RigPresenceOrderTargetIDAsc     = RigPresenceOrder{Column: "target_id"}
	RigPresenceOrderTargetIDDesc    = RigPresenceOrder{Column: "target_id", Desc: true}
	RigPresenceOrderTargetFieldAsc  = RigPresenceOrder{Column: "target_field"}
	RigPresenceOrderTargetFieldDesc = RigPresenceOrder{Column: "target_field", Desc: true}
	RigPresenceOrderActivityAsc     = RigPresenceOrder{Column: "activity"}
	RigPresenceOrderActivityDesc    = RigPresenceOrder{Column: "activity", Desc: true}
)

// NewRigPresenceFilterEquals builds an empty RigPresenceFilterEquals to fill
// in.
func NewRigPresenceFilterEquals() *RigPresenceFilterEquals { return &RigPresenceFilterEquals{} }

// NewRigPresenceFilterRange builds an empty RigPresenceFilterRange to fill in.
func NewRigPresenceFilterRange() *RigPresenceFilterRange { return &RigPresenceFilterRange{} }

// NewRigPresenceFilterContains builds an empty RigPresenceFilterContains to
// fill in.
func NewRigPresenceFilterContains() *RigPresenceFilterContains { return &RigPresenceFilterContains{} }

// NewRigPresenceFilterLike builds an empty RigPresenceFilterLike to fill in.
func NewRigPresenceFilterLike() *RigPresenceFilterLike { return &RigPresenceFilterLike{} }

// NewRigPresenceFilterNull builds an empty RigPresenceFilterNull to fill in.
func NewRigPresenceFilterNull() *RigPresenceFilterNull { return &RigPresenceFilterNull{} }

// NewRigPresenceFilter builds an empty filter, which matches every row the
// caller is allowed to see.
func NewRigPresenceFilter() RigPresenceFilter { return RigPresenceFilter{} }
