// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"strings"
)

// TODO: what does this enumeration represent?
type RigNotificationState string

// The values of RigNotificationState.
const (
	// TODO: describe this.
	RigNotificationStatePending RigNotificationState = "Pending"
	// TODO: describe this.
	RigNotificationStateResolved RigNotificationState = "Resolved"
	// TODO: describe this.
	RigNotificationStateCancelled RigNotificationState = "Cancelled"
)

// AllRigNotificationState is every value, in declaration order.
var AllRigNotificationState = []RigNotificationState{RigNotificationStatePending, RigNotificationStateResolved, RigNotificationStateCancelled}

// Valid reports whether the value is one the database will accept.
func (v RigNotificationState) Valid() bool {
	switch v {
	case RigNotificationStatePending, RigNotificationStateResolved, RigNotificationStateCancelled:
		return true
	default:
		return false
	}
}

// ParseRigNotificationState reads a value, accepting any casing and
// surrounding space.
//
// Normalization uses it, so "IN_PROGRESS" from one client and "in_progress"
// from another mean the same thing rather than one of them being a validation
// failure nobody can explain. The spelling still has to be the label’s: a
// value is a name the database knows, not a phrase.
func ParseRigNotificationState(s string) (RigNotificationState, bool) {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "pending":
		return RigNotificationStatePending, true
	case "resolved":
		return RigNotificationStateResolved, true
	case "cancelled":
		return RigNotificationStateCancelled, true
	default:
		return "", false
	}
}

// String implements fmt.Stringer.
func (v RigNotificationState) String() string { return string(v) }
