// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// Exact-match conditions on RigNotificationRecipient fields.
type RigNotificationRecipientFilterEquals struct {
	// Unique identifier for this row.
	ID *uuid.UUID `json:"id,omitempty"`
	// What happened. The line is separate from it so that one person clearing
	// their inbox changes nothing anybody else sees.
	NotificationID *uuid.UUID `json:"notificationId,omitempty"`
	// Who this line is for. An account rather than an identity: an identity has no
	// tenant, so a row addressed to one would fall outside every generated query.
	AccountID *uuid.UUID `json:"accountId,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *uuid.UUID `json:"deletedByAccountId,omitempty"`
	// Copied from the notification, so the inbox and its live-sync shape never
	// touch a table holding rows for people who are not recipients.
	Kind *string `json:"kind,omitempty"`
	// What collapses several events into one line. Null opts out and every event
	// is its own row.
	GroupKey *string `json:"groupKey,omitempty"`
	// How many events this line stands for. One unless a group key collapsed them.
	EventCount *int `json:"eventCount,omitempty"`
	// When the person read it. Null is unread, which is what the badge counts.
	ReadAt *time.Time `json:"readAt,omitempty"`
}

// Ordering conditions on RigNotificationRecipient fields that can be compared.
type RigNotificationRecipientFilterRange struct {
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// How many events this line stands for. One unless a group key collapsed them.
	EventCount *int `json:"eventCount,omitempty"`
	// When the person read it. Null is unread, which is what the badge counts.
	ReadAt *time.Time `json:"readAt,omitempty"`
}

// Set-membership conditions on RigNotificationRecipient fields.
type RigNotificationRecipientFilterContains struct {
	// Unique identifier for this row.
	ID []uuid.UUID `json:"id,omitempty"`
	// What happened. The line is separate from it so that one person clearing
	// their inbox changes nothing anybody else sees.
	NotificationID []uuid.UUID `json:"notificationId,omitempty"`
	// Who this line is for. An account rather than an identity: an identity has no
	// tenant, so a row addressed to one would fall outside every generated query.
	AccountID []uuid.UUID `json:"accountId,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt []time.Time `json:"createdAt,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt []time.Time `json:"updatedAt,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt []time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID []uuid.UUID `json:"deletedByAccountId,omitempty"`
	// Copied from the notification, so the inbox and its live-sync shape never
	// touch a table holding rows for people who are not recipients.
	Kind []string `json:"kind,omitempty"`
	// What collapses several events into one line. Null opts out and every event
	// is its own row.
	GroupKey []string `json:"groupKey,omitempty"`
	// How many events this line stands for. One unless a group key collapsed them.
	EventCount []int `json:"eventCount,omitempty"`
	// When the person read it. Null is unread, which is what the badge counts.
	ReadAt []time.Time `json:"readAt,omitempty"`
}

// Pattern conditions on RigNotificationRecipient text fields.
type RigNotificationRecipientFilterLike struct {
	// Copied from the notification, so the inbox and its live-sync shape never
	// touch a table holding rows for people who are not recipients.
	Kind *string `json:"kind,omitempty"`
	// What collapses several events into one line. Null opts out and every event
	// is its own row.
	GroupKey *string `json:"groupKey,omitempty"`
}

// Presence conditions on nullable RigNotificationRecipient fields.
type RigNotificationRecipientFilterNull struct {
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *bool `json:"updatedAt,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *bool `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *bool `json:"deletedByAccountId,omitempty"`
	// What collapses several events into one line. Null opts out and every event
	// is its own row.
	GroupKey *bool `json:"groupKey,omitempty"`
	// When the person read it. Null is unread, which is what the badge counts.
	ReadAt *bool `json:"readAt,omitempty"`
}

// Conditions a RigNotificationRecipient must satisfy to match a search.
type RigNotificationRecipientFilter struct {
	// Fields that must equal the given value.
	Equals *RigNotificationRecipientFilterEquals `json:"equals,omitempty"`
	// Fields that must not equal the given value.
	NotEquals *RigNotificationRecipientFilterEquals `json:"notEquals,omitempty"`
	// Fields that must be greater than the given value.
	GreaterThan *RigNotificationRecipientFilterRange `json:"greaterThan,omitempty"`
	// Fields that must be less than the given value.
	SmallerThan *RigNotificationRecipientFilterRange `json:"smallerThan,omitempty"`
	// Fields that must be greater than or equal to the given value.
	GreaterOrEqual *RigNotificationRecipientFilterRange `json:"greaterOrEqual,omitempty"`
	// Fields that must be less than or equal to the given value.
	SmallerOrEqual *RigNotificationRecipientFilterRange `json:"smallerOrEqual,omitempty"`
	// Fields that must be one of the given values.
	Contains *RigNotificationRecipientFilterContains `json:"contains,omitempty"`
	// Fields that must not be one of the given values.
	NotContains *RigNotificationRecipientFilterContains `json:"notContains,omitempty"`
	// Text fields that must match the given pattern.
	Like *RigNotificationRecipientFilterLike `json:"like,omitempty"`
	// Text fields that must not match the given pattern.
	NotLike *RigNotificationRecipientFilterLike `json:"notLike,omitempty"`
	// Fields that must be null.
	Null *RigNotificationRecipientFilterNull `json:"null,omitempty"`
	// Fields that must not be null.
	NotNull *RigNotificationRecipientFilterNull `json:"notNull,omitempty"`
	// Combine this filter's conditions with OR instead of AND.
	OrCondition bool `json:"orCondition,omitempty"`
	// Sub-filters combined with this one, so that AND and OR can be mixed to any
	// depth.
	NestedFilters []RigNotificationRecipientFilter `json:"nestedFilters,omitempty"`
}

// RigNotificationRecipientPage says which slice of a result to return, and in
// what order.
//
// The zero value is the first page at the repository's default size, in the
// table's configured order, which is what a caller who has not thought about
// it wants.
type RigNotificationRecipientPage struct {
	Limit  int
	Offset int

	// OrderBy replaces the table's default ordering.
	OrderBy []RigNotificationRecipientOrder
}

// RigNotificationRecipientOrder is one clause of an ordering.
//
// Relation names the relation the column belongs to, and is empty for this
// table's own columns. The repository turns it into a left join, so a row
// whose related row is missing still appears — at one end of the order
// rather than not at all.
type RigNotificationRecipientOrder struct {
	Relation string
	Column   string
	Desc     bool
}

// The orderings a RigNotificationRecipient supports.
var (
	RigNotificationRecipientOrderIDAsc                  = RigNotificationRecipientOrder{Column: "id"}
	RigNotificationRecipientOrderIDDesc                 = RigNotificationRecipientOrder{Column: "id", Desc: true}
	RigNotificationRecipientOrderTenantIDAsc            = RigNotificationRecipientOrder{Column: "tenant_id"}
	RigNotificationRecipientOrderTenantIDDesc           = RigNotificationRecipientOrder{Column: "tenant_id", Desc: true}
	RigNotificationRecipientOrderNotificationIDAsc      = RigNotificationRecipientOrder{Column: "notification_id"}
	RigNotificationRecipientOrderNotificationIDDesc     = RigNotificationRecipientOrder{Column: "notification_id", Desc: true}
	RigNotificationRecipientOrderAccountIDAsc           = RigNotificationRecipientOrder{Column: "account_id"}
	RigNotificationRecipientOrderAccountIDDesc          = RigNotificationRecipientOrder{Column: "account_id", Desc: true}
	RigNotificationRecipientOrderCreatedAtAsc           = RigNotificationRecipientOrder{Column: "created_at"}
	RigNotificationRecipientOrderCreatedAtDesc          = RigNotificationRecipientOrder{Column: "created_at", Desc: true}
	RigNotificationRecipientOrderUpdatedAtAsc           = RigNotificationRecipientOrder{Column: "updated_at"}
	RigNotificationRecipientOrderUpdatedAtDesc          = RigNotificationRecipientOrder{Column: "updated_at", Desc: true}
	RigNotificationRecipientOrderDeletedAtAsc           = RigNotificationRecipientOrder{Column: "deleted_at"}
	RigNotificationRecipientOrderDeletedAtDesc          = RigNotificationRecipientOrder{Column: "deleted_at", Desc: true}
	RigNotificationRecipientOrderDeletedByAccountIDAsc  = RigNotificationRecipientOrder{Column: "deleted_by_account_id"}
	RigNotificationRecipientOrderDeletedByAccountIDDesc = RigNotificationRecipientOrder{Column: "deleted_by_account_id", Desc: true}
	RigNotificationRecipientOrderKindAsc                = RigNotificationRecipientOrder{Column: "kind"}
	RigNotificationRecipientOrderKindDesc               = RigNotificationRecipientOrder{Column: "kind", Desc: true}
	RigNotificationRecipientOrderGroupKeyAsc            = RigNotificationRecipientOrder{Column: "group_key"}
	RigNotificationRecipientOrderGroupKeyDesc           = RigNotificationRecipientOrder{Column: "group_key", Desc: true}
	RigNotificationRecipientOrderEventCountAsc          = RigNotificationRecipientOrder{Column: "event_count"}
	RigNotificationRecipientOrderEventCountDesc         = RigNotificationRecipientOrder{Column: "event_count", Desc: true}
	RigNotificationRecipientOrderReadAtAsc              = RigNotificationRecipientOrder{Column: "read_at"}
	RigNotificationRecipientOrderReadAtDesc             = RigNotificationRecipientOrder{Column: "read_at", Desc: true}
)

// NewRigNotificationRecipientFilterEquals builds an empty
// RigNotificationRecipientFilterEquals to fill in.
func NewRigNotificationRecipientFilterEquals() *RigNotificationRecipientFilterEquals {
	return &RigNotificationRecipientFilterEquals{}
}

// NewRigNotificationRecipientFilterRange builds an empty
// RigNotificationRecipientFilterRange to fill in.
func NewRigNotificationRecipientFilterRange() *RigNotificationRecipientFilterRange {
	return &RigNotificationRecipientFilterRange{}
}

// NewRigNotificationRecipientFilterContains builds an empty
// RigNotificationRecipientFilterContains to fill in.
func NewRigNotificationRecipientFilterContains() *RigNotificationRecipientFilterContains {
	return &RigNotificationRecipientFilterContains{}
}

// NewRigNotificationRecipientFilterLike builds an empty
// RigNotificationRecipientFilterLike to fill in.
func NewRigNotificationRecipientFilterLike() *RigNotificationRecipientFilterLike {
	return &RigNotificationRecipientFilterLike{}
}

// NewRigNotificationRecipientFilterNull builds an empty
// RigNotificationRecipientFilterNull to fill in.
func NewRigNotificationRecipientFilterNull() *RigNotificationRecipientFilterNull {
	return &RigNotificationRecipientFilterNull{}
}

// NewRigNotificationRecipientFilter builds an empty filter, which matches
// every row the caller is allowed to see.
func NewRigNotificationRecipientFilter() RigNotificationRecipientFilter {
	return RigNotificationRecipientFilter{}
}
