// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// Who is here and what they are looking at. One row per browser tab, rewritten
// every heartbeat and deleted once it is stale.
//
// It is the one definition of a RigPresence: the repository scans into it and
// the API returns it, so there is no conversion between two shapes of the same
// thing and no field that can go missing from one of them.
type RigPresence struct {
	// The row's identifier. Nothing references it: a client addresses its own
	// presence by session key, so this identifier never leaves the server except
	// on the stream.
	ID uuid.UUID `json:"id"`
	// The tenant this presence is inside. Every read of this table is filtered on
	// it, the stream included.
	TenantID uuid.UUID `json:"tenantId"`
	// Who is present. Read from the credential and never from a request body,
	// which is what makes "you may only write your own presence" a sentence a
	// client cannot phrase rather than a rule somebody enforces.
	AccountID uuid.UUID `json:"accountId"`
	// Which tab this is. The browser names itself, and the name points at nothing:
	// one sign-in can have several tabs, and each is present separately rather
	// than overwriting the others.
	SessionKey string `json:"sessionKey"`
	// When this tab first appeared. It deliberately does not move on a heartbeat,
	// so "joined four minutes ago" stays answerable.
	CreatedAt time.Time `json:"createdAt"`
	// The last heartbeat. Not updated_at: this is not when the row was last
	// edited, it is the whole meaning of the row — whoever is reading decides
	// whether somebody is here by comparing it against the configured TTL.
	SeenAt time.Time `json:"seenAt"`
	// Which part of the application this presence is in, named by the application:
	// a board, a document, a tenant. It is what a subscriber narrows the stream
	// by, so it decides how much presence traffic one screen pays for.
	Scope string `json:"scope"`
	// The table the row being looked at is in, checked against this API's own
	// tables. Null means present in the scope without being on a particular row.
	TargetTable *string `json:"targetTable,omitempty"`
	// Which row. There is deliberately no foreign key, and this is the one place
	// rig accepts a polymorphic reference: nothing joins to a presence row,
	// nothing embeds one, and no client filters a list of them — so the
	// integrity a key would buy has no reader. A presence pointing at a row
	// somebody just deleted is not a bug, it is a row that will be gone before
	// anybody looks.
	TargetID *uuid.UUID `json:"targetId,omitempty"`
	// Which field, when the application tracks focus that finely. This is what
	// turns "Simon is on this issue" into "Simon is editing the title".
	TargetField *string `json:"targetField,omitempty"`
	// Whether they are looking or typing. Separate from target_field because a
	// client may know somebody is editing before it knows which control has focus.
	Activity RigPresenceActivity `json:"activity"`
}

// TableRigPresence is the table this entity is stored in.
const TableRigPresence = "rig_presence"

// Column names for rig_presence, so nothing has to spell one out.
const (
	ColumnRigPresenceID          = "id"
	ColumnRigPresenceTenantID    = "tenant_id"
	ColumnRigPresenceAccountID   = "account_id"
	ColumnRigPresenceSessionKey  = "session_key"
	ColumnRigPresenceCreatedAt   = "created_at"
	ColumnRigPresenceSeenAt      = "seen_at"
	ColumnRigPresenceScope       = "scope"
	ColumnRigPresenceTargetTable = "target_table"
	ColumnRigPresenceTargetID    = "target_id"
	ColumnRigPresenceTargetField = "target_field"
	ColumnRigPresenceActivity    = "activity"
)

// RigPresenceColumns is every column, in the order the row is scanned.
var RigPresenceColumns = []string{"id", "tenant_id", "account_id", "session_key", "created_at", "seen_at", "scope", "target_table", "target_id", "target_field", "activity"}
