// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// Exact-match conditions on RigNotificationSetting fields.
type RigNotificationSettingFilterEquals struct {
	// Unique identifier for this row.
	ID *uuid.UUID `json:"id,omitempty"`
	// Whose preference it is.
	AccountID *uuid.UUID `json:"accountId,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Null is the default for the channel, which is the second step of the
	// resolution.
	Kind *string `json:"kind,omitempty"`
	// Which channel it answers for.
	Channel *RigNotificationChannel `json:"channel,omitempty"`
	// False writes no delivery row at all. Not the same as digest Off, which is
	// about preferring to look rather than be told.
	IsEnabled *bool `json:"isEnabled,omitempty"`
	// Immediate sends each on its own; anything else waits for the window and goes
	// out as one message.
	Digest *RigNotificationDigest `json:"digest,omitempty"`
	// When to start delivering, in the account time zone. Null means all day. A
	// window that wraps midnight is ordinary: 22:00 to 06:00 is how somebody says
	// "not overnight".
	ActiveFrom *time.Time `json:"activeFrom,omitempty"`
	// When to stop. Outside the window a delivery is held, not dropped: the inbox
	// line exists either way, and a discarded copy makes the badge and the mailbox
	// disagree.
	ActiveUntil *time.Time `json:"activeUntil,omitempty"`
	// ISO weekdays, 1 being Monday. Empty means every day. An array rather than a
	// bitmask because [1,2,3,4,5] is legible in a settings payload and 62 is not.
	ActiveDays []int16 `json:"activeDays,omitempty"`
	// Conditions on this row's Account.
	//
	// A row with no Account never matches, and that holds for the negative
	// operators too: under NotEquals this asks whether the Account is there and
	// differs, so a row without one fails that as well. To ask the other question
	// — no matching Account, which a row with none satisfies — use
	// Without.Account.
	Account *RigAccountFilterEquals `json:"account,omitempty"`
}

// Ordering conditions on RigNotificationSetting fields that can be compared.
type RigNotificationSettingFilterRange struct {
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// When to start delivering, in the account time zone. Null means all day. A
	// window that wraps midnight is ordinary: 22:00 to 06:00 is how somebody says
	// "not overnight".
	ActiveFrom *time.Time `json:"activeFrom,omitempty"`
	// When to stop. Outside the window a delivery is held, not dropped: the inbox
	// line exists either way, and a discarded copy makes the badge and the mailbox
	// disagree.
	ActiveUntil *time.Time `json:"activeUntil,omitempty"`
	// Conditions on this row's Account.
	//
	// A row with no Account never matches, and that holds for the negative
	// operators too: under NotEquals this asks whether the Account is there and
	// differs, so a row without one fails that as well. To ask the other question
	// — no matching Account, which a row with none satisfies — use
	// Without.Account.
	Account *RigAccountFilterRange `json:"account,omitempty"`
}

// Set-membership conditions on RigNotificationSetting fields.
type RigNotificationSettingFilterContains struct {
	// Unique identifier for this row.
	ID []uuid.UUID `json:"id,omitempty"`
	// Whose preference it is.
	AccountID []uuid.UUID `json:"accountId,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt []time.Time `json:"createdAt,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt []time.Time `json:"updatedAt,omitempty"`
	// Null is the default for the channel, which is the second step of the
	// resolution.
	Kind []string `json:"kind,omitempty"`
	// Which channel it answers for.
	Channel []RigNotificationChannel `json:"channel,omitempty"`
	// False writes no delivery row at all. Not the same as digest Off, which is
	// about preferring to look rather than be told.
	IsEnabled []bool `json:"isEnabled,omitempty"`
	// Immediate sends each on its own; anything else waits for the window and goes
	// out as one message.
	Digest []RigNotificationDigest `json:"digest,omitempty"`
	// When to start delivering, in the account time zone. Null means all day. A
	// window that wraps midnight is ordinary: 22:00 to 06:00 is how somebody says
	// "not overnight".
	ActiveFrom []time.Time `json:"activeFrom,omitempty"`
	// When to stop. Outside the window a delivery is held, not dropped: the inbox
	// line exists either way, and a discarded copy makes the badge and the mailbox
	// disagree.
	ActiveUntil []time.Time `json:"activeUntil,omitempty"`
	// Conditions on this row's Account.
	//
	// A row with no Account never matches, and that holds for the negative
	// operators too: under NotEquals this asks whether the Account is there and
	// differs, so a row without one fails that as well. To ask the other question
	// — no matching Account, which a row with none satisfies — use
	// Without.Account.
	Account *RigAccountFilterContains `json:"account,omitempty"`
}

// Pattern conditions on RigNotificationSetting text fields.
type RigNotificationSettingFilterLike struct {
	// Null is the default for the channel, which is the second step of the
	// resolution.
	Kind *string `json:"kind,omitempty"`
	// Conditions on this row's Account.
	//
	// A row with no Account never matches, and that holds for the negative
	// operators too: under NotEquals this asks whether the Account is there and
	// differs, so a row without one fails that as well. To ask the other question
	// — no matching Account, which a row with none satisfies — use
	// Without.Account.
	Account *RigAccountFilterLike `json:"account,omitempty"`
}

// Presence conditions on nullable RigNotificationSetting fields.
type RigNotificationSettingFilterNull struct {
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *bool `json:"updatedAt,omitempty"`
	// Null is the default for the channel, which is the second step of the
	// resolution.
	Kind *bool `json:"kind,omitempty"`
	// When to start delivering, in the account time zone. Null means all day. A
	// window that wraps midnight is ordinary: 22:00 to 06:00 is how somebody says
	// "not overnight".
	ActiveFrom *bool `json:"activeFrom,omitempty"`
	// When to stop. Outside the window a delivery is held, not dropped: the inbox
	// line exists either way, and a discarded copy makes the badge and the mailbox
	// disagree.
	ActiveUntil *bool `json:"activeUntil,omitempty"`
	// Conditions on this row's Account.
	//
	// A row with no Account never matches, and that holds for the negative
	// operators too: under NotEquals this asks whether the Account is there and
	// differs, so a row without one fails that as well. To ask the other question
	// — no matching Account, which a row with none satisfies — use
	// Without.Account.
	Account *RigAccountFilterNull `json:"account,omitempty"`
}

// Relations a RigNotificationSetting must have no matching row for.
type RigNotificationSettingFilterWithout struct {
	// Match rows with no Account satisfying these conditions, including rows that
	// have none at all.
	//
	// This negates the existence of the related row rather than the comparison,
	// which is the whole difference from NotEquals.Account: that one needs the
	// Account to be there and to differ, so a row without one fails it and
	// satisfies this. An empty object asks for rows with no Account at all.
	Account *RigAccountFilter `json:"account,omitempty"`
}

// Conditions a RigNotificationSetting must satisfy to match a search.
type RigNotificationSettingFilter struct {
	// Fields that must equal the given value.
	Equals *RigNotificationSettingFilterEquals `json:"equals,omitempty"`
	// Fields that must not equal the given value.
	NotEquals *RigNotificationSettingFilterEquals `json:"notEquals,omitempty"`
	// Fields that must be greater than the given value.
	GreaterThan *RigNotificationSettingFilterRange `json:"greaterThan,omitempty"`
	// Fields that must be less than the given value.
	SmallerThan *RigNotificationSettingFilterRange `json:"smallerThan,omitempty"`
	// Fields that must be greater than or equal to the given value.
	GreaterOrEqual *RigNotificationSettingFilterRange `json:"greaterOrEqual,omitempty"`
	// Fields that must be less than or equal to the given value.
	SmallerOrEqual *RigNotificationSettingFilterRange `json:"smallerOrEqual,omitempty"`
	// Fields that must be one of the given values.
	Contains *RigNotificationSettingFilterContains `json:"contains,omitempty"`
	// Fields that must not be one of the given values.
	NotContains *RigNotificationSettingFilterContains `json:"notContains,omitempty"`
	// Text fields that must match the given pattern.
	Like *RigNotificationSettingFilterLike `json:"like,omitempty"`
	// Text fields that must not match the given pattern.
	NotLike *RigNotificationSettingFilterLike `json:"notLike,omitempty"`
	// Fields that must be null.
	Null *RigNotificationSettingFilterNull `json:"null,omitempty"`
	// Fields that must not be null.
	NotNull *RigNotificationSettingFilterNull `json:"notNull,omitempty"`
	// Combine this filter's conditions with OR instead of AND.
	OrCondition bool `json:"orCondition,omitempty"`
	// Sub-filters combined with this one, so that AND and OR can be mixed to any
	// depth.
	NestedFilters []RigNotificationSettingFilter `json:"nestedFilters,omitempty"`
	// Relations with no row matching the given conditions. An empty one asks for
	// no related row at all.
	//
	// This is where a negation belongs when what you mean is "not": it negates
	// whether a matching related row exists, so a row with no related row at all
	// satisfies it. The negative operators above negate the comparison instead and
	// still require the related row to be there — "no related row called X" is
	// here, "a related row not called X" is NotEquals.
	Without *RigNotificationSettingFilterWithout `json:"without,omitempty"`
}

// RigNotificationSettingPage says which slice of a result to return, and in
// what order.
//
// The zero value is the first page at the repository's default size, in the
// table's configured order, which is what a caller who has not thought about
// it wants.
type RigNotificationSettingPage struct {
	Limit  int
	Offset int

	// OrderBy replaces the table's default ordering.
	OrderBy []RigNotificationSettingOrder
}

// RigNotificationSettingOrder is one clause of an ordering.
//
// Relation names the relation the column belongs to, and is empty for this
// table's own columns. The repository turns it into a left join, so a row
// whose related row is missing still appears — at one end of the order
// rather than not at all.
type RigNotificationSettingOrder struct {
	Relation string
	Column   string
	Desc     bool
}

// The orderings a RigNotificationSetting supports.
var (
	RigNotificationSettingOrderIDAsc           = RigNotificationSettingOrder{Column: "id"}
	RigNotificationSettingOrderIDDesc          = RigNotificationSettingOrder{Column: "id", Desc: true}
	RigNotificationSettingOrderTenantIDAsc     = RigNotificationSettingOrder{Column: "tenant_id"}
	RigNotificationSettingOrderTenantIDDesc    = RigNotificationSettingOrder{Column: "tenant_id", Desc: true}
	RigNotificationSettingOrderAccountIDAsc    = RigNotificationSettingOrder{Column: "account_id"}
	RigNotificationSettingOrderAccountIDDesc   = RigNotificationSettingOrder{Column: "account_id", Desc: true}
	RigNotificationSettingOrderCreatedAtAsc    = RigNotificationSettingOrder{Column: "created_at"}
	RigNotificationSettingOrderCreatedAtDesc   = RigNotificationSettingOrder{Column: "created_at", Desc: true}
	RigNotificationSettingOrderUpdatedAtAsc    = RigNotificationSettingOrder{Column: "updated_at"}
	RigNotificationSettingOrderUpdatedAtDesc   = RigNotificationSettingOrder{Column: "updated_at", Desc: true}
	RigNotificationSettingOrderKindAsc         = RigNotificationSettingOrder{Column: "kind"}
	RigNotificationSettingOrderKindDesc        = RigNotificationSettingOrder{Column: "kind", Desc: true}
	RigNotificationSettingOrderChannelAsc      = RigNotificationSettingOrder{Column: "channel"}
	RigNotificationSettingOrderChannelDesc     = RigNotificationSettingOrder{Column: "channel", Desc: true}
	RigNotificationSettingOrderIsEnabledAsc    = RigNotificationSettingOrder{Column: "is_enabled"}
	RigNotificationSettingOrderIsEnabledDesc   = RigNotificationSettingOrder{Column: "is_enabled", Desc: true}
	RigNotificationSettingOrderDigestAsc       = RigNotificationSettingOrder{Column: "digest"}
	RigNotificationSettingOrderDigestDesc      = RigNotificationSettingOrder{Column: "digest", Desc: true}
	RigNotificationSettingOrderActiveFromAsc   = RigNotificationSettingOrder{Column: "active_from"}
	RigNotificationSettingOrderActiveFromDesc  = RigNotificationSettingOrder{Column: "active_from", Desc: true}
	RigNotificationSettingOrderActiveUntilAsc  = RigNotificationSettingOrder{Column: "active_until"}
	RigNotificationSettingOrderActiveUntilDesc = RigNotificationSettingOrder{Column: "active_until", Desc: true}
)

// RigNotificationSettingOrderAccount orders a RigNotificationSetting by a
// column of its Account.
//
// Take the term from RigAccount's own orderings:
//
//	RigNotificationSettingOrderAccount(RigAccountOrderIDDesc)
//
// The repository reaches it with a left join, so a RigNotificationSetting with
// no Account sorts to one end rather than vanishing. Only RigAccount's own
// columns can be used; an ordering that itself reaches across a relation is
// refused, because one join is where this stops.
func RigNotificationSettingOrderAccount(o RigAccountOrder) RigNotificationSettingOrder {
	return RigNotificationSettingOrder{Relation: "Account", Column: o.Column, Desc: o.Desc}
}

// NewRigNotificationSettingFilterEquals builds an empty
// RigNotificationSettingFilterEquals to fill in.
func NewRigNotificationSettingFilterEquals() *RigNotificationSettingFilterEquals {
	return &RigNotificationSettingFilterEquals{}
}

// NewRigNotificationSettingFilterRange builds an empty
// RigNotificationSettingFilterRange to fill in.
func NewRigNotificationSettingFilterRange() *RigNotificationSettingFilterRange {
	return &RigNotificationSettingFilterRange{}
}

// NewRigNotificationSettingFilterContains builds an empty
// RigNotificationSettingFilterContains to fill in.
func NewRigNotificationSettingFilterContains() *RigNotificationSettingFilterContains {
	return &RigNotificationSettingFilterContains{}
}

// NewRigNotificationSettingFilterLike builds an empty
// RigNotificationSettingFilterLike to fill in.
func NewRigNotificationSettingFilterLike() *RigNotificationSettingFilterLike {
	return &RigNotificationSettingFilterLike{}
}

// NewRigNotificationSettingFilterNull builds an empty
// RigNotificationSettingFilterNull to fill in.
func NewRigNotificationSettingFilterNull() *RigNotificationSettingFilterNull {
	return &RigNotificationSettingFilterNull{}
}

// NewRigNotificationSettingFilterWithout builds an empty
// RigNotificationSettingFilterWithout to fill in.
func NewRigNotificationSettingFilterWithout() *RigNotificationSettingFilterWithout {
	return &RigNotificationSettingFilterWithout{}
}

// NewRigNotificationSettingFilter builds an empty filter, which matches every
// row the caller is allowed to see.
func NewRigNotificationSettingFilter() RigNotificationSettingFilter {
	return RigNotificationSettingFilter{}
}
