// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"strings"
)

// Where a copy of an inbox line can be sent. The inbox itself is not one of
// them.
type RigNotificationChannel string

// The values of RigNotificationChannel.
const (
	// A browser or a desktop application, addressed by a device row.
	RigNotificationChannelDesktop RigNotificationChannel = "Desktop"
	// A phone, addressed by a device row.
	RigNotificationChannelMobile RigNotificationChannel = "Mobile"
	// The address on the account. No device row: there is nothing to register,
	// because the address is on the account already.
	RigNotificationChannelEmail RigNotificationChannel = "Email"
)

// AllRigNotificationChannel is every value, in declaration order.
var AllRigNotificationChannel = []RigNotificationChannel{RigNotificationChannelDesktop, RigNotificationChannelMobile, RigNotificationChannelEmail}

// Valid reports whether the value is one the database will accept.
func (v RigNotificationChannel) Valid() bool {
	switch v {
	case RigNotificationChannelDesktop, RigNotificationChannelMobile, RigNotificationChannelEmail:
		return true
	default:
		return false
	}
}

// ParseRigNotificationChannel reads a value, accepting any casing and
// surrounding space.
//
// Normalization uses it, so "IN_PROGRESS" from one client and "in_progress"
// from another mean the same thing rather than one of them being a validation
// failure nobody can explain. The spelling still has to be the label’s: a
// value is a name the database knows, not a phrase.
func ParseRigNotificationChannel(s string) (RigNotificationChannel, bool) {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "desktop":
		return RigNotificationChannelDesktop, true
	case "mobile":
		return RigNotificationChannelMobile, true
	case "email":
		return RigNotificationChannelEmail, true
	default:
		return "", false
	}
}

// String implements fmt.Stringer.
func (v RigNotificationChannel) String() string { return string(v) }
