// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// Exact-match conditions on RigAccount fields.
type RigAccountFilterEquals struct {
	// Unique identifier for this row.
	ID *uuid.UUID `json:"id,omitempty"`
	// The person this account belongs to, or null for a service account, which is
	// nobody.
	IdentityID *uuid.UUID `json:"identityId,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *uuid.UUID `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *uuid.UUID `json:"deletedByAccountId,omitempty"`
	// Whether this is a person or a service account an integration acts as.
	Kind *RigAccountKind `json:"kind,omitempty"`
	// The coarse level in this tenant: Owner, Admin, or Basic. Somebody can be an
	// Owner here and Basic elsewhere.
	Role *RigAccountRoleLevel `json:"role,omitempty"`
	// A copy of the identity's address, kept here so listing accounts is one
	// query. For a service account it is a label nobody signs in with.
	EmailAddress *string `json:"emailAddress,omitempty"`
	// What to call the person in this tenant.
	DisplayName *string `json:"displayName,omitempty"`
	// IANA name, for example Europe/Stockholm. Null means UTC.
	TimeZone *string `json:"timeZone,omitempty"`
	// Whether the account may be used. A disabled account is refused with 403, not
	// 401.
	IsActive *bool `json:"isActive,omitempty"`
	// API key this row was created through, when it was an integration rather than
	// a person.
	CreatedByAPIKeyID *uuid.UUID `json:"createdByApiKeyId,omitempty"`
	// API key this row was last updated through, when it was an integration rather
	// than a person.
	UpdatedByAPIKeyID *uuid.UUID `json:"updatedByApiKeyId,omitempty"`
	// API key this row was soft-deleted through, when it was an integration rather
	// than a person.
	DeletedByAPIKeyID *uuid.UUID `json:"deletedByApiKeyId,omitempty"`
	// Conditions on one of this row's AssigneeAccountTodos.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.AssigneeAccountTodos asks the second.
	AssigneeAccountTodos *TodoFilterEquals `json:"assigneeAccountTodos,omitempty"`
	// Conditions on this row's CreatedByAccount.
	//
	// A row with no CreatedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// CreatedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching CreatedByAccount, which a
	// row with none satisfies — use Without.CreatedByAccount.
	CreatedByAccount *RigAccountFilterEquals `json:"createdByAccount,omitempty"`
	// Conditions on this row's DeletedByAccount.
	//
	// A row with no DeletedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// DeletedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching DeletedByAccount, which a
	// row with none satisfies — use Without.DeletedByAccount.
	DeletedByAccount *RigAccountFilterEquals `json:"deletedByAccount,omitempty"`
	// Conditions on this row's UpdatedByAccount.
	//
	// A row with no UpdatedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// UpdatedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching UpdatedByAccount, which a
	// row with none satisfies — use Without.UpdatedByAccount.
	UpdatedByAccount *RigAccountFilterEquals `json:"updatedByAccount,omitempty"`
}

// Ordering conditions on RigAccount fields that can be compared.
type RigAccountFilterRange struct {
	// When this row was created. Set automatically and never changes.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// Conditions on one of this row's AssigneeAccountTodos.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.AssigneeAccountTodos asks the second.
	AssigneeAccountTodos *TodoFilterRange `json:"assigneeAccountTodos,omitempty"`
	// Conditions on this row's CreatedByAccount.
	//
	// A row with no CreatedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// CreatedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching CreatedByAccount, which a
	// row with none satisfies — use Without.CreatedByAccount.
	CreatedByAccount *RigAccountFilterRange `json:"createdByAccount,omitempty"`
	// Conditions on this row's DeletedByAccount.
	//
	// A row with no DeletedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// DeletedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching DeletedByAccount, which a
	// row with none satisfies — use Without.DeletedByAccount.
	DeletedByAccount *RigAccountFilterRange `json:"deletedByAccount,omitempty"`
	// Conditions on this row's UpdatedByAccount.
	//
	// A row with no UpdatedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// UpdatedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching UpdatedByAccount, which a
	// row with none satisfies — use Without.UpdatedByAccount.
	UpdatedByAccount *RigAccountFilterRange `json:"updatedByAccount,omitempty"`
}

// Set-membership conditions on RigAccount fields.
type RigAccountFilterContains struct {
	// Unique identifier for this row.
	ID []uuid.UUID `json:"id,omitempty"`
	// The person this account belongs to, or null for a service account, which is
	// nobody.
	IdentityID []uuid.UUID `json:"identityId,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt []time.Time `json:"createdAt,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID []uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt []time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID []uuid.UUID `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt []time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID []uuid.UUID `json:"deletedByAccountId,omitempty"`
	// Whether this is a person or a service account an integration acts as.
	Kind []RigAccountKind `json:"kind,omitempty"`
	// The coarse level in this tenant: Owner, Admin, or Basic. Somebody can be an
	// Owner here and Basic elsewhere.
	Role []RigAccountRoleLevel `json:"role,omitempty"`
	// A copy of the identity's address, kept here so listing accounts is one
	// query. For a service account it is a label nobody signs in with.
	EmailAddress []string `json:"emailAddress,omitempty"`
	// What to call the person in this tenant.
	DisplayName []string `json:"displayName,omitempty"`
	// IANA name, for example Europe/Stockholm. Null means UTC.
	TimeZone []string `json:"timeZone,omitempty"`
	// Whether the account may be used. A disabled account is refused with 403, not
	// 401.
	IsActive []bool `json:"isActive,omitempty"`
	// API key this row was created through, when it was an integration rather than
	// a person.
	CreatedByAPIKeyID []uuid.UUID `json:"createdByApiKeyId,omitempty"`
	// API key this row was last updated through, when it was an integration rather
	// than a person.
	UpdatedByAPIKeyID []uuid.UUID `json:"updatedByApiKeyId,omitempty"`
	// API key this row was soft-deleted through, when it was an integration rather
	// than a person.
	DeletedByAPIKeyID []uuid.UUID `json:"deletedByApiKeyId,omitempty"`
	// Conditions on one of this row's AssigneeAccountTodos.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.AssigneeAccountTodos asks the second.
	AssigneeAccountTodos *TodoFilterContains `json:"assigneeAccountTodos,omitempty"`
	// Conditions on this row's CreatedByAccount.
	//
	// A row with no CreatedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// CreatedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching CreatedByAccount, which a
	// row with none satisfies — use Without.CreatedByAccount.
	CreatedByAccount *RigAccountFilterContains `json:"createdByAccount,omitempty"`
	// Conditions on this row's DeletedByAccount.
	//
	// A row with no DeletedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// DeletedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching DeletedByAccount, which a
	// row with none satisfies — use Without.DeletedByAccount.
	DeletedByAccount *RigAccountFilterContains `json:"deletedByAccount,omitempty"`
	// Conditions on this row's UpdatedByAccount.
	//
	// A row with no UpdatedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// UpdatedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching UpdatedByAccount, which a
	// row with none satisfies — use Without.UpdatedByAccount.
	UpdatedByAccount *RigAccountFilterContains `json:"updatedByAccount,omitempty"`
}

// Pattern conditions on RigAccount text fields.
type RigAccountFilterLike struct {
	// A copy of the identity's address, kept here so listing accounts is one
	// query. For a service account it is a label nobody signs in with.
	EmailAddress *string `json:"emailAddress,omitempty"`
	// What to call the person in this tenant.
	DisplayName *string `json:"displayName,omitempty"`
	// IANA name, for example Europe/Stockholm. Null means UTC.
	TimeZone *string `json:"timeZone,omitempty"`
	// Conditions on one of this row's AssigneeAccountTodos.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.AssigneeAccountTodos asks the second.
	AssigneeAccountTodos *TodoFilterLike `json:"assigneeAccountTodos,omitempty"`
	// Conditions on this row's CreatedByAccount.
	//
	// A row with no CreatedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// CreatedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching CreatedByAccount, which a
	// row with none satisfies — use Without.CreatedByAccount.
	CreatedByAccount *RigAccountFilterLike `json:"createdByAccount,omitempty"`
	// Conditions on this row's DeletedByAccount.
	//
	// A row with no DeletedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// DeletedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching DeletedByAccount, which a
	// row with none satisfies — use Without.DeletedByAccount.
	DeletedByAccount *RigAccountFilterLike `json:"deletedByAccount,omitempty"`
	// Conditions on this row's UpdatedByAccount.
	//
	// A row with no UpdatedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// UpdatedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching UpdatedByAccount, which a
	// row with none satisfies — use Without.UpdatedByAccount.
	UpdatedByAccount *RigAccountFilterLike `json:"updatedByAccount,omitempty"`
}

// Presence conditions on nullable RigAccount fields.
type RigAccountFilterNull struct {
	// The person this account belongs to, or null for a service account, which is
	// nobody.
	IdentityID *bool `json:"identityId,omitempty"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *bool `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *bool `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *bool `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *bool `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *bool `json:"deletedByAccountId,omitempty"`
	// IANA name, for example Europe/Stockholm. Null means UTC.
	TimeZone *bool `json:"timeZone,omitempty"`
	// API key this row was created through, when it was an integration rather than
	// a person.
	CreatedByAPIKeyID *bool `json:"createdByApiKeyId,omitempty"`
	// API key this row was last updated through, when it was an integration rather
	// than a person.
	UpdatedByAPIKeyID *bool `json:"updatedByApiKeyId,omitempty"`
	// API key this row was soft-deleted through, when it was an integration rather
	// than a person.
	DeletedByAPIKeyID *bool `json:"deletedByApiKeyId,omitempty"`
	// Conditions on one of this row's AssigneeAccountTodos.
	//
	// Every condition has to hold of the same one, not of the set between them.
	//
	// Under the negative operators this asks whether one of them differs, which is
	// not the same as none of them matching: a row can have one that matches and
	// one that does not, satisfying the first and failing the second.
	// Without.AssigneeAccountTodos asks the second.
	AssigneeAccountTodos *TodoFilterNull `json:"assigneeAccountTodos,omitempty"`
	// Conditions on this row's CreatedByAccount.
	//
	// A row with no CreatedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// CreatedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching CreatedByAccount, which a
	// row with none satisfies — use Without.CreatedByAccount.
	CreatedByAccount *RigAccountFilterNull `json:"createdByAccount,omitempty"`
	// Conditions on this row's DeletedByAccount.
	//
	// A row with no DeletedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// DeletedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching DeletedByAccount, which a
	// row with none satisfies — use Without.DeletedByAccount.
	DeletedByAccount *RigAccountFilterNull `json:"deletedByAccount,omitempty"`
	// Conditions on this row's UpdatedByAccount.
	//
	// A row with no UpdatedByAccount never matches, and that holds for the
	// negative operators too: under NotEquals this asks whether the
	// UpdatedByAccount is there and differs, so a row without one fails that as
	// well. To ask the other question — no matching UpdatedByAccount, which a
	// row with none satisfies — use Without.UpdatedByAccount.
	UpdatedByAccount *RigAccountFilterNull `json:"updatedByAccount,omitempty"`
}

// Relations a RigAccount must have no matching row for.
type RigAccountFilterWithout struct {
	// Match rows with no AssigneeAccountTodos satisfying these conditions,
	// including rows with none at all.
	//
	// This negates the existence of a matching row rather than the comparison,
	// which is the whole difference from NotEquals.AssigneeAccountTodos: that one
	// is satisfied by one of them differing, and a row can have one that differs
	// and one that matches at the same time. An empty object asks for rows with no
	// AssigneeAccountTodos at all.
	AssigneeAccountTodos *TodoFilter `json:"assigneeAccountTodos,omitempty"`
	// Match rows with no CreatedByAccount satisfying these conditions, including
	// rows that have none at all.
	//
	// This negates the existence of the related row rather than the comparison,
	// which is the whole difference from NotEquals.CreatedByAccount: that one
	// needs the CreatedByAccount to be there and to differ, so a row without one
	// fails it and satisfies this. An empty object asks for rows with no
	// CreatedByAccount at all.
	CreatedByAccount *RigAccountFilter `json:"createdByAccount,omitempty"`
	// Match rows with no DeletedByAccount satisfying these conditions, including
	// rows that have none at all.
	//
	// This negates the existence of the related row rather than the comparison,
	// which is the whole difference from NotEquals.DeletedByAccount: that one
	// needs the DeletedByAccount to be there and to differ, so a row without one
	// fails it and satisfies this. An empty object asks for rows with no
	// DeletedByAccount at all.
	DeletedByAccount *RigAccountFilter `json:"deletedByAccount,omitempty"`
	// Match rows with no UpdatedByAccount satisfying these conditions, including
	// rows that have none at all.
	//
	// This negates the existence of the related row rather than the comparison,
	// which is the whole difference from NotEquals.UpdatedByAccount: that one
	// needs the UpdatedByAccount to be there and to differ, so a row without one
	// fails it and satisfies this. An empty object asks for rows with no
	// UpdatedByAccount at all.
	UpdatedByAccount *RigAccountFilter `json:"updatedByAccount,omitempty"`
}

// Conditions a RigAccount must satisfy to match a search.
type RigAccountFilter struct {
	// Fields that must equal the given value.
	Equals *RigAccountFilterEquals `json:"equals,omitempty"`
	// Fields that must not equal the given value.
	NotEquals *RigAccountFilterEquals `json:"notEquals,omitempty"`
	// Fields that must be greater than the given value.
	GreaterThan *RigAccountFilterRange `json:"greaterThan,omitempty"`
	// Fields that must be less than the given value.
	SmallerThan *RigAccountFilterRange `json:"smallerThan,omitempty"`
	// Fields that must be greater than or equal to the given value.
	GreaterOrEqual *RigAccountFilterRange `json:"greaterOrEqual,omitempty"`
	// Fields that must be less than or equal to the given value.
	SmallerOrEqual *RigAccountFilterRange `json:"smallerOrEqual,omitempty"`
	// Fields that must be one of the given values.
	Contains *RigAccountFilterContains `json:"contains,omitempty"`
	// Fields that must not be one of the given values.
	NotContains *RigAccountFilterContains `json:"notContains,omitempty"`
	// Text fields that must match the given pattern.
	Like *RigAccountFilterLike `json:"like,omitempty"`
	// Text fields that must not match the given pattern.
	NotLike *RigAccountFilterLike `json:"notLike,omitempty"`
	// Fields that must be null.
	Null *RigAccountFilterNull `json:"null,omitempty"`
	// Fields that must not be null.
	NotNull *RigAccountFilterNull `json:"notNull,omitempty"`
	// Combine this filter's conditions with OR instead of AND.
	OrCondition bool `json:"orCondition,omitempty"`
	// Sub-filters combined with this one, so that AND and OR can be mixed to any
	// depth.
	NestedFilters []RigAccountFilter `json:"nestedFilters,omitempty"`
	// Relations with no row matching the given conditions. An empty one asks for
	// no related row at all.
	//
	// This is where a negation belongs when what you mean is "not": it negates
	// whether a matching related row exists, so a row with no related row at all
	// satisfies it. The negative operators above negate the comparison instead and
	// still require the related row to be there — "no related row called X" is
	// here, "a related row not called X" is NotEquals.
	Without *RigAccountFilterWithout `json:"without,omitempty"`
}

// RigAccountPage says which slice of a result to return, and in what order.
//
// The zero value is the first page at the repository's default size, in the
// table's configured order, which is what a caller who has not thought about
// it wants.
type RigAccountPage struct {
	Limit  int
	Offset int

	// OrderBy replaces the table's default ordering.
	OrderBy []RigAccountOrder
}

// RigAccountOrder is one clause of an ordering.
//
// Relation names the relation the column belongs to, and is empty for this
// table's own columns. The repository turns it into a left join, so a row
// whose related row is missing still appears — at one end of the order
// rather than not at all.
type RigAccountOrder struct {
	Relation string
	Column   string
	Desc     bool
}

// The orderings a RigAccount supports.
var (
	RigAccountOrderIDAsc                  = RigAccountOrder{Column: "id"}
	RigAccountOrderIDDesc                 = RigAccountOrder{Column: "id", Desc: true}
	RigAccountOrderTenantIDAsc            = RigAccountOrder{Column: "tenant_id"}
	RigAccountOrderTenantIDDesc           = RigAccountOrder{Column: "tenant_id", Desc: true}
	RigAccountOrderIdentityIDAsc          = RigAccountOrder{Column: "identity_id"}
	RigAccountOrderIdentityIDDesc         = RigAccountOrder{Column: "identity_id", Desc: true}
	RigAccountOrderCreatedAtAsc           = RigAccountOrder{Column: "created_at"}
	RigAccountOrderCreatedAtDesc          = RigAccountOrder{Column: "created_at", Desc: true}
	RigAccountOrderCreatedByAccountIDAsc  = RigAccountOrder{Column: "created_by_account_id"}
	RigAccountOrderCreatedByAccountIDDesc = RigAccountOrder{Column: "created_by_account_id", Desc: true}
	RigAccountOrderUpdatedAtAsc           = RigAccountOrder{Column: "updated_at"}
	RigAccountOrderUpdatedAtDesc          = RigAccountOrder{Column: "updated_at", Desc: true}
	RigAccountOrderUpdatedByAccountIDAsc  = RigAccountOrder{Column: "updated_by_account_id"}
	RigAccountOrderUpdatedByAccountIDDesc = RigAccountOrder{Column: "updated_by_account_id", Desc: true}
	RigAccountOrderDeletedAtAsc           = RigAccountOrder{Column: "deleted_at"}
	RigAccountOrderDeletedAtDesc          = RigAccountOrder{Column: "deleted_at", Desc: true}
	RigAccountOrderDeletedByAccountIDAsc  = RigAccountOrder{Column: "deleted_by_account_id"}
	RigAccountOrderDeletedByAccountIDDesc = RigAccountOrder{Column: "deleted_by_account_id", Desc: true}
	RigAccountOrderKindAsc                = RigAccountOrder{Column: "kind"}
	RigAccountOrderKindDesc               = RigAccountOrder{Column: "kind", Desc: true}
	RigAccountOrderRoleAsc                = RigAccountOrder{Column: "role"}
	RigAccountOrderRoleDesc               = RigAccountOrder{Column: "role", Desc: true}
	RigAccountOrderEmailAddressAsc        = RigAccountOrder{Column: "email_address"}
	RigAccountOrderEmailAddressDesc       = RigAccountOrder{Column: "email_address", Desc: true}
	RigAccountOrderDisplayNameAsc         = RigAccountOrder{Column: "display_name"}
	RigAccountOrderDisplayNameDesc        = RigAccountOrder{Column: "display_name", Desc: true}
	RigAccountOrderTimeZoneAsc            = RigAccountOrder{Column: "time_zone"}
	RigAccountOrderTimeZoneDesc           = RigAccountOrder{Column: "time_zone", Desc: true}
	RigAccountOrderIsActiveAsc            = RigAccountOrder{Column: "is_active"}
	RigAccountOrderIsActiveDesc           = RigAccountOrder{Column: "is_active", Desc: true}
	RigAccountOrderCreatedByAPIKeyIDAsc   = RigAccountOrder{Column: "created_by_api_key_id"}
	RigAccountOrderCreatedByAPIKeyIDDesc  = RigAccountOrder{Column: "created_by_api_key_id", Desc: true}
	RigAccountOrderUpdatedByAPIKeyIDAsc   = RigAccountOrder{Column: "updated_by_api_key_id"}
	RigAccountOrderUpdatedByAPIKeyIDDesc  = RigAccountOrder{Column: "updated_by_api_key_id", Desc: true}
	RigAccountOrderDeletedByAPIKeyIDAsc   = RigAccountOrder{Column: "deleted_by_api_key_id"}
	RigAccountOrderDeletedByAPIKeyIDDesc  = RigAccountOrder{Column: "deleted_by_api_key_id", Desc: true}
)

// RigAccountOrderCreatedByAccount orders a RigAccount by a column of its
// CreatedByAccount.
//
// Take the term from RigAccount's own orderings:
//
//	RigAccountOrderCreatedByAccount(RigAccountOrderIDDesc)
//
// The repository reaches it with a left join, so a RigAccount with no
// CreatedByAccount sorts to one end rather than vanishing. Only RigAccount's
// own columns can be used; an ordering that itself reaches across a relation
// is refused, because one join is where this stops.
func RigAccountOrderCreatedByAccount(o RigAccountOrder) RigAccountOrder {
	return RigAccountOrder{Relation: "CreatedByAccount", Column: o.Column, Desc: o.Desc}
}

// RigAccountOrderDeletedByAccount orders a RigAccount by a column of its
// DeletedByAccount.
//
// Take the term from RigAccount's own orderings:
//
//	RigAccountOrderDeletedByAccount(RigAccountOrderIDDesc)
//
// The repository reaches it with a left join, so a RigAccount with no
// DeletedByAccount sorts to one end rather than vanishing. Only RigAccount's
// own columns can be used; an ordering that itself reaches across a relation
// is refused, because one join is where this stops.
func RigAccountOrderDeletedByAccount(o RigAccountOrder) RigAccountOrder {
	return RigAccountOrder{Relation: "DeletedByAccount", Column: o.Column, Desc: o.Desc}
}

// RigAccountOrderUpdatedByAccount orders a RigAccount by a column of its
// UpdatedByAccount.
//
// Take the term from RigAccount's own orderings:
//
//	RigAccountOrderUpdatedByAccount(RigAccountOrderIDDesc)
//
// The repository reaches it with a left join, so a RigAccount with no
// UpdatedByAccount sorts to one end rather than vanishing. Only RigAccount's
// own columns can be used; an ordering that itself reaches across a relation
// is refused, because one join is where this stops.
func RigAccountOrderUpdatedByAccount(o RigAccountOrder) RigAccountOrder {
	return RigAccountOrder{Relation: "UpdatedByAccount", Column: o.Column, Desc: o.Desc}
}

// NewRigAccountFilterEquals builds an empty RigAccountFilterEquals to fill in.
func NewRigAccountFilterEquals() *RigAccountFilterEquals { return &RigAccountFilterEquals{} }

// NewRigAccountFilterRange builds an empty RigAccountFilterRange to fill in.
func NewRigAccountFilterRange() *RigAccountFilterRange { return &RigAccountFilterRange{} }

// NewRigAccountFilterContains builds an empty RigAccountFilterContains to fill
// in.
func NewRigAccountFilterContains() *RigAccountFilterContains { return &RigAccountFilterContains{} }

// NewRigAccountFilterLike builds an empty RigAccountFilterLike to fill in.
func NewRigAccountFilterLike() *RigAccountFilterLike { return &RigAccountFilterLike{} }

// NewRigAccountFilterNull builds an empty RigAccountFilterNull to fill in.
func NewRigAccountFilterNull() *RigAccountFilterNull { return &RigAccountFilterNull{} }

// NewRigAccountFilterWithout builds an empty RigAccountFilterWithout to fill
// in.
func NewRigAccountFilterWithout() *RigAccountFilterWithout { return &RigAccountFilterWithout{} }

// NewRigAccountFilter builds an empty filter, which matches every row the
// caller is allowed to see.
func NewRigAccountFilter() RigAccountFilter { return RigAccountFilter{} }
