// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"cmp"
	"context"
	"crypto/rand"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/simonjanss/rig/auth"
	"github.com/simonjanss/rig/auth/account"
	"github.com/simonjanss/rig/auth/authhttp"
	"github.com/simonjanss/rig/auth/identity"
	"github.com/simonjanss/rig/auth/oauth"
	"github.com/simonjanss/rig/auth/session"
	"github.com/simonjanss/rig/runtime/rigerr"
	"github.com/simonjanss/rig/runtime/serve"
	"github.com/simonjanss/rig/runtime/throttle"
)

// BasePath is where the authentication endpoints are mounted. Every route
// below it comes from rig/auth: /auth/login, /auth/refresh, and the rest.
const BasePath = "/auth"

// TenantHeader is the header a request names its tenant in.
const TenantHeader = "X-Tenant-Id"

// TenantQuery is the query parameter a request may name its tenant in. It
// travels in links and in logs, which is why it is rarely the right source in
// a deployment.
const TenantQuery = "tenant"

// Providers are the sign-in providers this configuration offers, in order, for
// a page that draws a button per name. A provider whose credentials are absent
// is not offered, so ask ConfiguredProviders for what this process actually
// has.
var Providers = []string{"google"}

// SigningKeyEnv holds the key that signs the state parameter. Empty generates
// one per process, which is fine for one and wrong for several: a callback may
// arrive at a different replica than the one that started the sign-in.
const SigningKeyEnv = "OAUTH_SIGNING_KEY"

// OriginScheme is the scheme a callback URL is built with. A provider compares
// that URL exactly, so this follows the configured origin rather than the
// request.
const OriginScheme = "http"

// BaseURLEnv is where the origin comes from, for the deployment that has to
// say which one this is. [BaseURL] reads it.
//
// A constant beside SigningKeyEnv rather than a string inside that function,
// so what a deployment has to set is readable off the package — and so the
// refusal for having not set it can name it.
const BaseURLEnv = "BASE_URL"

// BaseURL is this application's own origin, which a provider has registered as
// the prefix of its callback URL.
//
// It is a function rather than a constant because the environment has a say:
// the same binary is deployed at more than one origin, and the configuration
// cannot know which.
//
// What the configuration and the environment say, which is not the whole
// answer: [Hooks.OAuth] carries a BaseURL of its own, and [Config] prefers it
// without asking here at all. This is what a project that supplied none gets.
func BaseURL() (string, error) {
	return strings.TrimRight(cmp.Or(os.Getenv(BaseURLEnv), "http://localhost:8082"), "/"), nil
}

// Hooks are what a configuration file cannot hold: the functions this
// application has to supply, and nothing else.
//
// Everything with a fixed answer is in rig.yaml and already applied — the
// lifetimes, the rotation leeway, the rate limits, the password policy, which
// providers exist. What is left here is behaviour: who holds a permission,
// where mail goes, what a new tenant needs. Each is optional unless the
// configuration makes it necessary, and Config says so rather than failing
// later.
type Hooks struct {
	// Grants answers what an account may do, and is required: every generated
	// handler checks a permission, so without this nobody holds one and every
	// endpoint answers 403.
	//
	// rig derives the permission keys from the schema — PermissionKeys(), beside
	// this, is the whole catalogue — and generates the check. Deciding who holds
	// which is this application's own model.
	Grants authhttp.Grants

	// Notifier sends the mail a flow needs: a reset link, a verification link, an
	// invitation. Nil sends none, and it does so silently — account.NoNotifier
	// is substituted and answers success from every method, so in production
	// nobody can reset a password and nothing anywhere says so.
	Notifier account.Notifier

	// Mail is the queue for those links, and it is off by default.
	//
	// Off, a link is minted in the request that asked for it and handed straight
	// to the Notifier, so a provider having a bad minute fails that request,
	// spends the caller's rate-limit budget, and kills a token that was already
	// minted. On, the link is written to the database in the same transaction and
	// sent by AuthMailDispatcher — which an operator's cron has to run. Turning
	// it on without that entry is turning mail off.
	//
	// The trade in the other direction is latency: a queued reset mail arrives up
	// to one dispatch interval late, where inline it went out inside the request.
	Mail auth.MailOptions

	// Tenants is this application's policy for making one: who may, what a name
	// may be, how a slug is derived, and what else a new tenant needs in the
	// transaction that made it. The zero value lets anybody signed in make one
	// called anything.
	//
	// rig owns the mechanism — the row, the first account, the transaction —
	// because that part is the same everywhere and getting it half right leaves a
	// tenant nobody can reach.
	Tenants account.TenantOptions

	// AllowIdentity decides whether somebody nobody here has ever heard of may
	// become an identity, and it is the one gate on that question: every path that
	// would create a person asks it — a provider sign-in, a mailed code, an
	// invitation and a direct provision alike. So this deployment cannot acquire
	// an ungated door by turning on a sign-in method it did not have before.
	//
	// It is asked about strangers and nobody else. By the time it runs rig has
	// established that the address has no provider link and no identity of its
	// own, so an existing member — and somebody adding a second provider to an
	// account they already have — have both been admitted without consulting it.
	// Write one rule, not a chain of them.
	//
	// Leave it nil and rig uses auth.allowed_identity_domains from rig.yaml, which
	// is "example.com", "acme.test". Setting this replaces that rule wholesale
	// rather than adding to it: two rules merged is a rule nobody can read. Call
	// identity.DomainAllowed from inside your own gate if you want both.
	AllowIdentity identity.Gate

	// OnRegistered runs inside the transaction that creates somebody rig has never
	// seen — asking for a sign-in code with a new address — and an error rolls
	// the whole thing back. The ordinary body is accounts.Provision into a starter
	// tenant, or accounts.Invite to leave one waiting in the picker they land in.
	// Nil creates the person and nothing else.
	OnRegistered func(context.Context, *account.Service, account.Registered) error

	// OnJoined runs inside the transaction that accepts an invitation, after the
	// account exists and before the session is issued, and an error rolls the
	// acceptance back.
	//
	// It is where a new member's roles and rows are seeded. Provision is called by
	// your own code, so what else a new member needs is your next line; accepting
	// an invitation is called by rig's handler, and this is that line.
	OnJoined func(context.Context, account.Joined) error

	// OnSessionRefresh replaces a session's payload every time it is refreshed.
	// Nil carries the previous one forward unchanged.
	//
	// Not for permissions: it is written at sign-in and again only at refresh, so
	// anything here outlives its own revocation by up to the refresh lifetime.
	// Grants answers that question, per request.
	OnSessionRefresh func(context.Context, *session.Token) (json.RawMessage, error)

	// OnError renders a failure. Nil uses this package's own error mapper, so an
	// authentication failure is shaped like every other failure this API returns.
	OnError func(w http.ResponseWriter, r *http.Request, err error)

	// RequestID labels an authentication request, exactly as [Server.RequestID]
	// labels every other one, and nil means the same default: the caller's own
	// X-Request-Id, if it sent one worth trusting.
	//
	// It is a second field rather than read from the Server for the reason Logger
	// is: this configuration is built first, and what it produces is what
	// Server.Auth is then set to. Set both or neither — a project whose resource
	// routes label a request one way and whose sign-in labels it another has two
	// answers to the question the label exists to settle.
	RequestID func(*http.Request) string

	// Logger records why an authentication request failed. Nil uses
	// [log/slog.Default].
	//
	// Give it the same logger as [Server.Logger]. These routes are mounted on the
	// same mux and answer in the same shape, and the cause of a 500 from signing
	// in should not be the one line that goes somewhere else.
	//
	// It is a second field rather than read from the Server because the order
	// forbids it: this configuration is built first, and what it produces is what
	// Server.Auth is then set to.
	Logger *slog.Logger

	// OAuth is what a provider sign-in needs beyond the configuration.
	OAuth OAuthHooks

	// Now is the clock, for tests.
	Now func() time.Time
}

// OAuthHooks are the provider decisions that are code.
type OAuthHooks struct {
	// OnSignIn finishes a provider sign-in. Nil issues a session and answers with
	// the same body a password login does.
	//
	// A browser flow usually wants a cookie and a redirect instead, and that
	// depends on what the client is — a single-page application, a
	// server-rendered one, a mobile app catching a deep link — which is why rig
	// will not choose.
	//
	// Whatever it does, it has to handle in.TenantID being the nil UUID: that is a
	// sign-in whose tenant was not known before the redirect, and issuing a
	// session from that field would issue one into a tenant that does not exist.
	// Nil handles it the way a login does — an identity token and the tenant
	// list, for the picker to take over.
	OnSignIn func(w http.ResponseWriter, r *http.Request, in oauth.SignIn) error

	// OnError renders a provider sign-in that did not finish, and it is a
	// different question from the API's own error shape.
	//
	// The two provider routes are the only ones here a person reaches with their
	// address bar. Every other route is called by script, which can read a status
	// and a body; a browser mid-navigation renders whatever came back as a
	// document, so rig's default is a bare text/plain page on this API's origin
	// with no way back to the application.
	//
	// The oauth.Failure it gets says which of the ways this was — cancelled at
	// the consent screen, an expired state cookie, an address the provider has not
	// verified — so a front end can be sent to its own sign-in page with a code
	// it has copy for. Never render Failure.ProviderError: it is text anybody can
	// write. Never render Failure.Error() on reason internal either: that one is a
	// seal or a store failure, and rig's own default answers "something went
	// wrong" rather than show it. Nil keeps the default.
	OnError func(w http.ResponseWriter, r *http.Request, f *oauth.Failure)

	// Origin overrides the configured origin for one request, for an application
	// served at several. Setting auth.oauth.origin_from_host in rig.yaml is the
	// declarative form of the usual answer.
	Origin func(r *http.Request) string

	// BaseURL is this application's own origin, and takes precedence over
	// everything rig.yaml said about one.
	//
	// Empty asks [BaseURL], which is what auth.oauth and the environment resolved,
	// and that is the ordinary case. This is for the origin that arrives some
	// other way: a test serving on an ephemeral port, or a deployment handed its
	// configuration rather than given it in its own environment. A whole origin
	// with a scheme, matching what the provider has registered exactly — a
	// trailing slash is trimmed and nothing else is.
	//
	// Not [OAuthHooks.Origin], which answers per request. This is the one origin
	// the callback routes are built from, and it has to exist even where Origin
	// overrides it.
	BaseURL string

	// SigningKey signs the cookie that carries the state and the PKCE verifier
	// across a sign-in's round trip. At least 32 bytes, and the same bytes in
	// every replica.
	//
	// Empty reads SigningKeyEnv, which is what a deployment ordinarily does. This
	// is for the key that lives somewhere os.Getenv cannot reach: a secret
	// manager, a mounted file, or a test that would rather not write to the
	// process it is running in.
	SigningKey []byte

	// Credentials are the client id and secret for each provider this
	// configuration offers, for an application whose secrets do not arrive in its
	// environment. A zero field reads that provider's pair from there, which is
	// the ordinary case and needs nothing written here.
	Credentials OAuthCredentials

	// Extra are providers this application builds itself: an in-house identity
	// server, or a stand-in served by the application during development. They are
	// appended to the configured ones.
	Extra []oauth.Provider

	// ReturnTo are further origins a finished sign-in may land on, added to the
	// configured auth.oauth.allowed_return_to.
	//
	// For the deployment whose set is not fixed. An application with a tenant per
	// subdomain has one origin per tenant, and a list in a file cannot name a
	// tenant that was created this morning.
	ReturnTo []string
}

// OAuthCredentials are what each provider this application offers knows it by.
//
// A zero field reads that provider's pair from the environment, which is what
// rig.yaml names it for and still the ordinary answer. What this is for is the
// id and secret that arrive some other way — a secret manager, a mounted
// file, a test fake — and for an application whose own configuration would
// rather name what it needs than leave it to a README.
//
// The only field is Google, because that is the one provider auth.oauth lists.
type OAuthCredentials struct {
	// Google's pair. Empty reads GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET.
	Google OAuthClient
}

// OAuthClient is one provider's registration: the id it knows this application
// by, and the secret that proves this application is the one asking.
//
// Each is read on its own, so an id can come from the environment and a secret
// from here — which is the shape a project keeping only its secrets in a
// manager already has, and the reason this is two fields rather than a pair
// taken whole. What it accepts is the other order of that mistake: an id
// supplied here beside a stale secret still in somebody's shell makes a pair
// the provider rejects at its token endpoint, naming neither half.
type OAuthClient struct {
	ID     string
	Secret string
}

// New assembles the authentication foundation over a pool.
//
// Hand the result to the generated API as api.Server.Auth and both halves are
// wired at once: every handler identifies its caller with the same
// verification that issued the token, and /auth/* is mounted on the same mux.
func New(pool *pgxpool.Pool, h Hooks) (*auth.Auth, error) {
	cfg, err := Config(pool, h)
	if err != nil {
		return nil, err
	}
	return auth.New(cfg)
}

// AttachAuth registers the shutdown for the authentication foundation, which
// is the whole of what a main function does with it beyond mounting it:
//
//	api.AttachAuth(app, front)
//
// What is closed is the invalidation channel the caches listen on, which is a
// connection and a goroutine of its own. A project with no cache configured
// closes nothing, and that is exactly what makes this easy to leave out: it
// costs a connection rather than correctness, on some later day, in a main
// function nobody is reading any more.
//
// A close step rather than a drain, because nothing is in flight. A listener
// that has stopped reports itself as not live, and a cache that is not live
// reads through and holds nothing — so the requests still being answered are
// answered correctly, from the database.
func AttachAuth(app *serve.App, a *auth.Auth) {
	app.CloseWithin("auth", authShutdown, a.Close)
}

// Config is the configuration rig.yaml describes, with the hooks folded in.
//
// Every value in it was resolved when the configuration was read, so this
// function makes no decisions: it is the same numbers the specification
// documents and the same ones a generated client is built against.
func Config(pool *pgxpool.Pool, h Hooks) (auth.Config, error) {
	if pool == nil {
		return auth.Config{}, errors.New("api: no pool: the authentication foundation lives in the database")
	}
	// Refused at construction rather than at the first request. Every generated
	// handler checks a permission, so a nil Grants is an API where every endpoint
	// answers 403 — a failure that looks like a policy decision.
	if h.Grants == nil {
		return auth.Config{}, errors.New("api: no Grants: every endpoint checks a permission, so nobody would hold one")
	}
	// A code nobody sends is a door nobody can open, and with no provider
	// configured it is the only door. Refused here rather than at the first
	// sign-in, because there is nothing in a running system that would point at
	// the configuration.
	if h.Notifier == nil {
		return auth.Config{}, errors.New("api: no Notifier, but auth.email_code.enabled is set, so every code would be minted and then dropped")
	}

	cfg := auth.Config{
		Pool:     pool,
		BasePath: BasePath,
		Tenant:   tenant(pool, h),

		AccessTTL:          10 * time.Minute,
		RefreshTTL:         12 * time.Hour,
		RememberTTL:        30 * 24 * time.Hour,
		RotationLeeway:     30 * time.Second,
		IdentitySessionTTL: 30 * time.Minute,

		// Verifying a session and verifying an API key are the two reads rig makes on
		// behalf of every caller, and this is what stops them being a row read each.
		//
		// Not a time-to-live over authentication, which would be a revoked session
		// that keeps working. The lifetime below is the backstop: a revocation
		// publishes on the transaction that performed it, over a Postgres channel
		// every replica listens on, so the ordinary case is that everybody has
		// forgotten by the time that transaction commits. A replica that lost the
		// channel stops caching rather than serving what it cannot withdraw.
		//
		// Every number came from `cache:` in rig.yaml.
		Cache: auth.CacheOptions{
			Enabled:    true,
			TTL:        30 * time.Second,
			Channel:    "rig_cache",
			MaxEntries: 50000,
			// The one line anybody reads when this stops working. The fallback — reading
			// the row again — is correct and silent, so nothing else about the server
			// would say so.
			Logger: h.Logger,
		},

		EmailCode: auth.EmailCodeOptions{
			Enabled:           true,
			Length:            6,
			TTL:               10 * time.Minute,
			MaxAttempts:       3,
			AllowProvisioning: true,
		},

		AllowTenantCreation:  true,
		RequireVerifiedEmail: false,
		AllowIdentity:        allowIdentity(h),
		Tenants:              h.Tenants,
		OnRegistered:         h.OnRegistered,
		OnJoined:             h.OnJoined,

		Grants:           h.Grants,
		Notifier:         h.Notifier,
		Mail:             h.Mail,
		OnSessionRefresh: h.OnSessionRefresh,
		OnError:          h.OnError,
		Limits:           limits(),
		LogRetention:     90 * 24 * time.Hour,
		Now:              h.Now,
	}

	// The server the two error writers below report through.
	//
	// One literal, shared, because it is the answer to "what does a request look
	// like" and a second copy of it is a second answer: the one this replaced
	// named no caller, no client revision, and a request identifier nothing
	// validated.
	//
	// RequestIDHeader is on it because it is what decides which header is read,
	// and a Server without it reads the default one — which is the right header
	// in most projects and the wrong one in exactly the projects that said so in
	// rig.yaml.
	srv := Server{Logger: h.Logger, RequestID: h.RequestID, RequestIDHeader: RequestIDHeader}

	// Providers are wired only when this process has credentials for at least one.
	// A deployment that has none mounts no provider routes, which is better than
	// mounting a button that cannot work.
	configured, err := ConfiguredProviders(h.OAuth)
	if err != nil {
		return auth.Config{}, err
	}
	if len(configured) > 0 {
		// The origin this application supplied, if it did. BaseURL is what rig.yaml
		// and the environment resolved, and it is not asked at all when the field
		// answers — so a deployment that named only auth.oauth.base_url_env and
		// fills this in from Go never meets BaseURL's refusal.
		//
		// The two rules rig checked on auth.oauth.base_url when it read the file,
		// applied to the one origin it could not see: a trailing slash is trimmed, and
		// an origin with no scheme is refused rather than built into a callback URL
		// that every provider rejects without saying why.
		base := strings.TrimRight(h.OAuth.BaseURL, "/")
		switch {
		case base == "":
			if base, err = BaseURL(); err != nil {
				return auth.Config{}, err
			}
		case !strings.HasPrefix(base, "http://") && !strings.HasPrefix(base, "https://"):
			return auth.Config{}, errors.New("api: Hooks.OAuth.BaseURL must be an absolute origin, for example https://app.example.com: a provider compares the callback URL built from it exactly")
		}
		key, err := signingKey(h.OAuth)
		if err != nil {
			return auth.Config{}, err
		}
		// allow_joining, set apart from allow_provisioning: one of the two doors a
		// provider sign-in opens is shut, and nil here would mean the other one's
		// answer.
		allowJoining := false
		cfg.OAuth = auth.OAuth{
			Providers:         configured,
			BaseURL:           base,
			Origin:            h.OAuth.Origin,
			SigningKey:        key,
			StateTTL:          10 * time.Minute,
			AllowProvisioning: true,
			AllowJoining:      &allowJoining,
			AllowedReturnTo:   append([]string{"http://localhost:8082"}, h.OAuth.ReturnTo...),
			// Plain HTTP, so the __Host- cookie a browser would insist on is
			// unavailable. Never set anywhere real.
			Insecure: true,
			OnSignIn: h.OAuth.OnSignIn,
			OnError:  h.OAuth.OnError,
			// And the same error writer every other route in this server uses, so a
			// refused provider sign-in is classified, answered and logged the way a
			// refused login is. These two routes used to write no line at any level: a
			// failed sign-in existed in the authentication log and nowhere else.
			//
			// Behind Hooks.OAuth.OnError, and behind the front-end redirect below when
			// there is one, because those answer what a person sees and this answers where
			// the line goes.
			Fail: func(w http.ResponseWriter, r *http.Request, err error) {
				fail(srv, w, r, requestContext(srv, r), err)
			},
		}
	}

	// So an authentication failure looks like every other failure this API
	// returns, and is recorded the same way. Through fail rather than straight to
	// the mapper, because the line that says why a 500 happened is written there
	// — an auth route is the one place a project cannot reach to add it, and it
	// is also where the interesting 500s are.
	//
	// Through requestContext rather than a literal of its own, for the same reason
	// one step out: a literal here is a second place deciding what a request looks
	// like, and the two had already drifted — this one named no caller, no
	// client revision, and a request identifier nothing validated.
	if cfg.OnError == nil {
		cfg.OnError = func(w http.ResponseWriter, r *http.Request, err error) {
			fail(srv, w, r, requestContext(srv, r), err)
		}
	}

	return cfg, nil
}

// tenant resolves which tenant a request is for, from query, then header.
//
// It is consulted only where the tenant cannot be known some other way: a
// sign-in, a password reset, the start of a provider flow. Everything else
// takes its tenant from the token.
//
// A request that names none is an ordinary answer rather than an error. A
// single sign-in page cannot know which tenants an address belongs to before
// the password has been checked, so uuid.Nil means unspecified and login
// resolves it.
func tenant(pool *pgxpool.Pool, h Hooks) func(*http.Request) (uuid.UUID, error) {
	return func(r *http.Request) (uuid.UUID, error) {
		if raw := r.URL.Query().Get(TenantQuery); raw != "" {
			id, err := uuid.Parse(raw)
			if err != nil {
				return uuid.Nil, rigerr.BadRequest("%s is not a valid identifier", TenantQuery)
			}
			return id, nil
		}
		if raw := r.Header.Get(TenantHeader); raw != "" {
			id, err := uuid.Parse(raw)
			if err != nil {
				// Present and malformed is a caller getting it wrong, which is
				// different from leaving it out.
				return uuid.Nil, rigerr.BadRequest("%s is not a valid identifier", TenantHeader)
			}
			return id, nil
		}
		return uuid.Nil, nil
	}
}

// limits are the rate limits from rig.yaml, counted in the database so two
// replicas cannot disagree about how many times a password has been tried and
// a restart does not clear somebody's lockout.
//
// The configuration sets how many and over how long. Which event each limit
// counts, and what clears it, is rig's — a limit counting something else
// under the same name would not be the same limit.
func limits() throttle.Defaults {
	d := throttle.Standard()
	d.LoginByEmail.Max, d.LoginByEmail.Window = 5, 15*time.Minute
	d.LoginByIP.Max, d.LoginByIP.Window = 50, 15*time.Minute
	d.EmailCodeRequest.Max, d.EmailCodeRequest.Window = 200, time.Hour
	d.EmailCodeByIP.Max, d.EmailCodeByIP.Window = 100, time.Hour
	d.VerificationResend.Max, d.VerificationResend.Window = 5, time.Hour
	d.Refresh.Max, d.Refresh.Window = 60, time.Minute
	d.APIKeyFailures.Max, d.APIKeyFailures.Window = 20, time.Minute
	d.InvitationPreview.Max, d.InvitationPreview.Window = 60, time.Hour
	return d
}

// allowIdentity is the gate on who may become a person here.
//
// auth.allowed_identity_domains in rig.yaml is sugar over the same hook rather
// than a mechanism beside it, so it is a Gate like any other — and a hook
// the application set wins wholesale. Merging the two would mean a refusal
// nobody could trace to a rule.
//
// An administrator is not asked: an invitation or a provision goes through
// whatever the list says, because somebody already here typed that address in.
func allowIdentity(h Hooks) identity.Gate {
	if h.AllowIdentity != nil {
		return h.AllowIdentity
	}
	return identity.AllowDomains("example.com", "acme.test")
}

// AuthLogPruner deletes authentication log entries older than 90d, which is
// `auth.log_retention` in rig.yaml.
//
// A task rather than a goroutine, so it is a subcommand in a cron job rather
// than something every replica does at once to the table the whole
// authentication path writes to. Register it in serve.Config.Tasks and run
// `<binary> prune-auth-log`.
//
// The window is checked against the rate limits before the server starts,
// because those limits are counted from this table: pruning inside one of
// their windows would clear a lockout by deleting the failures it counts.
func AuthLogPruner(front *auth.Auth) serve.Task {
	return func(ctx context.Context, _ *pgxpool.Pool) error {
		_, err := front.PruneLog(ctx)
		return err
	}
}

// AuthMailDispatcher is the guarantee behind every link rig mints: it sends
// what a request queued, retries what a provider refused, and gives back the
// claims of a process that died mid-pass. It prunes the deliveries that are
// done in the same pass, the way the notification dispatcher does.
//
// A subcommand rather than a goroutine, so it is a cron job rather than
// something racing itself in every replica. Register it in serve.Config.Tasks
// and run `<binary> dispatch-auth-mail`.
//
// **With Hooks.Mail.Queue set and no cron entry for this, links are queued and
// never sent.** With the queue off it claims nothing and returns, so
// registering it either way costs nothing.
//
// The logger is where each pass's report goes — every count including the
// zeros, because a pass that sent nothing is the ordinary case and the absence
// of a line cannot be told from the job not running. A nil logger is not
// silence: it is slog.Default, the same reading every other Logger in rig
// gives it, which for a cron job is the terminal it was started from.
//
// At info, because this is the whole output of a run that happens when nobody
// is watching and slog.Default drops debug — a level that has to have been
// turned on in advance would make this silent, which is the one thing the line
// exists to prevent.
func AuthMailDispatcher(front *auth.Auth, logger *slog.Logger) serve.Task {
	if logger == nil {
		logger = slog.Default()
	}
	return func(ctx context.Context, _ *pgxpool.Pool) error {
		report, err := front.DispatchMail(ctx)
		logger.InfoContext(ctx, "authentication mail dispatched", "counts", report.String())
		if err != nil {
			return err
		}
		pruned, err := front.PruneMail(ctx)
		logger.InfoContext(ctx, "authentication mail pruned", "count", pruned)
		return err
	}
}

// signingKey is the key that signs the cookie carrying the state and the PKCE
// verifier across a sign-in's round trip.
//
// At least 32 bytes, because it is a secret, and it has to be the same key in
// every replica: a callback may arrive at a different one than the one that
// started the sign-in, and a key invented per process is a sign-in that fails
// whenever a load balancer is doing its job.
//
// Hooks.OAuth.SigningKey first, then OAUTH_SIGNING_KEY, which is the ordinary
// way a deployment hands one over.
func signingKey(h OAuthHooks) ([]byte, error) {
	// A key this application named and got wrong, reported as that rather than as
	// an absence. It is not replaced by the variable, and where insecure is set it
	// is not replaced by a development key either: substituting for a value
	// somebody stated is how a sign-in works in one replica and not the next.
	if n := len(h.SigningKey); n > 0 && n < 32 {
		return nil, fmt.Errorf("api: Hooks.OAuth.SigningKey holds %d bytes and needs at least 32: it signs the OAuth state parameter, and every replica has to use the same one", n)
	}
	key := h.SigningKey
	if len(key) == 0 {
		key = []byte(os.Getenv(SigningKeyEnv))
	}
	switch {
	case len(key) >= 32:
		return key, nil
	case len(key) == 0:
		// auth.oauth.insecure is set, which says this is local development: one
		// process serves everything and there is no replica to share a key with.
		// Reached only when nothing supplied one at all — a key this short is a
		// mistake rather than an absence, and gets the error below.
		key = make([]byte, 32)
		if _, err := rand.Read(key); err != nil {
			return nil, fmt.Errorf("api: generate a development signing key: %w", err)
		}
		return key, nil
	}
	return nil, errors.New("api: a signing key of at least 32 bytes is required: set Hooks.OAuth.SigningKey or OAUTH_SIGNING_KEY — it signs the OAuth state parameter, and every replica has to use the same one")
}

// ConfiguredProviders are the providers this process has credentials for.
//
// A client secret is not configuration: it is a secret, so rig.yaml names the
// environment variable and this reads it. [OAuthHooks.Credentials] is read
// first, for an application that holds its secrets somewhere else, and a
// provider named in neither place is skipped rather than mounted broken —
// which is what lets one binary offer Google in a deployment and nothing at
// all on a laptop. A provider marked required refuses to start instead,
// whichever of the two it was waiting for.
//
// Exported so a sign-in page can draw a button per provider that actually
// works, rather than one per provider somebody hoped for.
func ConfiguredProviders(h OAuthHooks) ([]oauth.Provider, error) {
	out := make([]oauth.Provider, 0, 2)

	if id, secret := cmp.Or(h.Credentials.Google.ID, os.Getenv("GOOGLE_CLIENT_ID")), cmp.Or(h.Credentials.Google.Secret, os.Getenv("GOOGLE_CLIENT_SECRET")); id != "" && secret != "" {
		out = append(out, oauth.Google(id, secret))
	}

	return append(out, h.Extra...), nil
}
