// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"strings"

	"github.com/google/uuid"
	"github.com/simonjanss/rig/examples/auth/internal/model"
	"github.com/simonjanss/rig/runtime/rigerr"
	"github.com/simonjanss/rig/runtime/tenancy"
)

// A page of Notes.
type NoteListResponse struct {
	// The rows in this page.
	//
	// Pointers, because that is what the repository returns and copying every row
	// to change that would be work nobody asked for.
	Data []*model.Note `json:"data"`
	// Where this page sits in the full result set.
	Pagination Pagination `json:"pagination"`
}

// Query parameters for Note.List.
type NoteListQuery struct {
	// Maximum rows to return.
	Limit int `json:"limit"`
	// Rows to skip before the first returned row.
	Offset int `json:"offset"`
	// How wide to read: own for the notes the caller created, which is the
	// default, or all for every one in the tenant. Asking for all requires the
	// note.read.all permission and is refused without it, rather than quietly
	// answering with fewer rows.
	Scope tenancy.Scope `json:"scope"`
}

// Query parameters for Note.Search.
type NoteSearchQuery struct {
	// Maximum rows to return.
	Limit int `json:"limit"`
	// Rows to skip before the first returned row.
	Offset int `json:"offset"`
	// How wide to read: own for the notes the caller created, which is the
	// default, or all for every one in the tenant. Asking for all requires the
	// note.read.all permission and is refused without it, rather than quietly
	// answering with fewer rows.
	Scope tenancy.Scope `json:"scope"`
}

// The request body for Note.Search.
type NoteSearchBody struct {
	// Conditions rows must satisfy.
	Filter model.NoteFilter `json:"filter"`
}

// NoteSearchBodyError says what was wrong with each field of a NoteSearchBody.
//
// Its shape is the body's shape, so a client can attach every message to the
// field it is about without matching on strings. A member is nil when that
// field was fine, and the whole value is nil when the body was. It is what the
// 422 carries, and returning one from Note.Search is how that endpoint refuses
// a field rather than a request.
type NoteSearchBodyError struct {
	// Conditions rows must satisfy.
	Filter *rigerr.FieldError `json:"filter,omitempty"`

	// Entity is a problem with the body as a whole rather than with one field.
	Entity *rigerr.FieldError `json:"entity,omitempty"`
}

// Empty reports whether anything went wrong. A validator that found nothing
// returns nil rather than one of these.
func (e *NoteSearchBodyError) Empty() bool {
	if e == nil {
		return true
	}

	return e.Filter == nil && e.Entity == nil
}

// Error implements error. The sentence is for logs and for a person; the
// structure above is what a client acts on.
func (e *NoteSearchBodyError) Error() string {
	var parts []string
	if e.Filter != nil {
		parts = append(parts, "filter "+e.Filter.Error())
	}
	if e.Entity != nil {
		parts = append(parts, e.Entity.Error())
	}

	return "the request is not valid: " + strings.Join(parts, "; ")
}

// ErrorCode implements [rigerr.Coder]: the request was understood and its
// content is what is wrong, which is 422 and not 400.
func (e *NoteSearchBodyError) ErrorCode() rigerr.Code { return rigerr.CodeUnprocessableEntity }

// ErrorFields implements [rigerr.FieldReporter], which is how the HTTP layer
// finds this and answers with it rather than with prose.
func (e *NoteSearchBodyError) ErrorFields() any { return e }

// Query parameters for Note.ListDeleted.
type NoteListDeletedQuery struct {
	// Maximum rows to return.
	Limit int `json:"limit"`
	// Rows to skip before the first returned row.
	Offset int `json:"offset"`
	// How wide to read: own for the notes the caller created, which is the
	// default, or all for every one in the tenant. Asking for all requires the
	// note.read.all permission and is refused without it, rather than quietly
	// answering with fewer rows.
	Scope tenancy.Scope `json:"scope"`
}

// Path parameters for Note.Delete.
type NoteDeletePath struct {
	// Identifier of the Note.
	ID uuid.UUID `json:"id"`
}

// Path parameters for Note.Get.
type NoteGetPath struct {
	// Identifier of the Note.
	ID uuid.UUID `json:"id"`
}

// Query parameters for Note.Get.
type NoteGetQuery struct {
	// How wide to read: own for the notes the caller created, which is the
	// default, or all for every one in the tenant. Asking for all requires the
	// note.read.all permission and is refused without it, rather than quietly
	// answering with fewer rows.
	Scope tenancy.Scope `json:"scope"`
}

// Path parameters for Note.Update.
type NoteUpdatePath struct {
	// Identifier of the Note.
	ID uuid.UUID `json:"id"`
}

// Path parameters for Note.Restore.
type NoteRestorePath struct {
	// Identifier of the Note.
	ID uuid.UUID `json:"id"`
}
