// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

// Package api is the generated API layer: the wire types, the interfaces your
// service layer implements, and a working default implementation of each.
// Business logic belongs in the service layer, not here: every .gen.go file in
// this package is rewritten whenever the schema changes.
package api

import (
	"github.com/simonjanss/rig/runtime/apibase"
	"github.com/simonjanss/rig/runtime/apirev"
	"github.com/simonjanss/rig/runtime/rigerr"
	"github.com/simonjanss/rig/runtime/tenancy"
)

// Revision is the date this API surface last changed, as YYYY-MM-DD.
//
// It is not a build stamp: it moves when the surface moves and not when
// somebody regenerates, so two clients built a month apart against an
// unchanged API report the same thing — because they are the same thing.
// `rig generate` records it in .rig/revision.json, which is committed.
//
// Empty when the project has never generated with a revision recorded.
const Revision = "2026-08-24"

// RevisionHeader carries the revision in both directions: what the caller was
// built against on the way in, what this server was generated from on the way
// out.
const RevisionHeader = "API-Revision"

// serverRevision is [Revision] as a value, parsed once. Unknown for a project
// that has never generated with a revision recorded, which reads as "nobody is
// behind this server" rather than as an error.
var serverRevision, _ = apirev.Parse(Revision)

// Request is everything a handler received.
//
// Each part is a separate type parameter, and an operation that has no path
// parameters uses struct{} for that slot. That is deliberate: the signature
// says what an endpoint takes, so reaching for something it does not have is a
// compile error rather than a nil check.
type Request[Path, Query, Body any] = apibase.Request[Path, Query, Body]

// RequestContext is the request's own metadata: how it was labelled, what
// matched it, and what the caller was built against.
type RequestContext = apibase.RequestContext

// NewRequest builds a request. The server calls it; it is exported so a test
// can call a service method directly without going through HTTP.
func NewRequest[Path, Query, Body any](claims tenancy.Claims, path Path, query Query, body Body, rc RequestContext) Request[Path, Query, Body] {
	return apibase.NewRequest(claims, path, query, body, rc)
}

// NewContext carries a request's metadata down to everything the service
// method calls, so a validator or a hook — which are handed a context and
// nothing else — can ask what the caller was built against.
var NewContext = apibase.NewContext

// RequestContextFrom reads back what [NewContext] carried, and reports false
// for a context that never went through a handler.
var RequestContextFrom = apibase.RequestContextFrom

// caller is the claims a read hook is handed, or nil when the request carried
// none.
var caller = apibase.Caller

// ErrorCode is the machine-readable reason a request failed. Clients switch on
// this rather than on the status, because three unrelated failures share a
// status and none of them share a code.
type ErrorCode = rigerr.Code

// The codes a client may see.
const (
	ErrorCodeBadRequest           ErrorCode = rigerr.CodeBadRequest
	ErrorCodeUnauthorized         ErrorCode = rigerr.CodeUnauthorized
	ErrorCodeForbidden            ErrorCode = rigerr.CodeForbidden
	ErrorCodeNotFound             ErrorCode = rigerr.CodeNotFound
	ErrorCodeConflict             ErrorCode = rigerr.CodeConflict
	ErrorCodeUnprocessableEntity  ErrorCode = rigerr.CodeUnprocessableEntity
	ErrorCodeRateLimited          ErrorCode = rigerr.CodeRateLimited
	ErrorCodeTooLarge             ErrorCode = rigerr.CodeTooLarge
	ErrorCodeUnsupportedMediaType ErrorCode = rigerr.CodeUnsupportedMediaType
	ErrorCodeUpgradeRequired      ErrorCode = rigerr.CodeUpgradeRequired
	ErrorCodeInternal             ErrorCode = rigerr.CodeInternal
)

// Returned whenever a request fails.
type Error struct {
	// Machine-readable reason the request failed.
	Code ErrorCode `json:"code"`
	// Human-readable explanation. Not intended for clients to parse.
	Message string `json:"message"`
	// Identifier of this request, for correlating with server logs.
	RequestID string `json:"requestId,omitempty"`
	// Present when the failure was validation. It is shaped like the request body
	// that failed — one member per field, holding the problem with that field
	// — so a client can put each message beside the control it belongs to.
	Fields any `json:"fields,omitempty"`
}

// Where the returned page sits within the full result set.
type Pagination struct {
	// Number of rows skipped before this page.
	Offset int `json:"offset"`
	// Maximum number of rows in this page.
	Limit int `json:"limit"`
	// Total number of rows matching the query, ignoring pagination.
	Total int64 `json:"total"`
}
