// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"strings"

	"github.com/google/uuid"
	"github.com/simonjanss/rig/examples/auth_oauth/internal/model"
	"github.com/simonjanss/rig/runtime/rigerr"
)

// A page of Bookmarks.
type BookmarkListResponse struct {
	// The rows in this page.
	//
	// Pointers, because that is what the repository returns and copying every row
	// to change that would be work nobody asked for.
	Data []*model.Bookmark `json:"data"`
	// Where this page sits in the full result set.
	Pagination Pagination `json:"pagination"`
}

// Query parameters for Bookmark.List.
type BookmarkListQuery struct {
	// Maximum rows to return.
	Limit int `json:"limit"`
	// Rows to skip before the first returned row.
	Offset int `json:"offset"`
}

// Query parameters for Bookmark.Search.
type BookmarkSearchQuery struct {
	// Maximum rows to return.
	Limit int `json:"limit"`
	// Rows to skip before the first returned row.
	Offset int `json:"offset"`
}

// The request body for Bookmark.Search.
type BookmarkSearchBody struct {
	// Conditions rows must satisfy.
	Filter model.BookmarkFilter `json:"filter"`
}

// BookmarkSearchBodyError says what was wrong with each field of a
// BookmarkSearchBody.
//
// Its shape is the body's shape, so a client can attach every message to the
// field it is about without matching on strings. A member is nil when that
// field was fine, and the whole value is nil when the body was. It is what the
// 422 carries, and returning one from Bookmark.Search is how that endpoint
// refuses a field rather than a request.
type BookmarkSearchBodyError struct {
	// Conditions rows must satisfy.
	Filter *rigerr.FieldError `json:"filter,omitempty"`

	// Entity is a problem with the body as a whole rather than with one field.
	Entity *rigerr.FieldError `json:"entity,omitempty"`
}

// Empty reports whether anything went wrong. A validator that found nothing
// returns nil rather than one of these.
func (e *BookmarkSearchBodyError) Empty() bool {
	if e == nil {
		return true
	}

	return e.Filter == nil && e.Entity == nil
}

// Error implements error. The sentence is for logs and for a person; the
// structure above is what a client acts on.
func (e *BookmarkSearchBodyError) Error() string {
	var parts []string
	if e.Filter != nil {
		parts = append(parts, "filter "+e.Filter.Error())
	}
	if e.Entity != nil {
		parts = append(parts, e.Entity.Error())
	}

	return "the request is not valid: " + strings.Join(parts, "; ")
}

// ErrorCode implements [rigerr.Coder]: the request was understood and its
// content is what is wrong, which is 422 and not 400.
func (e *BookmarkSearchBodyError) ErrorCode() rigerr.Code { return rigerr.CodeUnprocessableEntity }

// ErrorFields implements [rigerr.FieldReporter], which is how the HTTP layer
// finds this and answers with it rather than with prose.
func (e *BookmarkSearchBodyError) ErrorFields() any { return e }

// Path parameters for Bookmark.Delete.
type BookmarkDeletePath struct {
	// Identifier of the Bookmark.
	ID uuid.UUID `json:"id"`
}

// Path parameters for Bookmark.Get.
type BookmarkGetPath struct {
	// Identifier of the Bookmark.
	ID uuid.UUID `json:"id"`
}

// Path parameters for Bookmark.Update.
type BookmarkUpdatePath struct {
	// Identifier of the Bookmark.
	ID uuid.UUID `json:"id"`
}
