// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"github.com/google/uuid"
	"github.com/simonjanss/rig/examples/auth_oauth/internal/model"
)

// A page of Bookmarks.
type BookmarkListResponse struct {
	// The rows in this page.
	//
	// Pointers, because that is what the repository returns and copying every row
	// to change that would be work nobody asked for.
	Data []*model.Bookmark `json:"data"`
	// Where this page sits in the full result set.
	Pagination Pagination `json:"pagination"`
}

// Query parameters for Bookmark.List.
type BookmarkListQuery struct {
	// Maximum rows to return.
	Limit int `json:"limit"`
	// Rows to skip before the first returned row.
	Offset int `json:"offset"`
}

// Query parameters for Bookmark.Search.
type BookmarkSearchQuery struct {
	// Maximum rows to return.
	Limit int `json:"limit"`
	// Rows to skip before the first returned row.
	Offset int `json:"offset"`
}

// The request body for Bookmark.Search.
type BookmarkSearchBody struct {
	// Conditions rows must satisfy.
	Filter model.BookmarkFilter `json:"filter"`
}

// Path parameters for Bookmark.Delete.
type BookmarkDeletePath struct {
	// Identifier of the Bookmark.
	ID uuid.UUID `json:"id"`
}

// Path parameters for Bookmark.Get.
type BookmarkGetPath struct {
	// Identifier of the Bookmark.
	ID uuid.UUID `json:"id"`
}

// Path parameters for Bookmark.Update.
type BookmarkUpdatePath struct {
	// Identifier of the Bookmark.
	ID uuid.UUID `json:"id"`
}
