// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package api

import (
	"net/http"

	"github.com/simonjanss/rig/runtime/apibase"
	"github.com/simonjanss/rig/runtime/httpx"
)

// RequestIDHeader is where a caller may name its own request, so that its logs
// and this API's can be lined up afterwards.
//
// It is read on every route, including the authentication ones. What is done
// with it is [Server.RequestID]'s documentation.
const RequestIDHeader = "X-Request-Id"

// Authenticator identifies a caller and serves its own routes.
//
// [github.com/simonjanss/rig/auth.Auth] satisfies it without either side
// knowing the other exists, which is what keeps a project with no
// authentication from depending on argon2 and OAuth. Anything else with these
// two methods works just as well: a wrapper that adds a header check, a stub
// in a test, an entirely different implementation.
type Authenticator = apibase.Authenticator

// Server is the behavior every handler shares: who the caller is, where the
// log lines go, what a failure is answered with.
//
// [Register] fills in what this project already decided — its revision, the
// headers it names, its rate limiter and, when `tracing:` is on, where its
// spans go — so what is left to set is the handful of fields only an
// application can answer. See the package documentation of
// [github.com/simonjanss/rig/runtime/apibase] for every field.
type Server = apibase.Server

// IdempotencyPruner deletes the records of writes past their retention, and so
// decides how long after a write its Idempotency-Key still replays.
//
// Zero takes idempotency.DefaultRetention, a day: long enough to cover any
// retry, short enough that a key reused a week later is a new request rather
// than a write that silently does nothing.
//
// A task rather than a goroutine, for the reason FileSweeper is one — a cron
// job is one thing running, and a goroutine in every replica is as many as
// there are replicas, all racing to delete the same rows. Register it in
// serve.Config.Tasks and run `<binary> prune-idempotency`:
//
//	Tasks: map[string]serve.Task{"prune-idempotency": api.IdempotencyPruner(0)},
//
// Nothing schedules it for you. Without it rig_idempotency keeps every record
// ever written, and the retention above is a sentence rather than a behaviour.
var IdempotencyPruner = apibase.IdempotencyPruner

var prepare = apibase.Prepare
var requestContext = apibase.RequestContextOf
var fail = apibase.Fail
var logRequest = apibase.LogRequest
var writeJSON = apibase.WriteJSON
var writeResult = apibase.WriteResult
var decodeBody = apibase.DecodeBody
var decodeReader = apibase.DecodeReader

// Handlers is every resource's service, plus the shared behavior.
//
// One field per resource is deliberate: adding a table and forgetting to wire
// it up will not compile, rather than producing a route that answers 404 until
// somebody notices.
type Handlers struct {
	Server Server

	Bookmark BookmarkService
}

// Register mounts every route and returns the mux.
//
// The patterns come from the compiled document, so the router, the OpenAPI
// document, and the generated client all describe the same paths.
//
// It makes the mux rather than taking one, because a caller has nothing to
// decide about it: the patterns are absolute and already carry the base path.
// What comes back is a *http.ServeMux and not an opaque handler, so anything
// else this server answers — static files, a second API, another generator's
// routes — is still a Handle call on it.
func Register(h Handlers) *http.ServeMux {
	if h.Server.Auth != nil {
		if h.Server.GetClaims != nil {
			// Two answers to "who is calling" is not a preference to resolve quietly.
			// Whichever one lost would go on looking wired, and the difference only shows
			// up as a caller who is somebody else.
			panic("api.Register: set Server.Auth or Server.GetClaims, not both")
		}
		h.Server.GetClaims = h.Server.Auth.Claims
	}

	if h.Server.GetClaims == nil {
		// Refusing here rather than defaulting to anonymous is the point: a server
		// with no way to identify a caller cannot enforce tenancy, and every generated
		// query depends on it.
		panic("api.Register: set Server.Auth, or Server.GetClaims if this project authenticates its own way")
	}

	if h.Server.DB == nil {
		// Here rather than at the first write that carries the header. A nil pool
		// would make every Idempotency-Key a header nobody read, and a client retrying
		// a create in the belief that it is safe to would be writing a second row
		// every time — a failure nobody sees until they go looking for duplicates.
		panic("api.Register: set Server.DB to the database pool, for example DB: app.Pool")
	}

	// What this project already decided. An application sets who is calling and
	// where the log lines go; the rest is the document's, and restating it in a
	// main function would be somewhere for the two to disagree.
	h.Server.Revision = serverRevision
	h.Server.RevisionHeader = RevisionHeader
	h.Server.RequestIDHeader = RequestIDHeader

	// Only when it is empty: a project that replaced how a failure is answered has
	// said so, and this is not the place to undo it.
	if h.Server.OnError == nil {
		h.Server.OnError = DefaultErrorMapper
	}

	Link(h)

	mux := http.NewServeMux()

	if h.Bookmark != nil {
		registerBookmark(mux, h.Server, h.Bookmark)
	}

	// After the resources, so a pattern collision between the two is a panic
	// naming the auth route rather than the resource one — and the resource
	// routes are the ones this project owns.
	if h.Server.Auth != nil {
		h.Server.Auth.Mount(mux)
	}

	return mux
}

// Link hands every resource the hooks of the tables that reference it, so a
// delete reaches them.
//
// Register calls it, which is all an ordinary server needs. It is exported for
// the program that builds services and does not call Register — a batch job,
// a test that drives the service layer directly — because a delete that
// silently skipped every child is the same delete with different data left
// behind.
//
// Calling it twice is calling it once: each list is replaced rather than
// appended to. A resource whose field is nil is skipped, and a parent whose
// children are all nil adopts an empty list, which is what it had before.
func Link(h Handlers) {
	// No table here references another one rig writes a service for, so there is
	// nothing to propagate.
	_ = h
}

// DefaultErrorMapper turns an error into a response.
//
// The decision is [github.com/simonjanss/rig/runtime/httpx.AnswerFor]'s,
// shared with the routes rig mounts itself, so a failure from /auth/login and
// a failure from a generated route are classified once: the same code, the
// same status, an internal failure's detail redacted — it is exactly the
// kind of thing that leaks a table name or a connection string, and the
// request identifier goes out instead so the detail can be found in the logs
// — and a 429 leaving with its Retry-After.
//
// What is not shared is the envelope. This one's field names go through the
// project's `api.json_case` and rig's own routes always answer camelCase, so
// one struct cannot be both. The classification is one implementation, the
// encoding is two.
func DefaultErrorMapper(w http.ResponseWriter, _ *http.Request, rc RequestContext, err error) {
	answer := httpx.AnswerFor(w, err)
	writeJSON(w, answer.Status, Error{
		Code:      answer.Code,
		Message:   answer.Message,
		RequestID: rc.RequestID,
		Fields:    answer.Fields,
	})
}
