-- +goose Up
-- +goose StatementBegin

CREATE TYPE rig_identity_verification_delivery_state
    AS ENUM ('Pending', 'Sent', 'Failed', 'Skipped');

-- One single-use link on its way to a mailbox: claimed by lease, sent with no
-- transaction open, and marked afterwards.
--
-- The same shape as rig_notification_delivery, deliberately. A reader who knows
-- one knows this one's lease columns on sight, and the reason there are two of
-- them rather than one shared table is a module boundary: rig/auth depends on
-- rig/runtime and not on rig/notify, so the alternative to duplicating this
-- statement is a public queue package every rig application imports, with table
-- names interpolated into its SQL by its callers.
--
-- It holds intent and never a secret. The row says "a reset link is owed to the
-- person behind this verification"; the token is generated by the dispatcher
-- immediately before the send and exists only in memory and in the mail. That is
-- not a rule this table enforces, it is a shape it makes possible: there is no
-- column here for one to be put in.
--
-- Not tenant-scoped, for the reason rig_identity_verification is not: a reset
-- link belongs to a person rather than to one of the tenants they work in. The
-- tenant an invitation is into is on the verification row, under the name that
-- says it is not the column rig filters on.
CREATE TABLE rig_identity_verification_delivery (
    id                  uuid PRIMARY KEY,
    verification_id     uuid NOT NULL
                            REFERENCES rig_identity_verification (id) ON DELETE CASCADE,

    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz,

    kind                rig_identity_verification_kind NOT NULL,
    state               rig_identity_verification_delivery_state NOT NULL DEFAULT 'Pending',
    deliver_at          timestamptz NOT NULL DEFAULT now(),
    sent_at             timestamptz,
    failed_reason       text,

    attempts            integer NOT NULL DEFAULT 0,
    claimed_at          timestamptz,
    claimed_by          uuid
);

-- One delivery per link. It is what makes the enqueue idempotent, and what makes
-- "rotate a fresh secret into the row this delivery owns" a sentence with one
-- subject rather than a race between two deliveries over one verification.
CREATE UNIQUE INDEX rig_identity_verification_delivery_key
    ON rig_identity_verification_delivery (verification_id);

-- The claim query, and nothing else here needs an index.
CREATE INDEX rig_identity_verification_delivery_due_idx
    ON rig_identity_verification_delivery (deliver_at) WHERE state = 'Pending';

COMMENT ON TABLE  rig_identity_verification_delivery IS 'One single-use link on its way to a mailbox. Holds intent, never a token: the secret is generated at send time and is only ever in memory and in the mail.';
COMMENT ON COLUMN rig_identity_verification_delivery.verification_id IS 'The link this is the delivery of. The dispatcher rotates a fresh token into that row before every attempt, so exactly one token for it is live at a time.';
COMMENT ON COLUMN rig_identity_verification_delivery.created_at IS 'When the link was queued, which is not when its own expiry starts: the TTL runs from the send.';
COMMENT ON COLUMN rig_identity_verification_delivery.updated_at IS 'When a dispatcher last wrote to the row, or null while it has only ever been queued.';
COMMENT ON COLUMN rig_identity_verification_delivery.kind IS 'Which notifier method to call, copied from the verification so a claim needs no join.';
COMMENT ON COLUMN rig_identity_verification_delivery.state IS 'Skipped means the link was consumed or withdrawn before the mail went out, which is a different answer from Failed and worth telling apart in a report.';
COMMENT ON COLUMN rig_identity_verification_delivery.deliver_at IS 'When this is due. A failed attempt moves it out by the backoff, spread so a provider refusing a batch does not meet the whole batch again at one instant.';
COMMENT ON COLUMN rig_identity_verification_delivery.sent_at IS 'When the notifier accepted it, which is not the same as it arriving.';
COMMENT ON COLUMN rig_identity_verification_delivery.failed_reason IS 'What the notifier said last time. Kept on a retry as well as on a failure, so a pattern is visible before the cap is reached.';
COMMENT ON COLUMN rig_identity_verification_delivery.attempts IS 'How many times this has been claimed, including a claim in progress. Past max_attempts it is Failed and stops being claimed.';
COMMENT ON COLUMN rig_identity_verification_delivery.claimed_at IS 'When a dispatcher took it. Past claim_ttl another one may, which is what makes a process that died mid-send recoverable.';
COMMENT ON COLUMN rig_identity_verification_delivery.claimed_by IS 'Which process holds the lease: one identifier per process, so a stuck lease traces to a pod rather than to a mystery.';

-- The secret does not exist until the mail goes out, so a link that is queued and
-- not yet sent has no hash.
--
-- NULL rather than a placeholder. A placeholder would look redeemable and be safe
-- only because nobody knows its preimage, which is an invariant carried by luck
-- instead of by the schema. Nothing can reach a NULL row by token either way:
-- every lookup is `token_hash = $1`, and equality against NULL is never true.
--
-- The unique index on token_hash needs no change — Postgres already treats NULLs
-- as distinct, so any number of unsent links coexist.
ALTER TABLE rig_identity_verification ALTER COLUMN token_hash DROP NOT NULL;

COMMENT ON COLUMN rig_identity_verification.token_hash IS 'sha256 of the token, or null for a link that has been queued and not yet sent. The token itself is only ever in the mail.';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE rig_identity_verification_delivery;
DROP TYPE rig_identity_verification_delivery_state;

-- A link whose secret was never generated is one nobody holds, so deleting it
-- loses nothing that could have been redeemed. It has to go before the column can
-- be NOT NULL again.
DELETE FROM rig_identity_verification WHERE token_hash IS NULL;
ALTER TABLE rig_identity_verification ALTER COLUMN token_hash SET NOT NULL;

COMMENT ON COLUMN rig_identity_verification.token_hash IS 'sha256 of the token. The token itself is only ever in the mail.';

-- +goose StatementEnd
