// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// Something somebody wrote down.
//
// It is the one definition of a Note: the repository scans into it and the API
// returns it, so there is no conversion between two shapes of the same thing
// and no field that can go missing from one of them.
type Note struct {
	// Unique identifier for this row.
	ID uuid.UUID `json:"id"`
	// Tenant this row belongs to. Every query is scoped by it.
	TenantID uuid.UUID `json:"tenantId"`
	// What the note is about, in a few words.
	Title string `json:"title"`
	// The note itself, or null while it is just a title.
	Body *string `json:"body,omitempty"`
	// When this row was created. Set automatically and never changes.
	CreatedAt time.Time `json:"createdAt"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *uuid.UUID `json:"updatedByAccountId,omitempty"`
	// When this row was soft-deleted. Null while the row is live.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// Account that soft-deleted this row, taken from the request's claims.
	DeletedByAccountID *uuid.UUID `json:"deletedByAccountId,omitempty"`
	// API key this row was created through, when it was an integration rather than
	// a person.
	CreatedByAPIKeyID *uuid.UUID `json:"createdByApiKeyId,omitempty"`
	// API key this row was last updated through, when it was an integration rather
	// than a person.
	UpdatedByAPIKeyID *uuid.UUID `json:"updatedByApiKeyId,omitempty"`
	// API key this row was soft-deleted through, when it was an integration rather
	// than a person.
	DeletedByAPIKeyID *uuid.UUID `json:"deletedByApiKeyId,omitempty"`
	// When the note goes live, or null while it is a draft. Notifications about it
	// are due then.
	PublishAt *time.Time `json:"publishAt,omitempty"`
}

// TableNote is the table this entity is stored in.
const TableNote = "note"

// Column names for note, so nothing has to spell one out.
const (
	ColumnNoteID                 = "id"
	ColumnNoteTenantID           = "tenant_id"
	ColumnNoteTitle              = "title"
	ColumnNoteBody               = "body"
	ColumnNoteCreatedAt          = "created_at"
	ColumnNoteCreatedByAccountID = "created_by_account_id"
	ColumnNoteUpdatedAt          = "updated_at"
	ColumnNoteUpdatedByAccountID = "updated_by_account_id"
	ColumnNoteDeletedAt          = "deleted_at"
	ColumnNoteDeletedByAccountID = "deleted_by_account_id"
	ColumnNoteCreatedByAPIKeyID  = "created_by_api_key_id"
	ColumnNoteUpdatedByAPIKeyID  = "updated_by_api_key_id"
	ColumnNoteDeletedByAPIKeyID  = "deleted_by_api_key_id"
	ColumnNotePublishAt          = "publish_at"
)

// NoteColumns is every column, in the order the row is scanned.
var NoteColumns = []string{"id", "tenant_id", "title", "body", "created_at", "created_by_account_id", "updated_at", "updated_by_account_id", "deleted_at", "deleted_by_account_id", "created_by_api_key_id", "updated_by_api_key_id", "deleted_by_api_key_id", "publish_at"}
