// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// Where a push can reach somebody. Email is refused: the address is on the
// account already.
//
// It is the one definition of a RigNotificationDevice: the repository scans
// into it and the API returns it, so there is no conversion between two shapes
// of the same thing and no field that can go missing from one of them.
type RigNotificationDevice struct {
	// Unique identifier for this row.
	ID uuid.UUID `json:"id"`
	// Tenant this row belongs to. Every query is scoped by it.
	TenantID uuid.UUID `json:"tenantId"`
	// Whose device it is.
	AccountID uuid.UUID `json:"accountId"`
	// When this row was created. Set automatically and never changes.
	CreatedAt time.Time `json:"createdAt"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Desktop or Mobile. Email is refused by the CHECK above.
	Channel RigNotificationChannel `json:"channel"`
	// What the provider was given to address this device. Opaque to rig.
	Token string `json:"token"`
	// What a person sees in a list of their devices, and the column that makes
	// revoking one possible for somebody who has four.
	Label *string `json:"label,omitempty"`
	// When this device last checked in, so a stale one can be told apart from a
	// revoked one.
	LastSeenAt *time.Time `json:"lastSeenAt,omitempty"`
	// When it stopped being a place to send to. Kept rather than deleted, so a
	// token that comes back can be recognised.
	RevokedAt *time.Time `json:"revokedAt,omitempty"`
}

// TableRigNotificationDevice is the table this entity is stored in.
const TableRigNotificationDevice = "rig_notification_device"

// Column names for rig_notification_device, so nothing has to spell one out.
const (
	ColumnRigNotificationDeviceID         = "id"
	ColumnRigNotificationDeviceTenantID   = "tenant_id"
	ColumnRigNotificationDeviceAccountID  = "account_id"
	ColumnRigNotificationDeviceCreatedAt  = "created_at"
	ColumnRigNotificationDeviceUpdatedAt  = "updated_at"
	ColumnRigNotificationDeviceChannel    = "channel"
	ColumnRigNotificationDeviceToken      = "token"
	ColumnRigNotificationDeviceLabel      = "label"
	ColumnRigNotificationDeviceLastSeenAt = "last_seen_at"
	ColumnRigNotificationDeviceRevokedAt  = "revoked_at"
)

// RigNotificationDeviceColumns is every column, in the order the row is
// scanned.
var RigNotificationDeviceColumns = []string{"id", "tenant_id", "account_id", "created_at", "updated_at", "channel", "token", "label", "last_seen_at", "revoked_at"}
