// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// A named bundle of permissions, defined per tenant.
//
// It is the one definition of a Role: the repository scans into it and the API
// returns it, so there is no conversion between two shapes of the same thing
// and no field that can go missing from one of them.
type Role struct {
	// Unique identifier for this row.
	ID uuid.UUID `json:"id"`
	// Tenant this row belongs to. Every query is scoped by it.
	TenantID uuid.UUID `json:"tenantId"`
	// When this row was created. Set automatically and never changes.
	CreatedAt time.Time `json:"createdAt"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Stable identifier, such as editor.
	Key string `json:"key"`
	// What to call the role in the interface.
	Name string `json:"name"`
	// What the role is for.
	Description string `json:"description"`
	// Whether rig created the role. A system role should not be editable.
	IsSystem bool `json:"isSystem"`
}

// TableRole is the table this entity is stored in.
const TableRole = "role"

// Column names for role, so nothing has to spell one out.
const (
	ColumnRoleID          = "id"
	ColumnRoleTenantID    = "tenant_id"
	ColumnRoleCreatedAt   = "created_at"
	ColumnRoleUpdatedAt   = "updated_at"
	ColumnRoleKey         = "key"
	ColumnRoleName        = "name"
	ColumnRoleDescription = "description"
	ColumnRoleIsSystem    = "is_system"
)

// RoleColumns is every column, in the order the row is scanned.
var RoleColumns = []string{"id", "tenant_id", "created_at", "updated_at", "key", "name", "description", "is_system"}
