// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

import (
	"time"

	"github.com/google/uuid"
)

// One copy of an inbox line on its way to a channel. Claimed by lease, sent
// outside any transaction, and marked afterwards.
//
// Every field the server returns, and no field it does not: this is the
// readable projection of the row rather than the row.
type NotificationDelivery struct {
	// Unique identifier for this row.
	ID uuid.UUID `json:"id"`
	// Tenant this row belongs to. Every query is scoped by it.
	TenantID uuid.UUID `json:"tenantId"`
	// The inbox line this is a copy of. The line is the truth and this is one way
	// it was repeated.
	RecipientID uuid.UUID `json:"recipientId"`
	// Who it is for, denormalized off the line so a claim can group by it without
	// a join.
	AccountID uuid.UUID `json:"accountId"`
	// When this row was created. Set automatically and never changes.
	CreatedAt time.Time `json:"createdAt"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Where it is going. One row per line per channel, which is what the unique
	// index below enforces.
	Channel NotificationChannel `json:"channel"`
	// Copied from the notification, so the settings resolution needs no join
	// either.
	Kind string `json:"kind"`
	// What the setting said when this row was written. Immediate rows are sent on
	// their own; the rest are batched per account and channel.
	Digest NotificationDigest `json:"digest"`
	// Skipped means a setting refused it, which is different from Failed and worth
	// telling apart in a report.
	State NotificationDeliveryState `json:"state"`
	// When this is due. A delivery held outside somebody hours moves to the next
	// opening; a digested one moves to its window close.
	DeliverAt time.Time `json:"deliverAt"`
	// When a channel accepted it, which is not the same as it arriving.
	SentAt *time.Time `json:"sentAt,omitempty"`
	// What the channel said last time. Kept on a retry as well as on a failure, so
	// a pattern is visible before the cap is reached.
	FailedReason *string `json:"failedReason,omitempty"`
	// How many times this has been claimed. Past notifications.max_attempts it is
	// Failed and stops being claimed.
	Attempts int `json:"attempts"`
	// When a dispatcher took it. Past notifications.claim_ttl another one may,
	// which is what makes a crashed process recoverable.
	ClaimedAt *time.Time `json:"claimedAt,omitempty"`
	// Which process holds the lease. A uuid generated once per process, with the
	// hostname beside it in the log line, so a stuck lease traces to a pod rather
	// than to a mystery.
	ClaimedBy *uuid.UUID `json:"claimedBy,omitempty"`
}

// A page of NotificationDeliveries.
type NotificationDeliveryListResponse struct {
	// The rows in this page.
	Data []NotificationDelivery `json:"data,omitempty"`
	// Where this page sits in the full result set.
	Pagination Pagination `json:"pagination"`
}
