// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

// Where a notification is in its life. Nothing here says anything was sent:
// that is the delivery table's business.
type NotificationState string

// The values of NotificationState.
const (
	// The audience has not been computed yet. Every notification starts here, and
	// a scheduled one waits here until it is due.
	NotificationStatePending NotificationState = "Pending"
	// The audience was computed and the inbox lines exist. It does not mean
	// anything was sent — a notification with an inbox line and no mail is a
	// working notification.
	NotificationStateResolved NotificationState = "Resolved"
	// It never will be resolved: the row it was about was retired before its time
	// came.
	NotificationStateCancelled NotificationState = "Cancelled"
)

// AllNotificationState is every value, in declaration order. It is what a
// picker is drawn from.
var AllNotificationState = []NotificationState{NotificationStatePending, NotificationStateResolved, NotificationStateCancelled}

// String implements fmt.Stringer.
func (v NotificationState) String() string { return string(v) }
