// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

import (
	"context"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/google/uuid"
	"github.com/simonjanss/rig/rigclient"
)

// NotificationRecipientClient calls the NotificationRecipient endpoints. It is
// reached as Client.NotificationRecipients rather than built directly.
type NotificationRecipientClient struct{ rt *rigclient.Runtime }

// List NotificationRecipients.
//
// GET /api/v1/notification-recipients
//
// Operation listNotificationRecipients.
func (c *NotificationRecipientClient) List(ctx context.Context, q NotificationRecipientListQuery, opts ...rigclient.CallOption) (*NotificationRecipientListResponse, error) {
	query := url.Values{}
	rigclient.SetInt(query, "limit", q.Limit)
	rigclient.SetInt(query, "offset", q.Offset)
	rigclient.SetString(query, "scope", q.Scope)

	op := rigclient.Op{
		Name:   "listNotificationRecipients",
		Method: http.MethodGet,
		Path:   "/notification-recipients",
		Query:  query,
	}
	return rigclient.Do[NotificationRecipientListResponse](ctx, c.rt, op, opts...)
}

// Search NotificationRecipients with filters.
//
// QUERY /api/v1/notification-recipients, falling back to POST
// /api/v1/notification-recipients/_search when something between here and the
// server refuses the method. The fallback is remembered, so it is tried once.
//
// Operation searchNotificationRecipients.
func (c *NotificationRecipientClient) Search(ctx context.Context, filter NotificationRecipientFilter, q NotificationRecipientSearchQuery, opts ...rigclient.CallOption) (*NotificationRecipientListResponse, error) {
	query := url.Values{}
	rigclient.SetInt(query, "limit", q.Limit)
	rigclient.SetInt(query, "offset", q.Offset)
	rigclient.SetString(query, "scope", q.Scope)

	op := rigclient.Op{
		Name:     "searchNotificationRecipients",
		Method:   rigclient.MethodQuery,
		Path:     "/notification-recipients",
		Query:    query,
		Body:     NotificationRecipientSearchBody{Filter: filter},
		Fallback: "/notification-recipients/_search",
	}
	return rigclient.Do[NotificationRecipientListResponse](ctx, c.rt, op, opts...)
}

// List retired NotificationRecipients.
//
// A deletion stamps the row rather than removing it, so this is what was
// deleted and can still be brought back. Only rows inside the 0-day restore
// window appear: past it a row is gone as far as anyone is concerned, so it is
// not in the trash either.
//
// GET /api/v1/notification-recipients/_deleted
//
// Operation listDeletedNotificationRecipients.
func (c *NotificationRecipientClient) ListDeleted(ctx context.Context, q NotificationRecipientListDeletedQuery, opts ...rigclient.CallOption) (*NotificationRecipientListResponse, error) {
	query := url.Values{}
	rigclient.SetInt(query, "limit", q.Limit)
	rigclient.SetInt(query, "offset", q.Offset)
	rigclient.SetString(query, "scope", q.Scope)

	op := rigclient.Op{
		Name:   "listDeletedNotificationRecipients",
		Method: http.MethodGet,
		Path:   "/notification-recipients/_deleted",
		Query:  query,
	}
	return rigclient.Do[NotificationRecipientListResponse](ctx, c.rt, op, opts...)
}

// Delete a NotificationRecipient.
//
// The row is retired by stamping a deletion time; it stops appearing in reads
// but can be restored within the retention window.
//
// DELETE /api/v1/notification-recipients/{id}
//
// Operation deleteNotificationRecipient.
func (c *NotificationRecipientClient) Delete(ctx context.Context, id uuid.UUID, opts ...rigclient.CallOption) error {
	op := rigclient.Op{
		Name:   "deleteNotificationRecipient",
		Method: http.MethodDelete,
		Path:   strings.Replace("/notification-recipients/{id}", "{id}", rigclient.PathValue(id.String()), 1),
	}
	return rigclient.DoNoContent(ctx, c.rt, op, opts...)
}

// Fetch one NotificationRecipient by identifier.
//
// GET /api/v1/notification-recipients/{id}
//
// Operation getNotificationRecipient.
func (c *NotificationRecipientClient) Get(ctx context.Context, id uuid.UUID, q NotificationRecipientGetQuery, opts ...rigclient.CallOption) (*NotificationRecipient, error) {
	query := url.Values{}
	rigclient.SetString(query, "scope", q.Scope)

	op := rigclient.Op{
		Name:   "getNotificationRecipient",
		Method: http.MethodGet,
		Path:   strings.Replace("/notification-recipients/{id}", "{id}", rigclient.PathValue(id.String()), 1),
		Query:  query,
	}
	return rigclient.Do[NotificationRecipient](ctx, c.rt, op, opts...)
}

// All reads every NotificationRecipient the query matches, a page at a time.
//
// The query's own limit is the page size, and its offset is where the walk
// starts. Iteration stops at the first failure, which arrives as the second
// value of the last pair — so a loop that ignores it is a loop that silently
// stops early.
func (c *NotificationRecipientClient) All(ctx context.Context, q NotificationRecipientListQuery, opts ...rigclient.CallOption) iter.Seq2[NotificationRecipient, error] {
	start := 0
	if q.Offset != nil {
		start = *q.Offset
	}

	return rigclient.Paginate(ctx, start, func(ctx context.Context, offset int) (rigclient.Page[NotificationRecipient], error) {
		q := q
		q.Offset = &offset

		res, err := c.List(ctx, q, opts...)
		if err != nil {
			return rigclient.Page[NotificationRecipient]{}, err
		}
		if res == nil {
			return rigclient.Page[NotificationRecipient]{}, nil
		}

		return rigclient.Page[NotificationRecipient]{
			Items:  res.Data,
			Total:  res.Pagination.Total,
			Offset: res.Pagination.Offset,
		}, nil
	})
}
