// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"time"

	"github.com/google/uuid"
)

// One match between two squads.
//
// It is the one definition of a Fixture: the repository scans into it and the
// API returns it, so there is no conversion between two shapes of the same
// thing and no field that can go missing from one of them.
type Fixture struct {
	// Unique identifier for this row.
	ID uuid.UUID `json:"id"`
	// Tenant this row belongs to. Every query is scoped by it.
	TenantID uuid.UUID `json:"tenantId"`
	// The squad playing at home.
	HomeTeamID uuid.UUID `json:"homeTeamId"`
	// The squad playing away.
	AwayTeamID uuid.UUID `json:"awayTeamId"`
	// When the match starts.
	KickoffAt time.Time `json:"kickoffAt"`
	// When this row was created. Set automatically and never changes.
	CreatedAt time.Time `json:"createdAt"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *uuid.UUID `json:"createdByAccountId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Account that last updated this row, taken from the request's claims.
	UpdatedByAccountID *uuid.UUID `json:"updatedByAccountId,omitempty"`
}

// TableFixture is the table this entity is stored in.
const TableFixture = "fixture"

// Column names for fixture, so nothing has to spell one out.
const (
	ColumnFixtureID                 = "id"
	ColumnFixtureTenantID           = "tenant_id"
	ColumnFixtureHomeTeamID         = "home_team_id"
	ColumnFixtureAwayTeamID         = "away_team_id"
	ColumnFixtureKickoffAt          = "kickoff_at"
	ColumnFixtureCreatedAt          = "created_at"
	ColumnFixtureCreatedByAccountID = "created_by_account_id"
	ColumnFixtureUpdatedAt          = "updated_at"
	ColumnFixtureUpdatedByAccountID = "updated_by_account_id"
)

// FixtureColumns is every column, in the order the row is scanned.
var FixtureColumns = []string{"id", "tenant_id", "home_team_id", "away_team_id", "kickoff_at", "created_at", "created_by_account_id", "updated_at", "updated_by_account_id"}
