// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package model

import (
	"context"
	"strings"

	"github.com/google/uuid"
	"github.com/simonjanss/rig/runtime/patch"
	"github.com/simonjanss/rig/runtime/rigerr"
	"github.com/simonjanss/rig/runtime/tenancy"
)

// TeamCreateInput is what creating a Team takes.
//
// The identifier, the tenant, and the audit columns are absent: those are
// stamped by the repository from the request's claims.
type TeamCreateInput struct {
	// What the manager calls their squad.
	Name string `json:"name"`
	// Whether the squad is playing this season.
	IsActive bool `json:"isActive"`
}

// Normalize tidies what was given before anything checks it.
//
// It runs first so that validation sees the value that will actually be
// stored: a title with a trailing space and one without are the same title,
// and rejecting the second for a length rule the first passes would be
// indefensible.
func (i *TeamCreateInput) Normalize() {
	i.Name = strings.TrimSpace(i.Name)
	if i.IsActive == false {
		i.IsActive = true
	}
}

// TeamCreateInputError says what was wrong with each field of a
// TeamCreateInput.
//
// Its shape is the input's shape, so a client can attach every message to the
// field it is about without matching on strings. A member is nil when that
// field was fine, and the whole value is nil when the input was. It is what
// the 422 carries.
type TeamCreateInputError struct {
	// What the manager calls their squad.
	Name *rigerr.FieldError `json:"name,omitempty"`
	// Whether the squad is playing this season.
	IsActive *rigerr.FieldError `json:"isActive,omitempty"`

	// Entity is a problem with the row as a whole rather than with one field: what
	// the Entity rule said.
	Entity *rigerr.FieldError `json:"entity,omitempty"`
}

// Empty reports whether anything went wrong. A validator that found nothing
// returns nil rather than one of these.
func (e *TeamCreateInputError) Empty() bool {
	if e == nil {
		return true
	}

	return e.Name == nil && e.IsActive == nil && e.Entity == nil
}

// Error implements error. The sentence is for logs and for a person; the
// structure above is what a client acts on.
func (e *TeamCreateInputError) Error() string {
	var parts []string
	if e.Name != nil {
		parts = append(parts, "name "+e.Name.Error())
	}
	if e.IsActive != nil {
		parts = append(parts, "isActive "+e.IsActive.Error())
	}
	if e.Entity != nil {
		parts = append(parts, e.Entity.Error())
	}

	return "team is not valid: " + strings.Join(parts, "; ")
}

// ErrorCode implements [rigerr.Coder]: the request was understood and its
// content is what is wrong, which is 422 and not 400.
func (e *TeamCreateInputError) ErrorCode() rigerr.Code { return rigerr.CodeUnprocessableEntity }

// ErrorFields implements [rigerr.FieldReporter], which is how the HTTP layer
// finds this and answers with it rather than with prose.
func (e *TeamCreateInputError) ErrorFields() any { return e }

// Validate checks what the schema can decide on its own.
//
// Everything a column declares — NOT NULL, a length, an enumeration's values
// — is checked here, so a service only writes the rules that are actually
// about the business. Every field is checked before returning, because a form
// that reports one problem per round trip is a form people give up on.
//
// What comes back is a *TeamCreateInputError, shaped like the input itself.
func (i *TeamCreateInput) Validate() error {
	var failed TeamCreateInputError

	if strings.TrimSpace(i.Name) == "" {
		failed.Name = rigerr.NewFieldError(rigerr.FieldCodeCannotBeEmpty, "cannot be empty")
	}

	if failed.Empty() {
		return nil
	}
	return &failed
}

// TeamUpdateInput is what changing a Team takes.
//
// A field left out is untouched. A nullable field set to null is cleared —
// which is why the two wrappers differ: a column that cannot hold null has no
// way to be given one, so clearing it is a compile error rather than a
// rejection at runtime. Immutable fields are not here at all.
type TeamUpdateInput struct {
	// What the manager calls their squad.
	Name patch.Optional[string] `json:"name"`
	// Whether the squad is playing this season.
	IsActive patch.Optional[bool] `json:"isActive"`
}

// Normalize tidies the fields this request actually carries.
//
// It does not fill in the ones it does not: the repository writes exactly the
// columns that were sent, and filling them here would turn every update into a
// write of every column — so two requests changing different fields of one
// row would start overwriting each other instead of composing.
func (i *TeamUpdateInput) Normalize() {
	if v, ok := i.Name.Get(); ok {
		v = strings.TrimSpace(v)
		i.Name = patch.NewOptional(v)
	}
}

// Merged is the row as it will be once this update is applied.
//
// It is what validation runs against, and the reason it exists: a rule
// spanning two fields cannot be checked from a partial request. "Ends after
// starts" is unanswerable when only one of them was sent.
//
// It returns a copy. The input keeps its patches, so the repository still
// writes only the columns that were actually given.
func (i TeamUpdateInput) Merged(prev *Team) Team {
	out := *prev

	if v, ok := i.Name.Get(); ok {
		out.Name = v
	}
	if v, ok := i.IsActive.Get(); ok {
		out.IsActive = v
	}

	return out
}

// TeamUpdateInputError says what was wrong with each field of a
// TeamUpdateInput.
//
// Its shape is the input's shape, so a client can attach every message to the
// field it is about without matching on strings. A member is nil when that
// field was fine, and the whole value is nil when the input was. It is what
// the 422 carries.
type TeamUpdateInputError struct {
	// What the manager calls their squad.
	Name *rigerr.FieldError `json:"name,omitempty"`
	// Whether the squad is playing this season.
	IsActive *rigerr.FieldError `json:"isActive,omitempty"`

	// Entity is a problem with the row as a whole rather than with one field: what
	// the Entity rule said.
	Entity *rigerr.FieldError `json:"entity,omitempty"`
}

// Empty reports whether anything went wrong. A validator that found nothing
// returns nil rather than one of these.
func (e *TeamUpdateInputError) Empty() bool {
	if e == nil {
		return true
	}

	return e.Name == nil && e.IsActive == nil && e.Entity == nil
}

// Error implements error. The sentence is for logs and for a person; the
// structure above is what a client acts on.
func (e *TeamUpdateInputError) Error() string {
	var parts []string
	if e.Name != nil {
		parts = append(parts, "name "+e.Name.Error())
	}
	if e.IsActive != nil {
		parts = append(parts, "isActive "+e.IsActive.Error())
	}
	if e.Entity != nil {
		parts = append(parts, e.Entity.Error())
	}

	return "team is not valid: " + strings.Join(parts, "; ")
}

// ErrorCode implements [rigerr.Coder]: the request was understood and its
// content is what is wrong, which is 422 and not 400.
func (e *TeamUpdateInputError) ErrorCode() rigerr.Code { return rigerr.CodeUnprocessableEntity }

// ErrorFields implements [rigerr.FieldReporter], which is how the HTTP layer
// finds this and answers with it rather than with prose.
func (e *TeamUpdateInputError) ErrorFields() any { return e }

// Validate checks the row this update would produce.
//
// Against the merged state, not the request: a length rule on a field nobody
// sent still has to hold, and a rule about two fields needs both.
//
// What comes back is a *TeamUpdateInputError, shaped like the input itself.
func (i *TeamUpdateInput) Validate(prev *Team) error {
	var failed TeamUpdateInputError

	merged := i.Merged(prev)

	if strings.TrimSpace(merged.Name) == "" {
		failed.Name = rigerr.NewFieldError(rigerr.FieldCodeCannotBeEmpty, "cannot be empty")
	}

	if failed.Empty() {
		return nil
	}
	return &failed
}

// TeamDeleteInput is what deleting a Team takes.
type TeamDeleteInput struct {
	// ID is the row to delete.
	ID uuid.UUID `json:"id"`
	// Hard removes the row outright instead of retiring it. A hard delete cannot
	// be undone and takes the row's snapshots with it.
	Hard bool `json:"hard,omitempty"`
}

// TeamValidatorContext is what a rule sees.
//
// Values is the row as it will be if this goes through — merged from the
// previous state on an update, so every field is set whether or not the
// request mentioned it. That is the point: "ends after starts" cannot be
// answered from a request that only carried one of them.
type TeamValidatorContext struct {
	// Values is the intended end state.
	Values Team

	// Claims are who is asking. They are a value rather than something to fetch
	// from the context because a rule that has to look them up is a rule that can
	// forget to, and because there is no case where they are absent: a write
	// without a caller is refused by the repository before any rule runs.
	Claims tenancy.Claims

	// previous is the row before this change, and is the zero value on a
	// create — there was nothing before.
	previous Team
	isUpdate bool
	changed  map[string]bool
}

// IsUpdate reports whether there was a row before this.
func (c *TeamValidatorContext) IsUpdate() bool { return c.isUpdate }

// Previous is the row as it was, and the zero value on a create. Check
// IsUpdate before reading it.
func (c *TeamValidatorContext) Previous() Team { return c.previous }

// Changed reports whether this request carried a new value for a column.
//
// It is what keeps an expensive rule from running on every update: a check
// that reaches another service to confirm a reference only needs to run when
// the reference actually moved. On a create everything is changed, because
// everything is new.
func (c *TeamValidatorContext) Changed(column string) bool { return c.changed[column] }

// NameChanged reports whether this request set name.
func (c *TeamValidatorContext) NameChanged() bool { return c.changed[ColumnTeamName] }

// IsActiveChanged reports whether this request set is_active.
func (c *TeamValidatorContext) IsActiveChanged() bool { return c.changed[ColumnTeamIsActive] }

// TeamCreateValidator is the rules for bringing a Team into existence: what
// the schema cannot express.
//
// One optional function per field this operation can set, so the set of fields
// is the set of rules that could apply — a column an update cannot touch has
// no hook here to write by mistake. A nil one is skipped. Every configured
// hook runs, because a rule that fails should not hide the next one, so a
// request reports everything wrong with it.
//
// A hook returns a FieldError to attach the message to a specific field, or
// any other error to fail the request outright.
type TeamCreateValidator struct {
	// What the manager calls their squad.
	Name func(ctx context.Context, c *TeamValidatorContext, value string) error
	// Whether the squad is playing this season.
	IsActive func(ctx context.Context, c *TeamValidatorContext, value bool) error

	// Entity runs after the per-field hooks, for a rule that is about the row
	// rather than about one column.
	Entity func(ctx context.Context, c *TeamValidatorContext) error
}

// RunCreate implements [dbhook.CreateValidator]: it runs the service's rules
// against the row this input would produce.
//
// The generated checks are not repeated here. The repository runs Normalize
// and Validate first, so by the time a hook sees the input it is tidy and the
// schema is satisfied — which is what lets a hook be about the business
// rather than about NOT NULL.
func (v TeamCreateValidator) RunCreate(ctx context.Context, claims tenancy.Claims, i *TeamCreateInput) error {
	// Everything is new, so everything counts as changed.
	c := &TeamValidatorContext{Claims: claims, changed: map[string]bool{}}
	c.Values.Name = i.Name
	c.changed[ColumnTeamName] = true
	c.Values.IsActive = i.IsActive
	c.changed[ColumnTeamIsActive] = true

	failed, err := v.run(ctx, c)
	if err != nil {
		return err
	}
	if failed != nil {
		return failed
	}
	return nil
}

// run calls every configured hook and puts what each one said under the field
// it was about.
//
// Two kinds of answer. A [rigerr.FieldError] is about the input: it lands on
// the field and the others still run, so one request reports everything wrong
// with it. Anything else is the rule itself failing — a lookup that could
// not reach another service — and there is nothing to tell the caller about
// their input, so it comes back wrapped with the rule that could not be run,
// keeping whatever code it carried and becoming Internal if it carried none.
func (v TeamCreateValidator) run(ctx context.Context, c *TeamValidatorContext) (*TeamCreateInputError, error) {
	var failed TeamCreateInputError

	if v.Name != nil {
		if err := v.Name(ctx, c, c.Values.Name); err != nil {
			field, ok := rigerr.AsFieldError(err)
			if !ok {
				return nil, rigerr.Wrap(err, "validate name")
			}
			failed.Name = field
		}
	}
	if v.IsActive != nil {
		if err := v.IsActive(ctx, c, c.Values.IsActive); err != nil {
			field, ok := rigerr.AsFieldError(err)
			if !ok {
				return nil, rigerr.Wrap(err, "validate is_active")
			}
			failed.IsActive = field
		}
	}

	if v.Entity != nil {
		if err := v.Entity(ctx, c); err != nil {
			field, ok := rigerr.AsFieldError(err)
			if !ok {
				return nil, rigerr.Wrap(err, "validate team")
			}
			failed.Entity = field
		}
	}

	if failed.Empty() {
		return nil, nil
	}
	return &failed, nil
}

// TeamUpdateValidator is the rules for changing one that already exists: what
// the schema cannot express.
//
// One optional function per field this operation can set, so the set of fields
// is the set of rules that could apply — a column an update cannot touch has
// no hook here to write by mistake. A nil one is skipped. Every configured
// hook runs, because a rule that fails should not hide the next one, so a
// request reports everything wrong with it.
//
// A hook returns a FieldError to attach the message to a specific field, or
// any other error to fail the request outright.
type TeamUpdateValidator struct {
	// What the manager calls their squad.
	Name func(ctx context.Context, c *TeamValidatorContext, value string) error
	// Whether the squad is playing this season.
	IsActive func(ctx context.Context, c *TeamValidatorContext, value bool) error

	// Entity runs after the per-field hooks, for a rule that is about the row
	// rather than about one column.
	Entity func(ctx context.Context, c *TeamValidatorContext) error
}

// RunUpdate implements [dbhook.UpdateValidator]: it runs the service's rules
// against the row this update would produce, with the row as it was available
// for a rule about the change itself.
func (v TeamUpdateValidator) RunUpdate(ctx context.Context, claims tenancy.Claims, i *TeamUpdateInput, prev *Team) error {
	c := &TeamValidatorContext{
		Values:   i.Merged(prev),
		Claims:   claims,
		previous: *prev,
		isUpdate: true,
		changed:  map[string]bool{},
	}
	c.changed[ColumnTeamName] = i.Name.IsSet()
	c.changed[ColumnTeamIsActive] = i.IsActive.IsSet()

	failed, err := v.run(ctx, c)
	if err != nil {
		return err
	}
	if failed != nil {
		return failed
	}
	return nil
}

// RunRestore implements [dbhook.RestoreValidator]: it runs the service's rules
// against the row this restore would bring back.
//
// Every rule runs, not only the ones whose field the request mentioned. The
// row was not live, so nothing about it has been checked against the world it
// is returning to.
func (v TeamUpdateValidator) RunRestore(ctx context.Context, claims tenancy.Claims, i *TeamUpdateInput, prev *Team) error {
	c := &TeamValidatorContext{
		Values:   i.Merged(prev),
		Claims:   claims,
		previous: *prev,
		isUpdate: true,
		changed:  map[string]bool{},
	}
	c.changed[ColumnTeamName] = true
	c.changed[ColumnTeamIsActive] = true

	failed, err := v.run(ctx, c)
	if err != nil {
		return err
	}
	if failed != nil {
		return failed
	}
	return nil
}

// run calls every configured hook and puts what each one said under the field
// it was about.
//
// Two kinds of answer. A [rigerr.FieldError] is about the input: it lands on
// the field and the others still run, so one request reports everything wrong
// with it. Anything else is the rule itself failing — a lookup that could
// not reach another service — and there is nothing to tell the caller about
// their input, so it comes back wrapped with the rule that could not be run,
// keeping whatever code it carried and becoming Internal if it carried none.
func (v TeamUpdateValidator) run(ctx context.Context, c *TeamValidatorContext) (*TeamUpdateInputError, error) {
	var failed TeamUpdateInputError

	if v.Name != nil {
		if err := v.Name(ctx, c, c.Values.Name); err != nil {
			field, ok := rigerr.AsFieldError(err)
			if !ok {
				return nil, rigerr.Wrap(err, "validate name")
			}
			failed.Name = field
		}
	}
	if v.IsActive != nil {
		if err := v.IsActive(ctx, c, c.Values.IsActive); err != nil {
			field, ok := rigerr.AsFieldError(err)
			if !ok {
				return nil, rigerr.Wrap(err, "validate is_active")
			}
			failed.IsActive = field
		}
	}

	if v.Entity != nil {
		if err := v.Entity(ctx, c); err != nil {
			field, ok := rigerr.AsFieldError(err)
			if !ok {
				return nil, rigerr.Wrap(err, "validate team")
			}
			failed.Entity = field
		}
	}

	if failed.Empty() {
		return nil, nil
	}
	return &failed, nil
}
