// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

import (
	"context"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/google/uuid"
	"github.com/simonjanss/rig/rigclient"
)

// AccountClient calls the Account endpoints. It is reached as Client.Accounts
// rather than built directly.
type AccountClient struct{ rt *rigclient.Runtime }

// List Accounts.
//
// GET /api/v1/accounts
//
// Operation listAccounts.
func (c *AccountClient) List(ctx context.Context, q AccountListQuery, opts ...rigclient.CallOption) (*AccountListResponse, error) {
	query := url.Values{}
	rigclient.SetInt(query, "limit", q.Limit)
	rigclient.SetInt(query, "offset", q.Offset)

	op := rigclient.Op{
		Name:   "listAccounts",
		Method: http.MethodGet,
		Path:   "/accounts",
		Query:  query,
	}
	return rigclient.Do[AccountListResponse](ctx, c.rt, op, opts...)
}

// List retired Accounts.
//
// A deletion stamps the row rather than removing it, so this is what was
// deleted and can still be brought back. Only rows inside the 30-day restore
// window appear: past it a row is gone as far as anyone is concerned, so it is
// not in the trash either.
//
// GET /api/v1/accounts/_deleted
//
// Operation listDeletedAccounts.
func (c *AccountClient) ListDeleted(ctx context.Context, q AccountListDeletedQuery, opts ...rigclient.CallOption) (*AccountListResponse, error) {
	query := url.Values{}
	rigclient.SetInt(query, "limit", q.Limit)
	rigclient.SetInt(query, "offset", q.Offset)

	op := rigclient.Op{
		Name:   "listDeletedAccounts",
		Method: http.MethodGet,
		Path:   "/accounts/_deleted",
		Query:  query,
	}
	return rigclient.Do[AccountListResponse](ctx, c.rt, op, opts...)
}

// Fetch one Account by identifier.
//
// GET /api/v1/accounts/{id}
//
// Operation getAccount.
func (c *AccountClient) Get(ctx context.Context, id uuid.UUID, opts ...rigclient.CallOption) (*Account, error) {
	op := rigclient.Op{
		Name:   "getAccount",
		Method: http.MethodGet,
		Path:   strings.Replace("/accounts/{id}", "{id}", rigclient.PathValue(id.String()), 1),
	}
	return rigclient.Do[Account](ctx, c.rt, op, opts...)
}

// All reads every Account the query matches, a page at a time.
//
// The query's own limit is the page size, and its offset is where the walk
// starts. Iteration stops at the first failure, which arrives as the second
// value of the last pair — so a loop that ignores it is a loop that silently
// stops early.
func (c *AccountClient) All(ctx context.Context, q AccountListQuery, opts ...rigclient.CallOption) iter.Seq2[Account, error] {
	start := 0
	if q.Offset != nil {
		start = *q.Offset
	}

	return rigclient.Paginate(ctx, start, func(ctx context.Context, offset int) (rigclient.Page[Account], error) {
		q := q
		q.Offset = &offset

		res, err := c.List(ctx, q, opts...)
		if err != nil {
			return rigclient.Page[Account]{}, err
		}
		if res == nil {
			return rigclient.Page[Account]{}, nil
		}

		return rigclient.Page[Account]{
			Items:  res.Data,
			Total:  res.Pagination.Total,
			Offset: res.Pagination.Offset,
		}, nil
	})
}
