// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

// Where a copy of an inbox line can be sent. The inbox itself is not one of
// them.
type NotificationChannel string

// The values of NotificationChannel.
const (
	// A browser or a desktop application, addressed by a device row.
	NotificationChannelDesktop NotificationChannel = "Desktop"
	// A phone, addressed by a device row.
	NotificationChannelMobile NotificationChannel = "Mobile"
	// The address on the account. No device row: there is nothing to register,
	// because the address is on the account already.
	NotificationChannelEmail NotificationChannel = "Email"
)

// AllNotificationChannel is every value, in declaration order. It is what a
// picker is drawn from.
var AllNotificationChannel = []NotificationChannel{NotificationChannelDesktop, NotificationChannelMobile, NotificationChannelEmail}

// String implements fmt.Stringer.
func (v NotificationChannel) String() string { return string(v) }
