// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Something worth telling somebody about, and when it is due. Carries no
// recipients: the audience is computed when it is sent.
//
// Every field the server returns, and no field it does not: this is the
// readable projection of the row rather than the row.
type Notification struct {
	// Unique identifier for this row.
	ID uuid.UUID `json:"id"`
	// Tenant this row belongs to. Every query is scoped by it.
	TenantID uuid.UUID `json:"tenantId"`
	// When this row was created. Set automatically and never changes.
	CreatedAt time.Time `json:"createdAt"`
	// Account that created this row, taken from the request's claims.
	CreatedByAccountID *uuid.UUID `json:"createdByAccountId,omitempty"`
	// API key this row was created through, when it was an integration rather than
	// a person.
	CreatedByAPIKeyID *uuid.UUID `json:"createdByApiKeyId,omitempty"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// What happened, as the application names it. Narrow it to an enum of your own
	// to get a switch the compiler can see.
	Kind string `json:"kind"`
	// Resolved means the audience was determined and the inbox lines exist. It
	// does not mean anything was sent.
	State NotificationState `json:"state"`
	// When this is due. now() is the ordinary case; a scheduled notification is
	// the same row with a later time, which is the only difference between the
	// two.
	DeliverAt time.Time `json:"deliverAt"`
	// When the audience was computed. Null while the notification is still pending
	// or was cancelled.
	ResolvedAt *time.Time `json:"resolvedAt,omitempty"`
	// What a template needs beyond the linked row. Give it a Go type with the
	// go_type key if it has a shape.
	Payload json.RawMessage `json:"payload"`
	// What collapses several of these into one inbox line, decided when the
	// announcement was written and copied onto the line when the audience is
	// resolved.
	GroupKey *string `json:"groupKey,omitempty"`
	// A recipient list captured at write time, and the one exception to computing
	// the audience late. Null is the ordinary case; a list here skips the question
	// entirely, for an audience that genuinely cannot be re-derived.
	AccountIds []uuid.UUID `json:"accountIds,omitempty"`
	// When a dispatcher took this to resolve. Past notifications.claim_ttl another
	// may, which is what makes a crashed process recoverable.
	ClaimedAt *time.Time `json:"claimedAt,omitempty"`
	// Which process holds the lease, so a stuck one traces to a pod rather than to
	// a mystery.
	ClaimedBy *uuid.UUID `json:"claimedBy,omitempty"`
	// How many times resolving this has been attempted.
	Attempts int `json:"attempts"`
}

// A page of Notifications.
type NotificationListResponse struct {
	// The rows in this page.
	Data []Notification `json:"data,omitempty"`
	// Where this page sits in the full result set.
	Pagination Pagination `json:"pagination"`
}
