// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

// The coarse level an account holds in its tenant.
type RigAccountRoleLevel string

// The values of RigAccountRoleLevel.
const (
	// Runs the tenant.
	RigAccountRoleLevelOwner RigAccountRoleLevel = "Owner"
	// Administers it without owning it.
	RigAccountRoleLevelAdmin RigAccountRoleLevel = "Admin"
	// An ordinary member. This is the default.
	RigAccountRoleLevelBasic RigAccountRoleLevel = "Basic"
)

// AllRigAccountRoleLevel is every value, in declaration order. It is what a
// picker is drawn from.
var AllRigAccountRoleLevel = []RigAccountRoleLevel{RigAccountRoleLevelOwner, RigAccountRoleLevelAdmin, RigAccountRoleLevelBasic}

// String implements fmt.Stringer.
func (v RigAccountRoleLevel) String() string { return string(v) }
