// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

import (
	"context"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/google/uuid"
	"github.com/simonjanss/rig/rigclient"
)

// RigNotificationDeviceClient calls the RigNotificationDevice endpoints. It is
// reached as Client.RigNotificationDevices rather than built directly.
type RigNotificationDeviceClient struct{ rt *rigclient.Runtime }

// List RigNotificationDevices.
//
// GET /api/v1/rig-notification-devices
//
// Operation listRigNotificationDevices.
func (c *RigNotificationDeviceClient) List(ctx context.Context, q RigNotificationDeviceListQuery, opts ...rigclient.CallOption) (*RigNotificationDeviceListResponse, error) {
	query := url.Values{}
	rigclient.SetInt(query, "limit", q.Limit)
	rigclient.SetInt(query, "offset", q.Offset)
	rigclient.SetString(query, "scope", q.Scope)

	op := rigclient.Op{
		Name:   "listRigNotificationDevices",
		Method: http.MethodGet,
		Path:   "/rig-notification-devices",
		Query:  query,
	}
	return rigclient.Do[RigNotificationDeviceListResponse](ctx, c.rt, op, opts...)
}

// Create a RigNotificationDevice.
//
// POST /api/v1/rig-notification-devices
//
// Operation createRigNotificationDevice.
//
// A refusal is read back with [RigNotificationDeviceCreateError], whose Fields
// say what was wrong with each member of the body.
func (c *RigNotificationDeviceClient) Create(ctx context.Context, in RigNotificationDeviceCreateInput, opts ...rigclient.CallOption) (*RigNotificationDevice, error) {
	op := rigclient.Op{
		Name:   "createRigNotificationDevice",
		Method: http.MethodPost,
		Path:   "/rig-notification-devices",
		Body:   in,
	}
	return rigclient.Do[RigNotificationDevice](ctx, c.rt, op, opts...)
}

// Delete a RigNotificationDevice.
//
// DELETE /api/v1/rig-notification-devices/{id}
//
// Operation deleteRigNotificationDevice.
func (c *RigNotificationDeviceClient) Delete(ctx context.Context, id uuid.UUID, opts ...rigclient.CallOption) error {
	op := rigclient.Op{
		Name:   "deleteRigNotificationDevice",
		Method: http.MethodDelete,
		Path:   strings.Replace("/rig-notification-devices/{id}", "{id}", rigclient.PathValue(id.String()), 1),
	}
	return rigclient.DoNoContent(ctx, c.rt, op, opts...)
}

// All reads every RigNotificationDevice the query matches, a page at a time.
//
// The query's own limit is the page size, and its offset is where the walk
// starts. Iteration stops at the first failure, which arrives as the second
// value of the last pair — so a loop that ignores it is a loop that silently
// stops early.
func (c *RigNotificationDeviceClient) All(ctx context.Context, q RigNotificationDeviceListQuery, opts ...rigclient.CallOption) iter.Seq2[RigNotificationDevice, error] {
	start := 0
	if q.Offset != nil {
		start = *q.Offset
	}

	return rigclient.Paginate(ctx, start, func(ctx context.Context, offset int) (rigclient.Page[RigNotificationDevice], error) {
		q := q
		q.Offset = &offset

		res, err := c.List(ctx, q, opts...)
		if err != nil {
			return rigclient.Page[RigNotificationDevice]{}, err
		}
		if res == nil {
			return rigclient.Page[RigNotificationDevice]{}, nil
		}

		return rigclient.Page[RigNotificationDevice]{
			Items:  res.Data,
			Total:  res.Pagination.Total,
			Offset: res.Pagination.Offset,
		}, nil
	})
}
