// Code generated by rig. DO NOT EDIT.
//
// This file is rewritten on every run. Put changes in the service layer.

package client

import (
	"time"

	"github.com/google/uuid"
)

// Where a push can reach somebody. Email is refused: the address is on the
// account already.
//
// Every field the server returns, and no field it does not: this is the
// readable projection of the row rather than the row.
type RigNotificationDevice struct {
	// Unique identifier for this row.
	ID uuid.UUID `json:"id"`
	// Tenant this row belongs to. Every query is scoped by it.
	TenantID uuid.UUID `json:"tenantId"`
	// Whose device it is.
	AccountID uuid.UUID `json:"accountId"`
	// When this row was created. Set automatically and never changes.
	CreatedAt time.Time `json:"createdAt"`
	// When this row was last updated. Set automatically on every update.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Desktop or Mobile. Email is refused by the CHECK above.
	Channel RigNotificationChannel `json:"channel"`
	// What the provider was given to address this device. Opaque to rig.
	Token string `json:"token"`
	// What a person sees in a list of their devices, and the column that makes
	// revoking one possible for somebody who has four.
	Label *string `json:"label,omitempty"`
	// When this device last checked in, so a stale one can be told apart from a
	// revoked one.
	LastSeenAt *time.Time `json:"lastSeenAt,omitempty"`
	// When it stopped being a place to send to. Kept rather than deleted, so a
	// token that comes back can be recognised.
	RevokedAt *time.Time `json:"revokedAt,omitempty"`
}

// A page of RigNotificationDevices.
type RigNotificationDeviceListResponse struct {
	// The rows in this page.
	Data []RigNotificationDevice `json:"data,omitempty"`
	// Where this page sits in the full result set.
	Pagination Pagination `json:"pagination"`
}
